package policies

// userPolicies — User Configuration branch of the catalog + Group Policy
// Preferences (Registry / Files / Shortcuts / Scheduled Tasks / etc).
//
// Scope rules:
//   ScopeUser  — applied at login to the user session (dconf lock, ~/.config).
//   ScopeBoth  — has a machine-default AND a per-user override chain.
var userPolicies = []Policy{
	// ---------------------------------------------------------------
	// User Configuration → Control Panel
	// ---------------------------------------------------------------
	{ID: "u.ctrl-panel.block", Name: "Prohibit access to system settings", WinGPName: "Prohibit access to Control Panel and PC settings", WinGPPath: "User Configuration|Policies|Administrative Templates|Control Panel", Category: []string{"User Configuration", "Administrative Templates", "Control Panel"}, Scope: ScopeUser, Description: "Block gnome-control-center / KDE System Settings for the user. Linux: dconf lock on /org/gnome/desktop/lockdown/disable-user-switching-and-settings + polkit rule to deny org.freedesktop.* admin actions for standard users.", LinuxImpl: "dconf lockdown + polkit"},
	{ID: "u.personalization.wallpaper", Name: "Prevent changing desktop wallpaper", WinGPName: "Prevent changing desktop background", WinGPPath: "User Configuration|Policies|Administrative Templates|Control Panel|Personalization", Category: []string{"User Configuration", "Administrative Templates", "Control Panel", "Personalization"}, Scope: ScopeUser, Description: "Lock the wallpaper to the policy-assigned value. Linux: dconf lock /org/gnome/desktop/background/picture-uri.", LinuxImpl: "dconf lock picture-uri"},
	{ID: "u.personalization.screensaver", Name: "Prevent changing screen-lock settings", WinGPName: "Prevent changing screen saver", WinGPPath: "User Configuration|Policies|Administrative Templates|Control Panel|Personalization", Category: []string{"User Configuration", "Administrative Templates", "Control Panel", "Personalization"}, Scope: ScopeUser, Description: "Lock idle-delay and screensaver settings. Linux: dconf lock /org/gnome/desktop/session/idle-delay and /org/gnome/desktop/screensaver/lock-*.", LinuxImpl: "dconf lock screensaver"},
	{ID: "u.display.hide-settings-tab", Name: "Hide the Display settings tab", WinGPName: "Hide Settings tab", WinGPPath: "User Configuration|Policies|Administrative Templates|Control Panel|Display", Category: []string{"User Configuration", "Administrative Templates", "Control Panel", "Display"}, Scope: ScopeUser, Description: "Hide the Display panel from the Settings app. Linux: gsettings org.gnome.settings-daemon.plugins.xsettings disabled-plugins + gnome-control-center panel hiding via dconf lockdown.", LinuxImpl: "dconf + panel lockdown"},
	{ID: "u.locale.restrict", Name: "Restrict selectable UI languages", WinGPName: "Restrict selection of Windows menus and dialogs language", WinGPPath: "User Configuration|Policies|Administrative Templates|Control Panel|Regional and Language Options", Category: []string{"User Configuration", "Administrative Templates", "Control Panel", "Regional and Language"}, Scope: ScopeUser, Description: "Limit the set of UI languages the user can switch to. Linux: AccountsService allowed Language + localectl available locales.", LinuxImpl: "AccountsService + localectl"},

	// ---------------------------------------------------------------
	// User Configuration → Desktop
	// ---------------------------------------------------------------
	{ID: "u.desktop.hide-all", Name: "Hide all desktop icons", WinGPName: "Hide and disable all items on the desktop", WinGPPath: "User Configuration|Policies|Administrative Templates|Desktop", Category: []string{"User Configuration", "Administrative Templates", "Desktop"}, Scope: ScopeUser, Description: "Hide icons on the user's desktop. Linux: dconf lock /org/nautilus/desktop/* (GNOME Classic) or kwriteconfig for KDE.", LinuxImpl: "dconf / kwriteconfig"},
	{ID: "u.desktop.hide-trash", Name: "Hide the Trash icon", WinGPName: "Remove Recycle Bin icon from desktop", WinGPPath: "User Configuration|Policies|Administrative Templates|Desktop", Category: []string{"User Configuration", "Administrative Templates", "Desktop"}, Scope: ScopeUser, Description: "Remove the user-visible Trash icon. Linux: dconf lock of the desktop icon extension (GNOME 'Desktop Icons NG').", LinuxImpl: "dconf lock desktop-icons trash"},
	{ID: "u.desktop.lock-home-path", Name: "Lock path of user home folders (Documents etc.)", WinGPName: "Prohibit user from changing My Documents path", WinGPPath: "User Configuration|Policies|Administrative Templates|Desktop", Category: []string{"User Configuration", "Administrative Templates", "Desktop"}, Scope: ScopeUser, Description: "Prevent moving XDG user directories. Linux: make ~/.config/user-dirs.conf enabled=false and deploy fixed ~/.config/user-dirs.dirs.", LinuxImpl: "xdg-user-dirs.conf"},

	// ---------------------------------------------------------------
	// User Configuration → Start Menu and Taskbar
	// ---------------------------------------------------------------
	{ID: "u.shell.lock-taskbar", Name: "Lock the taskbar / dash", WinGPName: "Lock the Taskbar", WinGPPath: "User Configuration|Policies|Administrative Templates|Start Menu and Taskbar", Category: []string{"User Configuration", "Administrative Templates", "Shell", "Panel"}, Scope: ScopeUser, Description: "Prevent the user from reorganising the dash/taskbar. Linux: dconf lock /org/gnome/shell/favorite-apps and /org/gnome/shell/extensions/dash-to-dock/*.", LinuxImpl: "dconf lock favorite-apps"},
	{ID: "u.shell.hide-run", Name: "Hide the Run / exec dialog", WinGPName: "Remove Run menu from Start Menu", WinGPPath: "User Configuration|Policies|Administrative Templates|Start Menu and Taskbar", Category: []string{"User Configuration", "Administrative Templates", "Shell", "Launcher"}, Scope: ScopeUser, Description: "Prevent launching arbitrary commands through a Run dialog. Linux: disable gnome-shell command-prompt extension and restrict Ctrl-Alt-F2 TTY switch via logind.", LinuxImpl: "gnome-shell lockdown"},
	{ID: "u.shell.notification-area", Name: "Hide the notification area / system tray", WinGPName: "Hide the notification area", WinGPPath: "User Configuration|Policies|Administrative Templates|Start Menu and Taskbar", Category: []string{"User Configuration", "Administrative Templates", "Shell", "Panel"}, Scope: ScopeUser, Description: "Visibility of system-tray icons. Linux: dconf /org/gnome/shell/extensions/appindicator/enabled; KDE Plasma panel script.", LinuxImpl: "dconf / plasma panel"},
	{ID: "u.shell.remove-settings", Name: "Remove Settings entry from Start Menu", WinGPName: "Remove Programs on Settings menu", WinGPPath: "User Configuration|Policies|Administrative Templates|Start Menu and Taskbar", Category: []string{"User Configuration", "Administrative Templates", "Shell", "Launcher"}, Scope: ScopeUser, Description: "Remove the Settings entry from the user's application grid.", LinuxImpl: "~/.local/share/applications override (NoDisplay=true)"},
	{ID: "u.shell.menu-overrides", Name: "Application menu overrides", WinGPName: "Remove common program groups from Start Menu", WinGPPath: "User Configuration|Policies|Administrative Templates|Start Menu and Taskbar", Category: []string{"User Configuration", "Administrative Templates", "Shell", "Launcher"}, Scope: ScopeUser, Description: "Hide or override entries in the application launcher. Linux: drop .desktop files with Hidden=true under /etc/xdg/menus or per-user ~/.local/share/applications.", LinuxImpl: ".desktop NoDisplay / Hidden"},

	// ---------------------------------------------------------------
	// User Configuration → System
	// ---------------------------------------------------------------
	{ID: "u.sys.no-shell", Name: "Prevent access to the terminal / command shell", WinGPName: "Prevent access to the command prompt", WinGPPath: "User Configuration|Policies|Administrative Templates|System", Category: []string{"User Configuration", "Administrative Templates", "System"}, Scope: ScopeUser, Description: "Hide/disable terminal emulators for kiosk-class users. Linux: chmod 0700 on terminal binaries for the user group is brittle — the supported approach is to AppArmor-deny launching /usr/bin/{bash,gnome-terminal,...} for members of a policy group, plus remove .desktop launchers.", LinuxImpl: "AppArmor deny + .desktop removal"},
	{ID: "u.sys.no-registry-editor", Name: "Prevent access to configuration-editor tools", WinGPName: "Prevent access to registry editing tools", WinGPPath: "User Configuration|Policies|Administrative Templates|System", Category: []string{"User Configuration", "Administrative Templates", "System"}, Scope: ScopeUser, Description: "Block launching of dconf-editor / gsettings-editor. Linux: remove .desktop and AppArmor-deny the binaries for the user's group.", LinuxImpl: "AppArmor deny dconf-editor"},
	{ID: "u.sys.run-only-allowed", Name: "Run only explicitly allowed applications", WinGPName: "Run only specified Windows applications", WinGPPath: "User Configuration|Policies|Administrative Templates|System", Category: []string{"User Configuration", "Administrative Templates", "System"}, Scope: ScopeUser, Description: "Kiosk allow-list. Linux: per-user AppArmor profile or fapolicyd rule scoped to the user.", LinuxImpl: "AppArmor user profile / fapolicyd"},
	{ID: "u.sys.run-deny", Name: "Block specified applications", WinGPName: "Don't run specified Windows applications", WinGPPath: "User Configuration|Policies|Administrative Templates|System", Category: []string{"User Configuration", "Administrative Templates", "System"}, Scope: ScopeUser, Description: "Deny-list for the user. Same mechanism as allow-list, inverse.", LinuxImpl: "AppArmor / fapolicyd deny"},
	{ID: "u.sys.autoplay", Name: "Disable removable-media autoplay", WinGPName: "Turn off Autoplay", WinGPPath: "User Configuration|Policies|Administrative Templates|System", Category: []string{"User Configuration", "Administrative Templates", "System"}, Scope: ScopeUser, Description: "Prevent automatic mount/open of inserted USB drives and optical media. Linux: gsettings org.gnome.desktop.media-handling automount=false automount-open=false, plus udisks2 polkit deny.", LinuxImpl: "dconf media-handling / udisks2 polkit"},
	{ID: "u.sys.custom-shell", Name: "Custom session shell override", WinGPName: "Custom User Interface", WinGPPath: "User Configuration|Policies|Administrative Templates|System", Category: []string{"User Configuration", "Administrative Templates", "System"}, Scope: ScopeUser, Description: "Replace the user's desktop shell (for single-app kiosks). Linux: .xsession / AccountsService Session override pointing at a custom GDM session definition.", LinuxImpl: ".xsession / AccountsService Session"},
	{ID: "u.sys.autostart", Name: "Programs to run at session start", WinGPName: "Run these programs at user logon", WinGPPath: "User Configuration|Policies|Administrative Templates|System|Logon", Category: []string{"User Configuration", "Administrative Templates", "System", "Logon"}, Scope: ScopeUser, Description: "Applications launched automatically when the user logs in. Linux: ~/.config/autostart/*.desktop or systemd user unit.", LinuxImpl: "~/.config/autostart / systemd --user"},

	// ---------------------------------------------------------------
	// User Configuration → Windows Components
	// ---------------------------------------------------------------
	{ID: "u.filemgr.no-net-drive", Name: "Disable network-drive mapping UI", WinGPName: "Remove Map Network Drive and Disconnect Network Drive", WinGPPath: "User Configuration|Policies|Administrative Templates|Windows Components|File Explorer", Category: []string{"User Configuration", "Administrative Templates", "File Manager"}, Scope: ScopeUser, Description: "Hide UI for user-initiated SMB/NFS mounts. Linux: gsettings org.gnome.nautilus.preferences hide-mount-dialog; gvfs deny mount via polkit.", LinuxImpl: "dconf nautilus + polkit gvfs"},
	{ID: "u.filemgr.hide-drives", Name: "Hide specific drives in file manager", WinGPName: "Hide these specified drives in My Computer", WinGPPath: "User Configuration|Policies|Administrative Templates|Windows Components|File Explorer", Category: []string{"User Configuration", "Administrative Templates", "File Manager"}, Scope: ScopeUser, Description: "Remove specific device paths from the side-bar. Linux: udisks2 polkit rule on specific device paths + gvfs blacklist.", LinuxImpl: "udisks2 polkit / gvfs blacklist"},
	{ID: "u.browser.edge-user", Name: "Browser managed preferences (user-scope)", WinGPName: "Microsoft Edge (user)", WinGPPath: "User Configuration|Policies|Administrative Templates|Microsoft Edge", Category: []string{"User Configuration", "Administrative Templates", "Browser"}, Scope: ScopeUser, Description: "Per-user browser policy (homepage, allowed extensions, bookmarks). Linux: same JSON policy format as computer scope, but under ~/.config/{BraveSoftware,edge,chromium}/... — effective only if the user owns the directory.", LinuxImpl: "per-user policies.json"},
	{ID: "u.installer.user", Name: "Disable per-user app installs", WinGPName: "Windows Installer (user)", WinGPPath: "User Configuration|Policies|Administrative Templates|Windows Components|Windows Installer", Category: []string{"User Configuration", "Administrative Templates", "Installer"}, Scope: ScopeUser, Description: "Whether the user can install flatpak --user, pip --user, npm -g, cargo install. Linux: chmod/chown ~/.local/bin and mask per-user systemd, plus polkit deny on org.freedesktop.Flatpak.app-install.", LinuxImpl: "polkit flatpak user-install"},

	// ---------------------------------------------------------------
	// User Configuration → Scripts (Logon/Logoff)
	// ---------------------------------------------------------------
	{ID: "u.scripts.logon", Name: "Logon script (runs as user)", WinGPName: "Logon", WinGPPath: "User Configuration|Policies|Windows Settings|Scripts (Logon/Logoff)", Category: []string{"User Configuration", "Scripts (Logon/Logoff)"}, Scope: ScopeUser, Description: "Script executed at session start, running as the user. Linux: systemd user unit (systemd --user) WantedBy=default.target, or /etc/profile.d/ for shell-started sessions.", LinuxImpl: "systemd --user unit"},
	{ID: "u.scripts.logoff", Name: "Logoff script (runs as user)", WinGPName: "Logoff", WinGPPath: "User Configuration|Policies|Windows Settings|Scripts (Logon/Logoff)", Category: []string{"User Configuration", "Scripts (Logon/Logoff)"}, Scope: ScopeUser, Description: "Script at session end. Linux: systemd user unit with ExecStop=; or gnome-session logout hook.", LinuxImpl: "systemd --user ExecStop"},

	// ---------------------------------------------------------------
	// Group Policy Preferences (both scopes) — Registry / Files /
	// Folders / Shortcuts / Drive Maps / Environment / Scheduled Tasks
	// ---------------------------------------------------------------
	{ID: "pref.registry.machine", Name: "Registry-style settings (machine)", WinGPName: "Preferences > Windows Settings > Registry (Computer)", WinGPPath: "Computer Configuration|Preferences|Windows Settings|Registry", Category: []string{"Computer Configuration", "Preferences", "Registry"}, Scope: ScopeComputer, Description: "Arbitrary machine-scope config-key assignments. On Linux the \"registry\" is split across many backends: sysctl (/etc/sysctl.d), dconf db (for GSettings defaults), and config drop-ins under /etc. Pluris normalises these under one editor that writes to the right backend based on the key prefix.", LinuxImpl: "sysctl.d / dconf system-db / /etc drop-ins"},
	{ID: "pref.registry.user", Name: "Registry-style settings (user)", WinGPName: "Preferences > Windows Settings > Registry (User)", WinGPPath: "User Configuration|Preferences|Windows Settings|Registry", Category: []string{"User Configuration", "Preferences", "Registry"}, Scope: ScopeUser, Description: "Per-user config-key overrides. Linux: GSettings via dconf (/org/... keys), KDE kconfig, and drop-ins under ~/.config.", LinuxImpl: "dconf user-db / ~/.config"},
	{ID: "pref.files.machine", Name: "Files to deploy (machine)", WinGPName: "Preferences > Windows Settings > Files (Computer)", WinGPPath: "Computer Configuration|Preferences|Windows Settings|Files", Category: []string{"Computer Configuration", "Preferences", "Files"}, Scope: ScopeComputer, Description: "Ship a file to a path on every target. Linux: systemd-tmpfiles (/etc/tmpfiles.d with C type for copy) or pluris-agent file drop.", LinuxImpl: "systemd-tmpfiles / agent file drop"},
	{ID: "pref.files.user", Name: "Files to deploy (user)", WinGPName: "Preferences > Windows Settings > Files (User)", WinGPPath: "User Configuration|Preferences|Windows Settings|Files", Category: []string{"User Configuration", "Preferences", "Files"}, Scope: ScopeUser, Description: "Ship a file into the user's home. Linux: systemd-tmpfiles-user (~/.config/user-tmpfiles.d) or pluris-agent per-user drop.", LinuxImpl: "systemd-tmpfiles-user"},
	{ID: "pref.folders.machine", Name: "Folders to create (machine)", WinGPName: "Preferences > Windows Settings > Folders (Computer)", WinGPPath: "Computer Configuration|Preferences|Windows Settings|Folders", Category: []string{"Computer Configuration", "Preferences", "Folders"}, Scope: ScopeComputer, Description: "Ensure a directory exists with given owner/mode. Linux: systemd-tmpfiles 'd' type entries.", LinuxImpl: "systemd-tmpfiles d"},
	{ID: "pref.shortcuts.machine", Name: "Shortcuts / launchers (machine)", WinGPName: "Preferences > Windows Settings > Shortcuts (Computer)", WinGPPath: "Computer Configuration|Preferences|Windows Settings|Shortcuts", Category: []string{"Computer Configuration", "Preferences", "Shortcuts"}, Scope: ScopeComputer, Description: "Desktop launchers deployed system-wide. Linux: .desktop files under /usr/local/share/applications.", LinuxImpl: "/usr/local/share/applications .desktop"},
	{ID: "pref.shortcuts.user", Name: "Shortcuts / launchers (user)", WinGPName: "Preferences > Windows Settings > Shortcuts (User)", WinGPPath: "User Configuration|Preferences|Windows Settings|Shortcuts", Category: []string{"User Configuration", "Preferences", "Shortcuts"}, Scope: ScopeUser, Description: "Per-user launchers. Linux: ~/.local/share/applications/*.desktop.", LinuxImpl: "~/.local/share/applications"},
	{ID: "pref.drive-maps.user", Name: "Drive / share maps (user)", WinGPName: "Preferences > Windows Settings > Drive Maps (User)", WinGPPath: "User Configuration|Preferences|Windows Settings|Drive Maps", Category: []string{"User Configuration", "Preferences", "Drive Maps"}, Scope: ScopeUser, Description: "Auto-mount network shares at logon. Linux: autofs with Kerberos credentials, or gio mount via pam_mount.", LinuxImpl: "autofs / pam_mount"},
	{ID: "pref.env.machine", Name: "Environment variables (machine)", WinGPName: "Preferences > Windows Settings > Environment (Computer)", WinGPPath: "Computer Configuration|Preferences|Windows Settings|Environment", Category: []string{"Computer Configuration", "Preferences", "Environment"}, Scope: ScopeComputer, Description: "Machine-wide environment variables. Linux: /etc/environment plus /etc/profile.d for shell-only vars.", LinuxImpl: "/etc/environment / /etc/profile.d"},
	{ID: "pref.env.user", Name: "Environment variables (user)", WinGPName: "Preferences > Windows Settings > Environment (User)", WinGPPath: "User Configuration|Preferences|Windows Settings|Environment", Category: []string{"User Configuration", "Preferences", "Environment"}, Scope: ScopeUser, Description: "Per-user environment variables. Linux: ~/.config/environment.d/*.conf (systemd user), ~/.profile (login shells).", LinuxImpl: "~/.config/environment.d"},
	{ID: "pref.tasks.machine", Name: "Scheduled tasks (machine)", WinGPName: "Preferences > Control Panel Settings > Scheduled Tasks (Computer)", WinGPPath: "Computer Configuration|Preferences|Control Panel Settings|Scheduled Tasks", Category: []string{"Computer Configuration", "Preferences", "Scheduled Tasks"}, Scope: ScopeComputer, Description: "Recurring jobs that run as root. Linux: systemd timer units or /etc/cron.d drop-in.", LinuxImpl: "systemd .timer / cron.d"},
	{ID: "pref.tasks.user", Name: "Scheduled tasks (user)", WinGPName: "Preferences > Control Panel Settings > Scheduled Tasks (User)", WinGPPath: "User Configuration|Preferences|Control Panel Settings|Scheduled Tasks", Category: []string{"User Configuration", "Preferences", "Scheduled Tasks"}, Scope: ScopeUser, Description: "Recurring jobs under the user's session. Linux: systemd --user timer or crontab -e.", LinuxImpl: "systemd --user .timer / crontab"},
	{ID: "pref.printers.machine", Name: "Printers to deploy", WinGPName: "Preferences > Control Panel Settings > Printers", WinGPPath: "Computer Configuration|Preferences|Control Panel Settings|Printers", Category: []string{"Computer Configuration", "Preferences", "Printers"}, Scope: ScopeBoth, Description: "Printers provisioned on the endpoint. Linux: CUPS lpadmin + /etc/cups/printers.conf; per-user overrides via ~/.cups/lpoptions.", LinuxImpl: "CUPS lpadmin"},
	{ID: "pref.power", Name: "Power options preset", WinGPName: "Preferences > Control Panel Settings > Power Options", WinGPPath: "Computer Configuration|Preferences|Control Panel Settings|Power Options", Category: []string{"Computer Configuration", "Preferences", "Power Options"}, Scope: ScopeComputer, Description: "Shortcut preference that writes a TLP / power-profiles-daemon profile with lid/button/timeout values in one go.", LinuxImpl: "tlp / power-profiles-daemon"},
}
