package policies

// computerPolicies — Computer Configuration branch of the catalog.
//
// Ordered the way Windows Group Policy Editor presents them, so admins
// migrating from AD see the same tree. The Category field mirrors the
// Windows tree with the redundant "Policies" / "Security Settings" /
// "Windows Settings" rungs kept for parity; this gives GP import a 1:1
// target and eases muscle memory.
//
// Increment 2 scope: names, windows equivalents, categorisation, scope,
// description, and a one-line hint at the Linux mechanism. The module
// engine that turns these descriptions into enforced state lands in a
// later increment.
var computerPolicies = []Policy{
	// ---------------------------------------------------------------
	// Account Policies → Password Policy
	// ---------------------------------------------------------------
	{
		ID:          "sec.account.password.min-length",
		Name:        "Minimum password length",
		WinGPName:   "Minimum password length",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Password Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Password Policy"},
		Scope:       ScopeComputer,
		Description: "Minimum number of characters required for local user passwords. On Linux this is enforced at password-change time by pam_pwquality / pam_passwdqc; it does not affect existing passwords until they next change.",
		LinuxImpl:   "pam_pwquality minlen= / /etc/security/pwquality.conf",
	},
	{
		ID:          "sec.account.password.history",
		Name:        "Password history remembered",
		WinGPName:   "Enforce password history",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Password Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Password Policy"},
		Scope:       ScopeComputer,
		Description: "Number of previous passwords the system refuses to reuse. Requires the PAM unix module to be configured with the remember= option, which stores hashed history in /etc/security/opasswd.",
		LinuxImpl:   "pam_unix remember= / /etc/security/opasswd",
	},
	{
		ID:          "sec.account.password.max-age",
		Name:        "Maximum password age (days)",
		WinGPName:   "Maximum password age",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Password Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Password Policy"},
		Scope:       ScopeComputer,
		Description: "Days after which a password must be changed. Applied as a default for new accounts via login.defs and to existing accounts via chage.",
		LinuxImpl:   "/etc/login.defs PASS_MAX_DAYS + chage -M",
	},
	{
		ID:          "sec.account.password.min-age",
		Name:        "Minimum password age (days)",
		WinGPName:   "Minimum password age",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Password Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Password Policy"},
		Scope:       ScopeComputer,
		Description: "Days a password must be kept before the user can change it again. Prevents users cycling through history to reuse a favourite password.",
		LinuxImpl:   "/etc/login.defs PASS_MIN_DAYS + chage -m",
	},
	{
		ID:          "sec.account.password.complexity",
		Name:        "Password must meet complexity requirements",
		WinGPName:   "Password must meet complexity requirements",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Password Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Password Policy"},
		Scope:       ScopeComputer,
		Description: "Requires mix of character classes and rejects dictionary words and the username. Maps to pwquality credit/class requirements (ucredit, lcredit, dcredit, ocredit, minclass) and dictcheck.",
		LinuxImpl:   "pam_pwquality / /etc/security/pwquality.conf",
	},
	{
		ID:          "sec.account.password.reversible-encryption",
		Name:        "Store passwords using reversible encryption",
		WinGPName:   "Store passwords using reversible encryption",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Password Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Password Policy"},
		Scope:       ScopeComputer,
		Description: "Windows-only concept: stores a decryptable password copy. Not implementable on Linux — local accounts always use one-way hashes (yescrypt/sha512). Listed for parity; enforcement on Linux always reports \"disabled\".",
		LinuxImpl:   "n/a (always disabled on Linux)",
	},

	// ---------------------------------------------------------------
	// Account Policies → Account Lockout Policy
	// ---------------------------------------------------------------
	{
		ID:          "sec.account.lockout.threshold",
		Name:        "Account lockout threshold (failed attempts)",
		WinGPName:   "Account lockout threshold",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Account Lockout Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Account Lockout Policy"},
		Scope:       ScopeComputer,
		Description: "Number of failed login attempts that triggers a lockout. Enforced across local logins, SSH, and desktop greeters via pam_faillock.",
		LinuxImpl:   "pam_faillock deny= / /etc/security/faillock.conf",
	},
	{
		ID:          "sec.account.lockout.duration",
		Name:        "Account lockout duration (seconds)",
		WinGPName:   "Account lockout duration",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Account Lockout Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Account Lockout Policy"},
		Scope:       ScopeComputer,
		Description: "How long a locked account stays locked before it auto-unlocks. 0 means locked until admin unlock.",
		LinuxImpl:   "pam_faillock unlock_time=",
	},
	{
		ID:          "sec.account.lockout.reset-after",
		Name:        "Reset lockout counter after (seconds)",
		WinGPName:   "Reset account lockout counter after",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Account Lockout Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Account Lockout Policy"},
		Scope:       ScopeComputer,
		Description: "Sliding window in which failed attempts accumulate. After this interval the counter resets to zero.",
		LinuxImpl:   "pam_faillock fail_interval=",
	},
	{
		ID:          "sec.account.lockout.even-root",
		Name:        "Apply lockout to root / administrator",
		WinGPName:   "Allow Administrator account lockout",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Account Lockout Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Account Lockout Policy"},
		Scope:       ScopeComputer,
		Description: "Whether lockout policy applies to root. Dangerous on systems with no console fallback — lockout can brick remote-only servers.",
		LinuxImpl:   "pam_faillock even_deny_root",
	},

	// ---------------------------------------------------------------
	// Account Policies → Kerberos Policy
	// ---------------------------------------------------------------
	{
		ID:          "sec.kerberos.ticket-lifetime",
		Name:        "Maximum user ticket lifetime (hours)",
		WinGPName:   "Maximum lifetime for user ticket",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Kerberos Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Kerberos Policy"},
		Scope:       ScopeComputer,
		Description: "How long a TGT is valid before the user must re-authenticate. Applied via /etc/krb5.conf on machines joined to a realm via SSSD or Kanidm.",
		LinuxImpl:   "/etc/krb5.conf ticket_lifetime",
	},
	{
		ID:          "sec.kerberos.renew-lifetime",
		Name:        "Maximum ticket renewal lifetime (days)",
		WinGPName:   "Maximum lifetime for user ticket renewal",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Kerberos Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Kerberos Policy"},
		Scope:       ScopeComputer,
		Description: "Total window a TGT can be renewed without re-authenticating. Pass 0 to disallow renewal entirely.",
		LinuxImpl:   "/etc/krb5.conf renew_lifetime",
	},
	{
		ID:          "sec.kerberos.service-ticket-lifetime",
		Name:        "Maximum service ticket lifetime (minutes)",
		WinGPName:   "Maximum lifetime for service ticket",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Kerberos Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Kerberos Policy"},
		Scope:       ScopeComputer,
		Description: "Lifetime of service tickets (TGS). Lower values reduce impact of ticket theft, higher values reduce KDC load.",
		LinuxImpl:   "krb5.conf default_tgs_lifetime",
	},
	{
		ID:          "sec.kerberos.clockskew",
		Name:        "Maximum tolerance for clock synchronisation (minutes)",
		WinGPName:   "Maximum tolerance for computer clock synchronization",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Kerberos Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Kerberos Policy"},
		Scope:       ScopeComputer,
		Description: "Acceptable clock drift between client and KDC. If exceeded, Kerberos refuses authentication — ensure chrony/timesyncd is healthy.",
		LinuxImpl:   "krb5.conf clockskew",
	},
	{
		ID:          "sec.kerberos.logon-restrictions",
		Name:        "Enforce user logon restrictions",
		WinGPName:   "Enforce user logon restrictions",
		WinGPPath:   "Computer Configuration|Policies|Windows Settings|Security Settings|Account Policies|Kerberos Policy",
		Category:    []string{"Computer Configuration", "Security Settings", "Account Policies", "Kerberos Policy"},
		Scope:       ScopeComputer,
		Description: "KDC validates every service ticket request against user account policy (disabled, expired, logon hours). Corresponds to KDC_OPT_ENFORCE; maps to MIT/Heimdal KDC config on Linux KDCs only — on GP-joined clients this setting is informational.",
		LinuxImpl:   "KDC-side (MIT krb5 / Heimdal)",
	},

	// ---------------------------------------------------------------
	// Local Policies → Audit Policy (classic 9 categories)
	// ---------------------------------------------------------------
	{ID: "sec.audit.account-logon", Name: "Audit account logon events", WinGPName: "Audit account logon events", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Audit Policy", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Audit Policy"}, Scope: ScopeComputer, Description: "Log successful and failed validations of an account's credentials (Kerberos AS/TGS, NTLM). On Linux maps to auditd rules on pam_unix/pam_sss and sshd PAM stack.", LinuxImpl: "auditd rules on PAM authentication"},
	{ID: "sec.audit.account-mgmt", Name: "Audit account management", WinGPName: "Audit account management", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Audit Policy", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Audit Policy"}, Scope: ScopeComputer, Description: "Log account creation, modification, deletion, enabling/disabling, group membership changes. Mapped to auditd watches on /etc/passwd, /etc/shadow, /etc/group, /etc/gshadow.", LinuxImpl: "auditd -w /etc/passwd -p wa"},
	{ID: "sec.audit.directory-access", Name: "Audit directory service access", WinGPName: "Audit directory service access", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Audit Policy", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Audit Policy"}, Scope: ScopeComputer, Description: "Log access to directory-service objects. On Linux only meaningful on 389-DS / Kanidm / OpenLDAP servers — maps to their native access log.", LinuxImpl: "389-ds / OpenLDAP access log"},
	{ID: "sec.audit.logon", Name: "Audit logon events", WinGPName: "Audit logon events", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Audit Policy", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Audit Policy"}, Scope: ScopeComputer, Description: "Log each user logon / logoff on the local machine (console, SSH, display manager). Distinct from account-logon which is KDC-side.", LinuxImpl: "auditd + systemd-logind"},
	{ID: "sec.audit.object-access", Name: "Audit object access", WinGPName: "Audit object access", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Audit Policy", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Audit Policy"}, Scope: ScopeComputer, Description: "Log access to individual filesystem objects, registry entries, or named resources that have an audit entry set. On Linux set via auditd path watches.", LinuxImpl: "auditd -w <path> -p rwxa"},
	{ID: "sec.audit.policy-change", Name: "Audit policy change", WinGPName: "Audit policy change", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Audit Policy", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Audit Policy"}, Scope: ScopeComputer, Description: "Log changes to security policy, user rights, audit config, trust relationships. Linux equivalent: watches on /etc/sudoers, /etc/audit/, /etc/security/, SELinux/AppArmor policy.", LinuxImpl: "auditd policy watches"},
	{ID: "sec.audit.privilege-use", Name: "Audit privilege use", WinGPName: "Audit privilege use", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Audit Policy", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Audit Policy"}, Scope: ScopeComputer, Description: "Log use of sensitive privileges (e.g. backup/restore, act as OS). Linux equivalent: sudo logging and auditd rules on capability-granting syscalls (capset).", LinuxImpl: "sudoers log_file + auditd capset"},
	{ID: "sec.audit.process-tracking", Name: "Audit process tracking", WinGPName: "Audit process tracking", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Audit Policy", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Audit Policy"}, Scope: ScopeComputer, Description: "Log every process creation and exit. High volume — consider auditd execve rules with key filters or switch to a lighter-weight tracer (bpftrace).", LinuxImpl: "auditd -a always,exit -F arch=... -S execve"},
	{ID: "sec.audit.system", Name: "Audit system events", WinGPName: "Audit system events", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Audit Policy", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Audit Policy"}, Scope: ScopeComputer, Description: "Log system-wide events: startup, shutdown, security log changes, time changes. Maps to auditd + journal boot/shutdown records.", LinuxImpl: "auditd + journald"},

	// ---------------------------------------------------------------
	// Local Policies → User Rights Assignment (representative)
	// ---------------------------------------------------------------
	{ID: "ura.network-access", Name: "Allow network access to this computer", WinGPName: "Access this computer from the network", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "List of users/groups allowed to reach the machine from the network. On Linux this is split per-service: sshd AllowUsers/AllowGroups, Samba valid users, pam_access source rules.", LinuxImpl: "sshd AllowUsers / pam_access.conf"},
	{ID: "ura.act-as-os", Name: "Act as part of the operating system", WinGPName: "Act as part of the operating system", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Windows privilege for impersonation-like service code. Closest Linux equivalent: restricting CAP_SYS_ADMIN and CAP_SETUID to an allow-list via systemd unit CapabilityBoundingSet=.", LinuxImpl: "systemd CapabilityBoundingSet"},
	{ID: "ura.add-workstations", Name: "Join machines to the directory", WinGPName: "Add workstations to domain", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Which identities can enrol a new machine into the directory. In Pluris mapped to the role that runs realm join / kanidm domain ldap_basedn and issues host keytabs.", LinuxImpl: "Kanidm / SSSD role"},
	{ID: "ura.adjust-memory", Name: "Adjust memory quotas for a process", WinGPName: "Adjust memory quotas for a process", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "On Windows controls SetProcessWorkingSetSize. On Linux maps to cgroup memory controller delegation via systemd user slices and /etc/security/limits.conf RSS caps.", LinuxImpl: "cgroups / /etc/security/limits.conf"},
	{ID: "ura.logon-locally", Name: "Allow log on locally", WinGPName: "Allow log on locally", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Users permitted console / display-manager logins. Enforced by pam_access.conf on the login, gdm-password, and lightdm PAM stacks.", LinuxImpl: "pam_access.conf"},
	{ID: "ura.logon-remote", Name: "Allow log on through Remote Desktop / SSH", WinGPName: "Allow log on through Remote Desktop Services", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Who can log in remotely. On Linux split: sshd AllowUsers/AllowGroups for SSH, xrdp permissions for RDP-style remote desktop.", LinuxImpl: "sshd_config + xrdp"},
	{ID: "ura.backup-files", Name: "Bypass file ACLs for backup", WinGPName: "Back up files and directories", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Permission to read any file regardless of DAC. Linux equivalent: granting CAP_DAC_READ_SEARCH to the backup service unit.", LinuxImpl: "CAP_DAC_READ_SEARCH via systemd AmbientCapabilities"},
	{ID: "ura.change-time", Name: "Change the system time", WinGPName: "Change the system time", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Who may change the wall-clock. Linux: CAP_SYS_TIME plus polkit rule for org.freedesktop.timedate1.set-time.", LinuxImpl: "polkit timedate1 + CAP_SYS_TIME"},
	{ID: "ura.debug-programs", Name: "Debug programs", WinGPName: "Debug programs", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Attach a debugger to an arbitrary process. Linux: kernel.yama.ptrace_scope sysctl plus CAP_SYS_PTRACE. 0=classic, 1=restricted (default), 2=admin-only, 3=disabled.", LinuxImpl: "sysctl kernel.yama.ptrace_scope"},
	{ID: "ura.deny-network", Name: "Deny network access", WinGPName: "Deny access to this computer from the network", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Block list for remote access. Enforced alongside the allow list via sshd DenyUsers/DenyGroups and pam_access rules.", LinuxImpl: "sshd DenyUsers / pam_access"},
	{ID: "ura.deny-logon-locally", Name: "Deny log on locally", WinGPName: "Deny log on locally", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Block list for console/GUI logins. pam_access.conf deny rules, evaluated before the allow list.", LinuxImpl: "pam_access.conf deny"},
	{ID: "ura.shutdown-remote", Name: "Force shutdown from a remote system", WinGPName: "Force shutdown from a remote system", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Who may trigger remote reboot/shutdown. Linux: polkit rule for org.freedesktop.login1.power-off plus sudoers for /sbin/shutdown.", LinuxImpl: "polkit login1 + sudoers"},
	{ID: "ura.generate-audit", Name: "Generate security audits", WinGPName: "Generate security audits", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Which processes can write to the security audit log. Linux: CAP_AUDIT_WRITE capability (granted by default to sshd and pam_audit).", LinuxImpl: "CAP_AUDIT_WRITE"},
	{ID: "ura.load-drivers", Name: "Load and unload kernel modules", WinGPName: "Load and unload device drivers", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Who can call insmod/modprobe/rmmod. Linux: CAP_SYS_MODULE plus kernel.modules_disabled sysctl. In Secure Boot lockdown mode module signing is also enforced.", LinuxImpl: "CAP_SYS_MODULE + kernel lockdown"},
	{ID: "ura.lock-pages", Name: "Lock pages in memory", WinGPName: "Lock pages in memory", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Permission to call mlock/mlockall and keep pages non-swappable. Linux: ulimit -l and /etc/security/limits.conf memlock.", LinuxImpl: "/etc/security/limits.conf memlock"},
	{ID: "ura.logon-batch", Name: "Log on as a batch job (cron)", WinGPName: "Log on as a batch job", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Who may have cron/at jobs execute. Enforced via /etc/cron.allow, /etc/cron.deny, /etc/at.allow.", LinuxImpl: "/etc/cron.allow /etc/at.allow"},
	{ID: "ura.logon-service", Name: "Log on as a service", WinGPName: "Log on as a service", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Accounts under which systemd services may run. Validated at unit-generation time: ensures User= field of any .service file belongs to this set.", LinuxImpl: "systemd unit User= allow-list"},
	{ID: "ura.manage-audit", Name: "Manage auditing and security log", WinGPName: "Manage auditing and security log", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Who may read or configure the audit subsystem. Linux: CAP_AUDIT_CONTROL and CAP_AUDIT_READ, plus membership of adm/systemd-journal groups.", LinuxImpl: "CAP_AUDIT_CONTROL + systemd-journal group"},
	{ID: "ura.firmware-env", Name: "Modify firmware environment values", WinGPName: "Modify firmware environment values", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Who can rewrite UEFI/NVRAM variables. Linux: CAP_SYS_ADMIN on /sys/firmware/efi/efivars plus Secure Boot lockdown gating.", LinuxImpl: "/sys/firmware/efi/efivars + lockdown"},
	{ID: "ura.profile-proc", Name: "Profile single process", WinGPName: "Profile single process", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Allow user to run perf-style counters against one process. Linux: kernel.perf_event_paranoid sysctl (1 or 2 permits per-process).", LinuxImpl: "sysctl kernel.perf_event_paranoid"},
	{ID: "ura.profile-sys", Name: "Profile system performance", WinGPName: "Profile system performance", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "System-wide profiling. Linux: kernel.perf_event_paranoid = -1 (or 0) plus CAP_PERFMON capability (5.8+).", LinuxImpl: "sysctl + CAP_PERFMON"},
	{ID: "ura.restore-files", Name: "Restore files and directories", WinGPName: "Restore files and directories", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Who may write files bypassing DAC (for restore). Linux: CAP_DAC_OVERRIDE on the restore service.", LinuxImpl: "CAP_DAC_OVERRIDE"},
	{ID: "ura.shutdown-sys", Name: "Shut down the system", WinGPName: "Shut down the system", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Who can initiate a local shutdown/reboot. Linux: polkit action org.freedesktop.login1.power-off.", LinuxImpl: "polkit login1.power-off"},
	{ID: "ura.take-ownership", Name: "Take ownership of files or other objects", WinGPName: "Take ownership of files or other objects", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|User Rights Assignment", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "User Rights Assignment"}, Scope: ScopeComputer, Description: "Change UID/GID owner of arbitrary files. Linux: CAP_CHOWN plus CAP_FOWNER.", LinuxImpl: "CAP_CHOWN + CAP_FOWNER"},

	// ---------------------------------------------------------------
	// Local Policies → Security Options
	// ---------------------------------------------------------------
	{ID: "sec.opt.root-status", Name: "Root account status", WinGPName: "Accounts: Administrator account status", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Whether the root account accepts passwords. Recommended state on managed endpoints: locked (passwd -l root); admins escalate through sudo instead.", LinuxImpl: "passwd -l root / passwd -u root"},
	{ID: "sec.opt.guest-status", Name: "Guest account status", WinGPName: "Accounts: Guest account status", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Whether an unauthenticated guest desktop session is offered. Managed by AccountsService and the display-manager (gdm/lightdm) guest-session setting.", LinuxImpl: "AccountsService + gdm/lightdm guest-session"},
	{ID: "sec.opt.rename-admin", Name: "Rename root / primary admin account", WinGPName: "Accounts: Rename administrator account", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "On Windows renames the built-in Administrator. On Linux the UID 0 account is conventionally named 'root' and renaming it breaks assumptions in many tools — Pluris recommends leaving root as-is and instead controlling access via sudo + named admin accounts.", LinuxImpl: "advisory — do not rename uid 0"},
	{ID: "sec.opt.null-passwords-console", Name: "Limit blank passwords to console", WinGPName: "Accounts: Limit local account use of blank passwords to console logon only", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Prevent empty-password accounts from authenticating over network services. Mapped to removing nullok from non-console PAM stacks (sshd, su).", LinuxImpl: "pam_unix nullok removal"},
	{ID: "sec.opt.audit-shutdown-on-fail", Name: "Shut down immediately if unable to log audits", WinGPName: "Audit: Shut down system immediately if unable to log security audits", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Halt on audit-write failure for compliance profiles (PCI-DSS/STIG). Linux: auditd disk_error_action=HALT and disk_full_action=HALT.", LinuxImpl: "auditd.conf disk_error_action=HALT"},
	{ID: "sec.opt.ctrl-alt-del", Name: "Disable Ctrl-Alt-Del reboot", WinGPName: "Interactive logon: Do not require CTRL+ALT+DEL", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "On Linux the console Ctrl-Alt-Del key combo reboots via systemd. This policy enables or disables that behaviour.", LinuxImpl: "systemctl mask ctrl-alt-del.target"},
	{ID: "sec.opt.hide-last-user", Name: "Do not display last signed-in user on greeter", WinGPName: "Interactive logon: Don't display last signed-in", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Suppress the username on the display-manager greeter. Mapped to gdm / lightdm config — hide user list, force manual username entry.", LinuxImpl: "gdm disable-user-list / lightdm greeter-hide-users"},
	{ID: "sec.opt.logon-banner-text", Name: "Pre-logon banner text", WinGPName: "Interactive logon: Message text for users attempting to log on", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Legal/usage banner shown before interactive logon. On Linux maps to /etc/issue (console), /etc/issue.net (telnet/SSH pre-auth), and sshd Banner directive.", LinuxImpl: "/etc/issue /etc/issue.net sshd Banner"},
	{ID: "sec.opt.logon-banner-title", Name: "Pre-logon banner title", WinGPName: "Interactive logon: Message title for users attempting to log on", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Title line of the banner. On Linux concatenated to /etc/issue header; graphical greeters render it as a separate emphasis line.", LinuxImpl: "/etc/issue header"},
	{ID: "sec.opt.cached-logons", Name: "Number of previous logons to cache", WinGPName: "Interactive logon: Number of previous logons to cache", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "How many recent directory logins SSSD caches for offline use. Offline unlock of an encrypted desktop depends on this being > 0.", LinuxImpl: "sssd.conf cache_credentials=true + entry_cache_timeout"},
	{ID: "sec.opt.password-warn", Name: "Warn user N days before password expiry", WinGPName: "Interactive logon: Prompt user to change password before expiration", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "How many days in advance to warn the user about expiry.", LinuxImpl: "/etc/login.defs PASS_WARN_AGE"},
	{ID: "sec.opt.require-smartcard", Name: "Require smart-card login", WinGPName: "Interactive logon: Require smart card", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Force smart-card auth for interactive logon. Linux: pam_pkcs11 / sssd with certificate mapping; requires PKCS#11 middleware (OpenSC / manufacturer driver).", LinuxImpl: "pam_pkcs11 / sssd p11_kit"},
	{ID: "sec.opt.smartcard-removal", Name: "Action on smart-card removal", WinGPName: "Interactive logon: Smart card removal behavior", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "None / Lock / Force logoff when the card is pulled. Linux: sssd-smartcard + logind lock-session hook.", LinuxImpl: "sssd smartcard + systemd-logind"},
	{ID: "sec.opt.smb-client-sign", Name: "SMB client: require signing", WinGPName: "Microsoft network client: Digitally sign communications (always)", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Require SMB signing from Linux SMB clients. Maps to smb.conf 'client signing = mandatory'.", LinuxImpl: "smb.conf client signing"},
	{ID: "sec.opt.smb-server-sign", Name: "SMB server: require signing", WinGPName: "Microsoft network server: Digitally sign communications (always)", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Force SMB signing on inbound shares. Maps to smb.conf 'server signing = mandatory' on any host running smbd.", LinuxImpl: "smb.conf server signing"},
	{ID: "sec.opt.anon-sam", Name: "Block anonymous directory enumeration", WinGPName: "Network access: Do not allow anonymous enumeration of SAM accounts", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Refuse anonymous user-list requests. For Linux SMB servers: smb.conf 'restrict anonymous = 2'. For LDAP/Kanidm: require authenticated bind.", LinuxImpl: "smb.conf restrict anonymous / LDAP no-anon"},
	{ID: "sec.opt.kerb-enctypes", Name: "Kerberos permitted encryption types", WinGPName: "Network security: Configure encryption types allowed for Kerberos", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Allowed enctypes (RC4, AES128, AES256). Linux: krb5.conf default_tgs_enctypes / default_tkt_enctypes / permitted_enctypes.", LinuxImpl: "krb5.conf permitted_enctypes"},
	{ID: "sec.opt.lm-auth-level", Name: "LAN Manager authentication level", WinGPName: "Network security: LAN Manager authentication level", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Controls NTLM/LM behaviour. Recommended: NTLMv2 only. Linux: smb.conf 'client ntlmv2 auth = yes' and 'ntlm auth = no' on any smbd.", LinuxImpl: "smb.conf ntlm auth / client ntlmv2 auth"},
	{ID: "sec.opt.ldap-signing", Name: "LDAP client signing requirements", WinGPName: "Network security: LDAP client signing requirements", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Require signed LDAP binds. Linux: /etc/openldap/ldap.conf SASL_SECPROPS minssf=128 and sssd ldap_sasl_mech=GSSAPI.", LinuxImpl: "ldap.conf SASL_SECPROPS / sssd ldap_sasl_mech"},
	{ID: "sec.opt.shutdown-no-logon", Name: "Allow shutdown without login", WinGPName: "Shutdown: Allow system to be shut down without having to log on", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Show shutdown/reboot buttons on the greeter without requiring a prior login. Linux: gdm/lightdm 'disable-restart-buttons' + polkit login1 rule for the 'no session' subject.", LinuxImpl: "gdm/lightdm greeter + polkit login1"},
	{ID: "sec.opt.clear-swap", Name: "Encrypt or wipe swap on shutdown", WinGPName: "Shutdown: Clear virtual memory pagefile", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Prevent secrets leaking via swap. On Linux the strong recommendation is encrypted swap (/etc/crypttab with random key per boot) rather than a shred-on-shutdown hook.", LinuxImpl: "cryptswap / /etc/crypttab"},
	{ID: "sec.opt.fips", Name: "FIPS mode", WinGPName: "System cryptography: Use FIPS compliant algorithms", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Restrict kernel and userland crypto to FIPS 140-validated algorithms. Linux: fips-mode-setup --enable (RHEL/OL/Alma) or update-crypto-policies --set FIPS.", LinuxImpl: "fips-mode-setup / update-crypto-policies"},
	{ID: "sec.opt.uac-admin-approval", Name: "Require password for privilege elevation (admin accounts)", WinGPName: "User Account Control: Admin Approval Mode for the Built-in Administrator account", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Force admins to re-enter their password on sudo / polkit elevation. Linux: remove NOPASSWD in sudoers and set polkit admin rules to auth_admin.", LinuxImpl: "sudoers + polkit auth_admin"},
	{ID: "sec.opt.uac-standard-prompt", Name: "Elevation prompt for standard users", WinGPName: "User Account Control: Behavior of the elevation prompt for standard users", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "How standard users are prompted when an action needs elevation: prompt / deny. Linux: polkit rules deciding allow_any / auth_admin / no.", LinuxImpl: "polkit rules"},
	{ID: "sec.opt.exec-signed-only", Name: "Only allow signed/verified executables", WinGPName: "User Account Control: Only elevate executables that are signed and validated", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Local Policies|Security Options", Category: []string{"Computer Configuration", "Security Settings", "Local Policies", "Security Options"}, Scope: ScopeComputer, Description: "Enforce that only packaged / signed binaries run. Linux: fapolicyd in enforcing mode with RPM/dpkg trust sources, or IMA-appraisal with a verified keyring.", LinuxImpl: "fapolicyd / IMA-appraisal"},

	// ---------------------------------------------------------------
	// Windows Defender Firewall → Firewall Profiles / Rules
	// ---------------------------------------------------------------
	{ID: "fw.profile.domain", Name: "Firewall state — Domain profile", WinGPName: "Firewall state (Domain Profile)", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security|Domain Profile", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall", "Domain Profile"}, Scope: ScopeComputer, Description: "Enabled/disabled state when the machine is in a trusted (directory-joined) network. Linux: firewalld zone 'internal' or nftables table inet pluris_domain with default policy drop.", LinuxImpl: "firewalld zone / nftables"},
	{ID: "fw.profile.private", Name: "Firewall state — Private profile", WinGPName: "Firewall state (Private Profile)", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security|Private Profile", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall", "Private Profile"}, Scope: ScopeComputer, Description: "Firewall state on known but untrusted networks. Linux: firewalld zone 'home' / nftables chain.", LinuxImpl: "firewalld zone home"},
	{ID: "fw.profile.public", Name: "Firewall state — Public profile", WinGPName: "Firewall state (Public Profile)", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security|Public Profile", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall", "Public Profile"}, Scope: ScopeComputer, Description: "Firewall state on untrusted networks (cafés, airports). Linux: firewalld zone 'public' — typically default-deny inbound, allow only dhcpv6-client/ssh if needed.", LinuxImpl: "firewalld zone public"},
	{ID: "fw.default.inbound", Name: "Default inbound action", WinGPName: "Inbound connections", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall"}, Scope: ScopeComputer, Description: "Allow / Block / Block all. Linux: nftables chain hook input policy drop/accept; ufw default deny incoming.", LinuxImpl: "nftables input policy / ufw default"},
	{ID: "fw.default.outbound", Name: "Default outbound action", WinGPName: "Outbound connections", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall"}, Scope: ScopeComputer, Description: "Allow / Block. Most endpoints leave this as allow; servers may restrict to specific egress.", LinuxImpl: "nftables output policy / ufw default outgoing"},
	{ID: "fw.log.dropped", Name: "Log dropped packets", WinGPName: "Log dropped packets", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall"}, Scope: ScopeComputer, Description: "Write dropped packets to a log. Linux: nftables rule 'log prefix \"pluris-drop\" level info' with ratelimit, shipped via rsyslog/ulogd.", LinuxImpl: "nftables log / ulogd2"},
	{ID: "fw.log.accepted", Name: "Log accepted connections", WinGPName: "Log successful connections", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall"}, Scope: ScopeComputer, Description: "Log accepted new flows. High volume; usually only needed during policy tuning.", LinuxImpl: "nftables log on accept"},
	{ID: "fw.log.path", Name: "Firewall log file path", WinGPName: "Name (log file path)", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall"}, Scope: ScopeComputer, Description: "Where the firewall log is written. Linux: rsyslog rule routing kern.warning with msg containing the prefix to /var/log/pluris-fw.log.", LinuxImpl: "rsyslog rule"},
	{ID: "fw.log.size", Name: "Firewall log size limit", WinGPName: "Size limit (KB)", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall"}, Scope: ScopeComputer, Description: "Rotation size for the firewall log. Linux: logrotate stanza for the log file.", LinuxImpl: "logrotate"},
	{ID: "fw.rules.inbound", Name: "Inbound rules", WinGPName: "Inbound Rules", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security|Inbound Rules", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall", "Inbound Rules"}, Scope: ScopeComputer, Description: "Per-port / per-service inbound allow or block rules. Edited as a list, each rule with protocol, port, source, action, profile.", LinuxImpl: "nftables rules / firewalld services"},
	{ID: "fw.rules.outbound", Name: "Outbound rules", WinGPName: "Outbound Rules", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security|Outbound Rules", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall", "Outbound Rules"}, Scope: ScopeComputer, Description: "Restrict outbound traffic by destination, port, protocol.", LinuxImpl: "nftables rules"},
	{ID: "fw.ipsec.rules", Name: "IPsec / Connection security rules", WinGPName: "Connection Security Rules", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Windows Defender Firewall with Advanced Security|Connection Security Rules", Category: []string{"Computer Configuration", "Security Settings", "Windows Defender Firewall", "Connection Security Rules"}, Scope: ScopeComputer, Description: "Require IPsec for flows between specific endpoints. Linux: strongSwan swanctl.conf or libreswan ipsec.conf.", LinuxImpl: "strongSwan / libreswan"},

	// ---------------------------------------------------------------
	// Public Key Policies
	// ---------------------------------------------------------------
	{ID: "pki.ca.trusted", Name: "Trusted Root Certification Authorities", WinGPName: "Trusted Root Certification Authorities", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Public Key Policies", Category: []string{"Computer Configuration", "Security Settings", "Public Key Policies"}, Scope: ScopeComputer, Description: "Root CAs the machine trusts. Linux: drop PEMs into /usr/local/share/ca-certificates/ (Debian) or /etc/pki/ca-trust/source/anchors/ (RHEL) and run update-ca-certificates / update-ca-trust.", LinuxImpl: "update-ca-certificates / update-ca-trust"},
	{ID: "pki.ca.intermediate", Name: "Intermediate Certification Authorities", WinGPName: "Intermediate Certification Authorities", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Public Key Policies", Category: []string{"Computer Configuration", "Security Settings", "Public Key Policies"}, Scope: ScopeComputer, Description: "Intermediate CAs to pre-seed in the system trust store. Same mechanism as root CAs.", LinuxImpl: "update-ca-trust / update-ca-certificates"},
	{ID: "pki.autoenroll", Name: "Automatic certificate enrolment", WinGPName: "Certificate Services Client - Auto-Enrollment", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Public Key Policies", Category: []string{"Computer Configuration", "Security Settings", "Public Key Policies"}, Scope: ScopeComputer, Description: "Auto-request and renew machine certificates. Linux: certmonger against FreeIPA/Dogtag, or acme.sh/certbot for ACME-issued certs.", LinuxImpl: "certmonger / certbot"},
	{ID: "pki.efs", Name: "Filesystem encryption (EFS equivalent)", WinGPName: "Encrypting File System", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Public Key Policies", Category: []string{"Computer Configuration", "Security Settings", "Public Key Policies"}, Scope: ScopeComputer, Description: "Per-user encrypted home/data directories. Linux choices: fscrypt (native, built into ext4/f2fs), eCryptfs (legacy), or full-disk LUKS as an alternative.", LinuxImpl: "fscrypt / eCryptfs / LUKS"},

	// ---------------------------------------------------------------
	// Application Control (SRP / AppLocker equivalent)
	// ---------------------------------------------------------------
	{ID: "appctl.exec.allowlist", Name: "Executable allow-list rules", WinGPName: "AppLocker: Executable Rules", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Application Control Policies|AppLocker|Executable Rules", Category: []string{"Computer Configuration", "Security Settings", "Application Control", "Executable Rules"}, Scope: ScopeComputer, Description: "Which binaries may run. Linux options: fapolicyd (path + hash + package source), SELinux execmod, AppArmor profile.", LinuxImpl: "fapolicyd / SELinux / AppArmor"},
	{ID: "appctl.script.allowlist", Name: "Script allow-list rules", WinGPName: "AppLocker: Script Rules", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Application Control Policies|AppLocker|Script Rules", Category: []string{"Computer Configuration", "Security Settings", "Application Control", "Script Rules"}, Scope: ScopeComputer, Description: "Constrain which interpreted scripts may be executed. Linux: fapolicyd with interpreter trust (bash, python, perl, nodejs) + restrictive $PATH for interactive shells.", LinuxImpl: "fapolicyd interpreter trust"},
	{ID: "appctl.installer.allowlist", Name: "Installer / package allow-list", WinGPName: "AppLocker: Windows Installer Rules", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Application Control Policies|AppLocker|Windows Installer Rules", Category: []string{"Computer Configuration", "Security Settings", "Application Control", "Installer Rules"}, Scope: ScopeComputer, Description: "Restrict which package operations are allowed. Linux: apt/dnf hooks + polkit rules on package-manager D-Bus interfaces.", LinuxImpl: "apt/dnf hooks + polkit"},
	{ID: "appctl.packaged.allowlist", Name: "Packaged-app (Flatpak/Snap) rules", WinGPName: "AppLocker: Packaged app Rules", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Application Control Policies|AppLocker|Packaged app Rules", Category: []string{"Computer Configuration", "Security Settings", "Application Control", "Packaged App Rules"}, Scope: ScopeComputer, Description: "Which Flatpak IDs and Snap names are permitted. Linux: flatpak override + /etc/flatpak/remotes.d; snap refresh-control and snap connections.", LinuxImpl: "flatpak override / snap"},
	{ID: "appctl.lib.allowlist", Name: "Library (shared-object) rules", WinGPName: "AppLocker: DLL Rules", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Application Control Policies|AppLocker|DLL Rules", Category: []string{"Computer Configuration", "Security Settings", "Application Control", "Library Rules"}, Scope: ScopeComputer, Description: "Control which shared libraries may be loaded. Linux: fapolicyd in library-integrity mode; alternatively IMA-appraisal on .so files.", LinuxImpl: "fapolicyd lib mode / IMA"},
	{ID: "appctl.default-rule", Name: "Default application control action", WinGPName: "Default Rule", WinGPPath: "Computer Configuration|Policies|Windows Settings|Security Settings|Application Control Policies|AppLocker", Category: []string{"Computer Configuration", "Security Settings", "Application Control"}, Scope: ScopeComputer, Description: "What happens to executables that don't match any allow/deny rule. Linux: fapolicyd 'permissive' (log only) vs 'enforcing'.", LinuxImpl: "fapolicyd.conf permissive="},

	// ---------------------------------------------------------------
	// Scripts (Startup / Shutdown) — Computer side
	// ---------------------------------------------------------------
	{ID: "scripts.startup", Name: "Startup scripts", WinGPName: "Startup", WinGPPath: "Computer Configuration|Policies|Windows Settings|Scripts (Startup/Shutdown)", Category: []string{"Computer Configuration", "Scripts (Startup/Shutdown)"}, Scope: ScopeComputer, Description: "Scripts run as root during system boot, before any user session. Linux: systemd unit with WantedBy=multi-user.target or a drop-in to pluris-startup.target.", LinuxImpl: "systemd unit"},
	{ID: "scripts.shutdown", Name: "Shutdown scripts", WinGPName: "Shutdown", WinGPPath: "Computer Configuration|Policies|Windows Settings|Scripts (Startup/Shutdown)", Category: []string{"Computer Configuration", "Scripts (Startup/Shutdown)"}, Scope: ScopeComputer, Description: "Scripts run as root during system shutdown. Linux: systemd unit with ExecStop=, DefaultDependencies=no, Before=shutdown.target.", LinuxImpl: "systemd unit ExecStop"},
	{ID: "scripts.policy-refresh", Name: "Script run on policy refresh", WinGPName: "Run these programs at group-policy refresh", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Group Policy", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Group Policy"}, Scope: ScopeComputer, Description: "Executed whenever the agent applies an updated policy set. Useful for cache invalidation / restart of affected services.", LinuxImpl: "pluris-agent post-apply hook"},
	{ID: "scripts.max-wait", Name: "Maximum wait time for startup scripts (seconds)", WinGPName: "Maximum wait time for Group Policy scripts", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Scripts", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Scripts"}, Scope: ScopeComputer, Description: "Timeout after which a boot script is killed and boot continues. Linux: systemd TimeoutStartSec= on the unit.", LinuxImpl: "systemd TimeoutStartSec"},

	// ---------------------------------------------------------------
	// Administrative Templates → System
	// ---------------------------------------------------------------
	{ID: "adm.sys.power.plan", Name: "Active power plan", WinGPName: "Select an active power plan", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Power Management", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Power Management"}, Scope: ScopeComputer, Description: "Selected power profile (balanced / performance / power-saver). Linux: tlp / power-profiles-daemon 'powerprofilesctl set'.", LinuxImpl: "tlp / power-profiles-daemon"},
	{ID: "adm.sys.power.display-sleep", Name: "Display sleep timeout (seconds)", WinGPName: "Specify the display's sleep timeout", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Power Management|Video and Display Settings", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Power Management"}, Scope: ScopeComputer, Description: "Idle time before the display turns off. Linux: gsettings org.gnome.settings-daemon.plugins.power (system-wide via dconf lock).", LinuxImpl: "dconf / xset dpms"},
	{ID: "adm.sys.power.hibernate", Name: "Hibernate timeout (seconds)", WinGPName: "Specify the system hibernate timeout", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Power Management|Sleep Settings", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Power Management"}, Scope: ScopeComputer, Description: "Idle time before hibernate. Linux: systemd-logind HandleLidSwitch / IdleAction + IdleActionSec.", LinuxImpl: "systemd-logind.conf"},
	{ID: "adm.sys.power.hybrid-sleep", Name: "Disable hybrid sleep", WinGPName: "Turn off hybrid sleep", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Power Management|Sleep Settings", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Power Management"}, Scope: ScopeComputer, Description: "Whether to use suspend-then-hibernate. Linux: systemctl mask systemd-suspend-then-hibernate.service.", LinuxImpl: "systemctl mask"},
	{ID: "adm.sys.remote-assistance", Name: "Remote assistance", WinGPName: "Configure Offer Remote Assistance", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Remote Assistance", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Remote Assistance"}, Scope: ScopeComputer, Description: "Whether help-desk operators can take remote screen-share sessions. Linux: vino-server / gnome-remote-desktop / rustdesk-server policy.", LinuxImpl: "gnome-remote-desktop / rustdesk"},
	{ID: "adm.sys.removable-storage", Name: "Block all removable storage", WinGPName: "All Removable Storage classes: Deny all access", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Removable Storage Access", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Removable Storage Access"}, Scope: ScopeComputer, Description: "Deny mounting of USB drives, SD cards, etc. Linux: USBGuard (policy-driven device allow-list) + udev rules; udisks2 polkit rule to deny mount for 'no-active-session' or non-admin.", LinuxImpl: "USBGuard + udev + udisks2 polkit"},
	{ID: "adm.sys.system-restore", Name: "Disable filesystem snapshotting", WinGPName: "Turn off System Restore", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|System Restore", Category: []string{"Computer Configuration", "Administrative Templates", "System", "System Restore"}, Scope: ScopeComputer, Description: "Whether users may create/restore filesystem snapshots. Linux: snapper / timeshift service state and polkit rule.", LinuxImpl: "snapper / timeshift"},
	{ID: "adm.sys.time.ntp", Name: "NTP server configuration", WinGPName: "Configure Windows NTP Client", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Windows Time Service|Time Providers", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Time Service"}, Scope: ScopeComputer, Description: "NTP/chrony server list, polling interval, iburst. Linux: chrony.conf (pool / server / minpoll / maxpoll) or systemd-timesyncd.conf.", LinuxImpl: "chrony.conf / timesyncd.conf"},
	{ID: "adm.sys.tpm", Name: "TPM services", WinGPName: "Trusted Platform Module Services", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Trusted Platform Module Services", Category: []string{"Computer Configuration", "Administrative Templates", "System", "TPM"}, Scope: ScopeComputer, Description: "Whether the TPM is exposed to userland and owned. Linux: tpm2-abrmd + /dev/tpmrm0 permissions; owner hierarchy password via tpm2_changeauth.", LinuxImpl: "tpm2-abrmd / tpm2-tools"},
	{ID: "adm.sys.logon.wait-network", Name: "Wait for network at boot before login", WinGPName: "Always wait for the network at computer startup and logon", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Logon", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Logon"}, Scope: ScopeComputer, Description: "Force the login prompt to wait for network availability (so directory auth can succeed on first login). Linux: systemd-networkd-wait-online / NetworkManager-wait-online enabled; gdm start after network-online.target.", LinuxImpl: "systemd-networkd-wait-online"},
	{ID: "adm.sys.optional-components", Name: "Source for optional-component install", WinGPName: "Specify settings for optional component installation", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System", Category: []string{"Computer Configuration", "Administrative Templates", "System"}, Scope: ScopeComputer, Description: "Package source for on-demand feature installs. Linux: apt/dnf repo config + pluris-managed package mirror URL.", LinuxImpl: "apt / dnf repo config"},

	// ---------------------------------------------------------------
	// Administrative Templates → Network
	// ---------------------------------------------------------------
	{ID: "adm.net.dns.search", Name: "DNS suffix search list", WinGPName: "DNS Suffix Search List", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Network|DNS Client", Category: []string{"Computer Configuration", "Administrative Templates", "Network", "DNS Client"}, Scope: ScopeComputer, Description: "Domains to append when resolving unqualified names. Linux: systemd-resolved Domains= in [Resolve] or per-link DNSConfiguration; NetworkManager dns-search.", LinuxImpl: "systemd-resolved / NetworkManager"},
	{ID: "adm.net.dns.register", Name: "Register connection DNS name with directory", WinGPName: "Register DNS records with connection-specific DNS suffix", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Network|DNS Client", Category: []string{"Computer Configuration", "Administrative Templates", "Network", "DNS Client"}, Scope: ScopeComputer, Description: "Whether the machine sends dynamic DNS updates. Linux: sssd+adcli dyndns_update=true (AD-joined) or nsupdate script.", LinuxImpl: "sssd ad_dyndns / nsupdate"},
	{ID: "adm.net.offline-files", Name: "Offline files (CIFS caching)", WinGPName: "Allow or disallow use of the Offline Files feature", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Network|Offline Files", Category: []string{"Computer Configuration", "Administrative Templates", "Network", "Offline Files"}, Scope: ScopeComputer, Description: "Whether CIFS/NFS shares are cached for offline use. Linux: autofs + fscache (cachefilesd) for CIFS; cachefilesd for NFS.", LinuxImpl: "cachefilesd / autofs"},
	{ID: "adm.net.net-bridge", Name: "Prohibit network bridging", WinGPName: "Prohibit installation and configuration of Network Bridge", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Network|Network Connections", Category: []string{"Computer Configuration", "Administrative Templates", "Network", "Network Connections"}, Scope: ScopeComputer, Description: "Block the creation of Ethernet bridges on client machines (security baseline). Linux: mask systemd-networkd Bridge= units and disallow nmcli connection add type bridge via polkit.", LinuxImpl: "polkit NetworkManager + kernel module blacklist"},
	{ID: "adm.net.ssl-ciphers", Name: "TLS cipher suite order (system-wide)", WinGPName: "SSL Cipher Suite Order", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Network|SSL Configuration Settings", Category: []string{"Computer Configuration", "Administrative Templates", "Network", "SSL Configuration"}, Scope: ScopeComputer, Description: "System-wide preferred TLS ciphers. Linux: update-crypto-policies (DEFAULT, LEGACY, FIPS, FUTURE) or a custom policy under /etc/crypto-policies/back-ends.", LinuxImpl: "update-crypto-policies"},
	{ID: "adm.net.qos", Name: "QoS packet scheduler", WinGPName: "QoS Packet Scheduler", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Network|QoS Packet Scheduler", Category: []string{"Computer Configuration", "Administrative Templates", "Network", "QoS"}, Scope: ScopeComputer, Description: "Reserve bandwidth for classes of traffic. Linux: tc qdisc (fq_codel / htb) configured via /etc/tc-rules or systemd-networkd QoS.", LinuxImpl: "tc qdisc"},
	{ID: "adm.net.unc-hardening", Name: "Hardened UNC / SMB paths", WinGPName: "Hardened UNC Paths", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Network|Network Provider", Category: []string{"Computer Configuration", "Administrative Templates", "Network", "Network Provider"}, Scope: ScopeComputer, Description: "Require signing/sealing when talking to specific SMB shares. Linux: CIFS mount options seal, sign, krb5, vers=3.0+.", LinuxImpl: "cifs mount options"},
	{ID: "adm.net.proxy", Name: "System-wide HTTP(S) proxy", WinGPName: "Proxy Settings", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Network", Category: []string{"Computer Configuration", "Administrative Templates", "Network"}, Scope: ScopeComputer, Description: "Outbound proxy for system services and package managers. Linux: /etc/environment (http_proxy/https_proxy), apt.conf Acquire::http::Proxy, dnf.conf proxy=.", LinuxImpl: "/etc/environment + apt/dnf proxy"},

	// ---------------------------------------------------------------
	// Administrative Templates → Windows Components (Linux equivalents)
	// ---------------------------------------------------------------
	{ID: "adm.win.bitlocker", Name: "Full-disk encryption policy", WinGPName: "BitLocker Drive Encryption", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|BitLocker Drive Encryption", Category: []string{"Computer Configuration", "Administrative Templates", "Disk Encryption"}, Scope: ScopeComputer, Description: "Whether the system disk must be encrypted, and key-escrow target. Linux: LUKS2 with cryptsetup, key escrow to clevis+tang or TPM2 NV.", LinuxImpl: "LUKS2 + clevis/tang"},
	{ID: "adm.win.wu.auto", Name: "Automatic updates configuration", WinGPName: "Configure Automatic Updates", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|Windows Update", Category: []string{"Computer Configuration", "Administrative Templates", "Updates"}, Scope: ScopeComputer, Description: "Whether security updates auto-install, download-only, notify-only, disabled. Linux: unattended-upgrades (Debian/Ubuntu), dnf-automatic (RHEL), or pluris update-cycle attachment.", LinuxImpl: "unattended-upgrades / dnf-automatic"},
	{ID: "adm.win.wu.mirror", Name: "Internal update mirror URL", WinGPName: "Specify intranet Microsoft update service location", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|Windows Update", Category: []string{"Computer Configuration", "Administrative Templates", "Updates"}, Scope: ScopeComputer, Description: "Point endpoints at an on-prem package mirror. Linux: apt sources.list.d / dnf repo config / flatpak remote-add.", LinuxImpl: "apt / dnf / flatpak"},
	{ID: "adm.win.wu.no-restart", Name: "No auto-restart while users logged on", WinGPName: "No auto-restart with logged on users for scheduled automatic updates installations", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|Windows Update", Category: []string{"Computer Configuration", "Administrative Templates", "Updates"}, Scope: ScopeComputer, Description: "Defer reboot until no one is logged in. Linux: needrestart -r a only when no active session, or pluris update-cycle 'reboot-window' setting.", LinuxImpl: "needrestart / pluris cycle"},
	{ID: "adm.win.defender", Name: "Antivirus / malware scanner policy", WinGPName: "Microsoft Defender Antivirus", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|Microsoft Defender Antivirus", Category: []string{"Computer Configuration", "Administrative Templates", "Endpoint Protection"}, Scope: ScopeComputer, Description: "AV enabled, signature update schedule, scheduled scan. Linux: ClamAV daemon + freshclam schedule, or third-party EDR (Sophos, CrowdStrike, SentinelOne).", LinuxImpl: "clamav / EDR agent"},
	{ID: "adm.win.exploit-guard", Name: "Exploit mitigation policy", WinGPName: "Microsoft Defender Exploit Guard", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|Microsoft Defender Exploit Guard", Category: []string{"Computer Configuration", "Administrative Templates", "Endpoint Protection"}, Scope: ScopeComputer, Description: "Attack-surface reduction controls. Linux: apparmor/SELinux profiles in enforcing mode, kernel.unprivileged_userns_clone = 0, kptr_restrict, dmesg_restrict, perf_event_paranoid.", LinuxImpl: "sysctl + AppArmor/SELinux"},
	{ID: "adm.win.time-svc", Name: "Time service (NTP daemon)", WinGPName: "Windows Time Service", WinGPPath: "Computer Configuration|Policies|Administrative Templates|System|Windows Time Service", Category: []string{"Computer Configuration", "Administrative Templates", "System", "Time Service"}, Scope: ScopeComputer, Description: "Preferred time daemon and synchronisation policy. Linux: chrony on workstations with low-drift requirements, systemd-timesyncd elsewhere.", LinuxImpl: "chrony / timesyncd"},
	{ID: "adm.win.edge-policy", Name: "Browser (Chromium/Edge) managed policy", WinGPName: "Microsoft Edge", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Microsoft Edge", Category: []string{"Computer Configuration", "Administrative Templates", "Browser"}, Scope: ScopeComputer, Description: "Managed browser preferences (allowed extensions, homepage, proxy, update channel). Linux: /etc/opt/edge/policies/managed/*.json (Edge), /etc/chromium/policies/managed/*.json, /etc/firefox/policies/policies.json.", LinuxImpl: "/etc/*/policies/managed/*.json"},
	{ID: "adm.win.rdp.sessions", Name: "Remote desktop max sessions", WinGPName: "Limit number of connections", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|Remote Desktop Services|Remote Desktop Session Host|Connections", Category: []string{"Computer Configuration", "Administrative Templates", "Remote Desktop"}, Scope: ScopeComputer, Description: "Concurrent remote sessions allowed. Linux: sshd MaxSessions / MaxStartups; xrdp max_bpp & session limits.", LinuxImpl: "sshd_config / xrdp.ini"},
	{ID: "adm.win.rdp.tls", Name: "Require TLS for RDP / remote-desktop", WinGPName: "Require use of specific security layer for remote (RDP) connections", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|Remote Desktop Services|Remote Desktop Session Host|Security", Category: []string{"Computer Configuration", "Administrative Templates", "Remote Desktop"}, Scope: ScopeComputer, Description: "Force TLS wrapper on remote desktop. Linux: xrdp tls_ciphers / ssl_protocols; for VNC switch to x0vncserver with TLS.", LinuxImpl: "xrdp.ini security_layer=tls"},
	{ID: "adm.win.rdp.idle", Name: "Remote desktop idle timeout (seconds)", WinGPName: "Set time limit for active but idle Remote Desktop Services sessions", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|Remote Desktop Services|Remote Desktop Session Host|Session Time Limits", Category: []string{"Computer Configuration", "Administrative Templates", "Remote Desktop"}, Scope: ScopeComputer, Description: "Idle timeout for remote sessions. Linux: sshd ClientAliveInterval + ClientAliveCountMax; xrdp session_timeout.", LinuxImpl: "sshd ClientAliveInterval / xrdp"},
	{ID: "adm.win.installer.user", Name: "Prohibit user-level installs", WinGPName: "Prohibit User Installs", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|Windows Installer", Category: []string{"Computer Configuration", "Administrative Templates", "Installer"}, Scope: ScopeComputer, Description: "Whether unprivileged users may install software. Linux: polkit rules for apt / flatpak-system-helper / PackageKit.", LinuxImpl: "polkit PackageKit / flatpak"},
	{ID: "adm.win.smartcard.svc", Name: "Smart card service enabled", WinGPName: "Smart Card", WinGPPath: "Computer Configuration|Policies|Administrative Templates|Windows Components|Smart Card", Category: []string{"Computer Configuration", "Administrative Templates", "Smart Card"}, Scope: ScopeComputer, Description: "Whether the smart-card daemon runs. Linux: pcscd.service + pkcs11 module configuration.", LinuxImpl: "pcscd / pam_pkcs11"},
}
