// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: activity_log.sql

package db

import (
	"context"
	"database/sql"
)

const InsertActivity = `-- name: InsertActivity :exec

INSERT INTO activity_log (tenant_id, entity_type, entity_id, event, detail, actor_identity_id)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type InsertActivityParams struct {
	TenantID        int64          `json:"tenant_id"`
	EntityType      string         `json:"entity_type"`
	EntityID        int64          `json:"entity_id"`
	Event           string         `json:"event"`
	Detail          sql.NullString `json:"detail"`
	ActorIdentityID sql.NullInt64  `json:"actor_identity_id"`
}

// Activity log queries - generic per entity event feed backed by the
// activity_log table in db/schema/003_roles_software_logs.sql.
func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, InsertActivity,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.Event,
		arg.Detail,
		arg.ActorIdentityID,
	)
	return err
}

const ListActivityForEntity = `-- name: ListActivityForEntity :many
SELECT id, tenant_id, entity_type, entity_id, event, detail, actor_identity_id, created_at FROM activity_log
WHERE tenant_id = ?1
  AND entity_type = ?2
  AND entity_id = ?3
ORDER BY created_at DESC
LIMIT ?4
`

type ListActivityForEntityParams struct {
	TenantID   int64  `json:"tenant_id"`
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) ListActivityForEntity(ctx context.Context, arg ListActivityForEntityParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, ListActivityForEntity,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityType,
			&i.EntityID,
			&i.Event,
			&i.Detail,
			&i.ActorIdentityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
