// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const ClearAssetOwner = `-- name: ClearAssetOwner :exec
UPDATE assets SET owner_identity_id = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?1
`

func (q *Queries) ClearAssetOwner(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, ClearAssetOwner, id)
	return err
}

const CountAssetsByEnrollmentState = `-- name: CountAssetsByEnrollmentState :one
SELECT COUNT(*) FROM assets
WHERE tenant_id = ?1 AND enrollment_state = ?2 AND deleted_at IS NULL
`

type CountAssetsByEnrollmentStateParams struct {
	TenantID int64  `json:"tenant_id"`
	State    string `json:"state"`
}

func (q *Queries) CountAssetsByEnrollmentState(ctx context.Context, arg CountAssetsByEnrollmentStateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountAssetsByEnrollmentState, arg.TenantID, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountAssetsBySubtype = `-- name: CountAssetsBySubtype :one
SELECT COUNT(*) FROM assets
WHERE tenant_id = ?1 AND subtype = ?2 AND deleted_at IS NULL
`

type CountAssetsBySubtypeParams struct {
	TenantID int64  `json:"tenant_id"`
	Subtype  string `json:"subtype"`
}

func (q *Queries) CountAssetsBySubtype(ctx context.Context, arg CountAssetsBySubtypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountAssetsBySubtype, arg.TenantID, arg.Subtype)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountAssetsByTenant = `-- name: CountAssetsByTenant :one
SELECT COUNT(*) FROM assets
WHERE tenant_id = ?1 AND deleted_at IS NULL
`

func (q *Queries) CountAssetsByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountAssetsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateAsset = `-- name: CreateAsset :one

INSERT INTO assets (
    uuid, tenant_id, site_id, subtype, subtype_payload,
    enrollment_state, agent_version, labels, human_id
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9
) RETURNING id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by
`

type CreateAssetParams struct {
	Uuid            string         `json:"uuid"`
	TenantID        int64          `json:"tenant_id"`
	SiteID          sql.NullInt64  `json:"site_id"`
	Subtype         string         `json:"subtype"`
	SubtypePayload  string         `json:"subtype_payload"`
	EnrollmentState string         `json:"enrollment_state"`
	AgentVersion    sql.NullString `json:"agent_version"`
	Labels          sql.NullString `json:"labels"`
	HumanID         sql.NullString `json:"human_id"`
}

// Asset CRUD operations
func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, CreateAsset,
		arg.Uuid,
		arg.TenantID,
		arg.SiteID,
		arg.Subtype,
		arg.SubtypePayload,
		arg.EnrollmentState,
		arg.AgentVersion,
		arg.Labels,
		arg.HumanID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TenantID,
		&i.SiteID,
		&i.Subtype,
		&i.SubtypePayload,
		&i.EnrollmentState,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.Labels,
		&i.LifecycleState,
		&i.Location,
		&i.OwnerIdentityID,
		&i.Vendor,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.WarrantyExpiresAt,
		&i.HumanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.ManagedByIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const DeleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = ?1
`

func (q *Queries) DeleteAsset(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAsset, id)
	return err
}

const GetAsset = `-- name: GetAsset :one
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE id = ?1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, id int64) (Asset, error) {
	row := q.db.QueryRowContext(ctx, GetAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TenantID,
		&i.SiteID,
		&i.Subtype,
		&i.SubtypePayload,
		&i.EnrollmentState,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.Labels,
		&i.LifecycleState,
		&i.Location,
		&i.OwnerIdentityID,
		&i.Vendor,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.WarrantyExpiresAt,
		&i.HumanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.ManagedByIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const GetAssetByHumanID = `-- name: GetAssetByHumanID :one
SELECT 
    a.id, a.uuid, a.tenant_id, a.site_id, a.subtype, a.subtype_payload, a.enrollment_state, a.enrolled_at, a.last_seen_at, a.agent_version, a.labels, a.lifecycle_state, a.location, a.owner_identity_id, a.vendor, a.purchase_date, a.purchase_price, a.warranty_expires_at, a.human_id, a.created_at, a.updated_at, a.description, a.managed_by_identity_id, a.deleted_at, a.deleted_by,
    t.slug as tenant_slug,
    s.name as site_name,
    i.display_name as owner_name,
    m.display_name as managed_by_name
FROM assets a
LEFT JOIN tenants t ON a.tenant_id = t.id
LEFT JOIN sites s ON a.site_id = s.id
LEFT JOIN identities i ON a.owner_identity_id = i.id AND i.deleted_at IS NULL
LEFT JOIN identities m ON a.managed_by_identity_id = m.id AND m.deleted_at IS NULL
WHERE a.human_id = ?1 AND a.deleted_at IS NULL
LIMIT 1
`

type GetAssetByHumanIDRow struct {
	ID                  int64           `json:"id"`
	Uuid                string          `json:"uuid"`
	TenantID            int64           `json:"tenant_id"`
	SiteID              sql.NullInt64   `json:"site_id"`
	Subtype             string          `json:"subtype"`
	SubtypePayload      string          `json:"subtype_payload"`
	EnrollmentState     string          `json:"enrollment_state"`
	EnrolledAt          sql.NullTime    `json:"enrolled_at"`
	LastSeenAt          sql.NullTime    `json:"last_seen_at"`
	AgentVersion        sql.NullString  `json:"agent_version"`
	Labels              sql.NullString  `json:"labels"`
	LifecycleState      sql.NullString  `json:"lifecycle_state"`
	Location            sql.NullString  `json:"location"`
	OwnerIdentityID     sql.NullInt64   `json:"owner_identity_id"`
	Vendor              sql.NullString  `json:"vendor"`
	PurchaseDate        sql.NullTime    `json:"purchase_date"`
	PurchasePrice       sql.NullFloat64 `json:"purchase_price"`
	WarrantyExpiresAt   sql.NullTime    `json:"warranty_expires_at"`
	HumanID             sql.NullString  `json:"human_id"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	Description         sql.NullString  `json:"description"`
	ManagedByIdentityID sql.NullInt64   `json:"managed_by_identity_id"`
	DeletedAt           interface{}     `json:"deleted_at"`
	DeletedBy           interface{}     `json:"deleted_by"`
	TenantSlug          sql.NullString  `json:"tenant_slug"`
	SiteName            sql.NullString  `json:"site_name"`
	OwnerName           sql.NullString  `json:"owner_name"`
	ManagedByName       sql.NullString  `json:"managed_by_name"`
}

func (q *Queries) GetAssetByHumanID(ctx context.Context, humanID sql.NullString) (GetAssetByHumanIDRow, error) {
	row := q.db.QueryRowContext(ctx, GetAssetByHumanID, humanID)
	var i GetAssetByHumanIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TenantID,
		&i.SiteID,
		&i.Subtype,
		&i.SubtypePayload,
		&i.EnrollmentState,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.Labels,
		&i.LifecycleState,
		&i.Location,
		&i.OwnerIdentityID,
		&i.Vendor,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.WarrantyExpiresAt,
		&i.HumanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.ManagedByIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.TenantSlug,
		&i.SiteName,
		&i.OwnerName,
		&i.ManagedByName,
	)
	return i, err
}

const GetAssetByUUID = `-- name: GetAssetByUUID :one
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE uuid = ?1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetAssetByUUID(ctx context.Context, uuid string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, GetAssetByUUID, uuid)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TenantID,
		&i.SiteID,
		&i.Subtype,
		&i.SubtypePayload,
		&i.EnrollmentState,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.Labels,
		&i.LifecycleState,
		&i.Location,
		&i.OwnerIdentityID,
		&i.Vendor,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.WarrantyExpiresAt,
		&i.HumanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.ManagedByIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const GetAssetForDeletion = `-- name: GetAssetForDeletion :one
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE tenant_id = ?1 AND (human_id = ?2 OR uuid = ?2)
LIMIT 1
`

type GetAssetForDeletionParams struct {
	TenantID   int64          `json:"tenant_id"`
	Identifier sql.NullString `json:"identifier"`
}

func (q *Queries) GetAssetForDeletion(ctx context.Context, arg GetAssetForDeletionParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, GetAssetForDeletion, arg.TenantID, arg.Identifier)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TenantID,
		&i.SiteID,
		&i.Subtype,
		&i.SubtypePayload,
		&i.EnrollmentState,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.Labels,
		&i.LifecycleState,
		&i.Location,
		&i.OwnerIdentityID,
		&i.Vendor,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.WarrantyExpiresAt,
		&i.HumanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.ManagedByIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const GetAssetStatsByTenant = `-- name: GetAssetStatsByTenant :one
SELECT 
    COUNT(*) as total,
    SUM(CASE WHEN enrollment_state = 'enrolled' THEN 1 ELSE 0 END) as enrolled,
    SUM(CASE WHEN enrollment_state = 'pending' THEN 1 ELSE 0 END) as pending,
    SUM(CASE WHEN enrollment_state = 'approved' THEN 1 ELSE 0 END) as approved,
    SUM(CASE WHEN subtype = 'computer' THEN 1 ELSE 0 END) as computers,
    SUM(CASE WHEN subtype = 'server' THEN 1 ELSE 0 END) as servers,
    SUM(CASE WHEN subtype = 'printer' THEN 1 ELSE 0 END) as printers,
    SUM(CASE WHEN subtype = 'desk' THEN 1 ELSE 0 END) as desks
FROM assets
WHERE tenant_id = ?1 AND deleted_at IS NULL
`

type GetAssetStatsByTenantRow struct {
	Total     int64           `json:"total"`
	Enrolled  sql.NullFloat64 `json:"enrolled"`
	Pending   sql.NullFloat64 `json:"pending"`
	Approved  sql.NullFloat64 `json:"approved"`
	Computers sql.NullFloat64 `json:"computers"`
	Servers   sql.NullFloat64 `json:"servers"`
	Printers  sql.NullFloat64 `json:"printers"`
	Desks     sql.NullFloat64 `json:"desks"`
}

// Summary statistics for dashboard
func (q *Queries) GetAssetStatsByTenant(ctx context.Context, tenantID int64) (GetAssetStatsByTenantRow, error) {
	row := q.db.QueryRowContext(ctx, GetAssetStatsByTenant, tenantID)
	var i GetAssetStatsByTenantRow
	err := row.Scan(
		&i.Total,
		&i.Enrolled,
		&i.Pending,
		&i.Approved,
		&i.Computers,
		&i.Servers,
		&i.Printers,
		&i.Desks,
	)
	return i, err
}

const GetAssetWithRelations = `-- name: GetAssetWithRelations :one
SELECT 
    a.id, a.uuid, a.tenant_id, a.site_id, a.subtype, a.subtype_payload, a.enrollment_state, a.enrolled_at, a.last_seen_at, a.agent_version, a.labels, a.lifecycle_state, a.location, a.owner_identity_id, a.vendor, a.purchase_date, a.purchase_price, a.warranty_expires_at, a.human_id, a.created_at, a.updated_at, a.description, a.managed_by_identity_id, a.deleted_at, a.deleted_by,
    t.slug as tenant_slug,
    t.name as tenant_name,
    s.name as site_name,
    s.slug as site_slug,
    i.display_name as owner_name,
    i.email as owner_email,
    m.display_name as managed_by_name
FROM assets a
LEFT JOIN tenants t ON a.tenant_id = t.id
LEFT JOIN sites s ON a.site_id = s.id
LEFT JOIN identities i ON a.owner_identity_id = i.id AND i.deleted_at IS NULL
LEFT JOIN identities m ON a.managed_by_identity_id = m.id AND m.deleted_at IS NULL
WHERE a.id = ?1 AND a.deleted_at IS NULL
LIMIT 1
`

type GetAssetWithRelationsRow struct {
	ID                  int64           `json:"id"`
	Uuid                string          `json:"uuid"`
	TenantID            int64           `json:"tenant_id"`
	SiteID              sql.NullInt64   `json:"site_id"`
	Subtype             string          `json:"subtype"`
	SubtypePayload      string          `json:"subtype_payload"`
	EnrollmentState     string          `json:"enrollment_state"`
	EnrolledAt          sql.NullTime    `json:"enrolled_at"`
	LastSeenAt          sql.NullTime    `json:"last_seen_at"`
	AgentVersion        sql.NullString  `json:"agent_version"`
	Labels              sql.NullString  `json:"labels"`
	LifecycleState      sql.NullString  `json:"lifecycle_state"`
	Location            sql.NullString  `json:"location"`
	OwnerIdentityID     sql.NullInt64   `json:"owner_identity_id"`
	Vendor              sql.NullString  `json:"vendor"`
	PurchaseDate        sql.NullTime    `json:"purchase_date"`
	PurchasePrice       sql.NullFloat64 `json:"purchase_price"`
	WarrantyExpiresAt   sql.NullTime    `json:"warranty_expires_at"`
	HumanID             sql.NullString  `json:"human_id"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	Description         sql.NullString  `json:"description"`
	ManagedByIdentityID sql.NullInt64   `json:"managed_by_identity_id"`
	DeletedAt           interface{}     `json:"deleted_at"`
	DeletedBy           interface{}     `json:"deleted_by"`
	TenantSlug          sql.NullString  `json:"tenant_slug"`
	TenantName          sql.NullString  `json:"tenant_name"`
	SiteName            sql.NullString  `json:"site_name"`
	SiteSlug            sql.NullString  `json:"site_slug"`
	OwnerName           sql.NullString  `json:"owner_name"`
	OwnerEmail          sql.NullString  `json:"owner_email"`
	ManagedByName       sql.NullString  `json:"managed_by_name"`
}

func (q *Queries) GetAssetWithRelations(ctx context.Context, id int64) (GetAssetWithRelationsRow, error) {
	row := q.db.QueryRowContext(ctx, GetAssetWithRelations, id)
	var i GetAssetWithRelationsRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TenantID,
		&i.SiteID,
		&i.Subtype,
		&i.SubtypePayload,
		&i.EnrollmentState,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.Labels,
		&i.LifecycleState,
		&i.Location,
		&i.OwnerIdentityID,
		&i.Vendor,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.WarrantyExpiresAt,
		&i.HumanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.ManagedByIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.TenantSlug,
		&i.TenantName,
		&i.SiteName,
		&i.SiteSlug,
		&i.OwnerName,
		&i.OwnerEmail,
		&i.ManagedByName,
	)
	return i, err
}

const ListAssets = `-- name: ListAssets :many
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE tenant_id = ?1
  AND deleted_at IS NULL
ORDER BY last_seen_at DESC
LIMIT ?3 OFFSET ?2
`

type ListAssetsParams struct {
	TenantID int64 `json:"tenant_id"`
	Offset   int64 `json:"offset"`
	Limit    int64 `json:"limit"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, ListAssets, arg.TenantID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAssetsByEnrollmentState = `-- name: ListAssetsByEnrollmentState :many
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE tenant_id = ?1 AND enrollment_state = ?2 AND deleted_at IS NULL
ORDER BY last_seen_at DESC
LIMIT ?4 OFFSET ?3
`

type ListAssetsByEnrollmentStateParams struct {
	TenantID int64  `json:"tenant_id"`
	State    string `json:"state"`
	Offset   int64  `json:"offset"`
	Limit    int64  `json:"limit"`
}

// Filter assets by enrollment state
func (q *Queries) ListAssetsByEnrollmentState(ctx context.Context, arg ListAssetsByEnrollmentStateParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, ListAssetsByEnrollmentState,
		arg.TenantID,
		arg.State,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAssetsByLifecycleState = `-- name: ListAssetsByLifecycleState :many
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE tenant_id = ?1 AND lifecycle_state = ?2 AND deleted_at IS NULL
ORDER BY last_seen_at DESC
LIMIT ?4 OFFSET ?3
`

type ListAssetsByLifecycleStateParams struct {
	TenantID int64          `json:"tenant_id"`
	State    sql.NullString `json:"state"`
	Offset   int64          `json:"offset"`
	Limit    int64          `json:"limit"`
}

// Get assets by lifecycle state
func (q *Queries) ListAssetsByLifecycleState(ctx context.Context, arg ListAssetsByLifecycleStateParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, ListAssetsByLifecycleState,
		arg.TenantID,
		arg.State,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAssetsByOwner = `-- name: ListAssetsByOwner :many
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE tenant_id = ?1 AND owner_identity_id = ?2
  AND deleted_at IS NULL
ORDER BY last_seen_at DESC
`

type ListAssetsByOwnerParams struct {
	TenantID int64         `json:"tenant_id"`
	OwnerID  sql.NullInt64 `json:"owner_id"`
}

func (q *Queries) ListAssetsByOwner(ctx context.Context, arg ListAssetsByOwnerParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, ListAssetsByOwner, arg.TenantID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAssetsBySite = `-- name: ListAssetsBySite :many
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE tenant_id = ?1 AND site_id = ?2
  AND deleted_at IS NULL
ORDER BY last_seen_at DESC
LIMIT ?4 OFFSET ?3
`

type ListAssetsBySiteParams struct {
	TenantID int64         `json:"tenant_id"`
	SiteID   sql.NullInt64 `json:"site_id"`
	Offset   int64         `json:"offset"`
	Limit    int64         `json:"limit"`
}

func (q *Queries) ListAssetsBySite(ctx context.Context, arg ListAssetsBySiteParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, ListAssetsBySite,
		arg.TenantID,
		arg.SiteID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAssetsBySubtype = `-- name: ListAssetsBySubtype :many
SELECT 
    a.id, a.uuid, a.tenant_id, a.site_id, a.subtype, a.subtype_payload, a.enrollment_state, a.enrolled_at, a.last_seen_at, a.agent_version, a.labels, a.lifecycle_state, a.location, a.owner_identity_id, a.vendor, a.purchase_date, a.purchase_price, a.warranty_expires_at, a.human_id, a.created_at, a.updated_at, a.description, a.managed_by_identity_id, a.deleted_at, a.deleted_by,
    t.slug as tenant_slug,
    s.name as site_name,
    i.display_name as owner_name,
    m.display_name as managed_by_name
FROM assets a
LEFT JOIN tenants t ON a.tenant_id = t.id
LEFT JOIN sites s ON a.site_id = s.id
LEFT JOIN identities i ON a.owner_identity_id = i.id AND i.deleted_at IS NULL
LEFT JOIN identities m ON a.managed_by_identity_id = m.id AND m.deleted_at IS NULL
WHERE a.tenant_id = ?1 AND a.subtype = ?2 AND a.deleted_at IS NULL
ORDER BY a.last_seen_at DESC
LIMIT ?4 OFFSET ?3
`

type ListAssetsBySubtypeParams struct {
	TenantID int64  `json:"tenant_id"`
	Subtype  string `json:"subtype"`
	Offset   int64  `json:"offset"`
	Limit    int64  `json:"limit"`
}

type ListAssetsBySubtypeRow struct {
	ID                  int64           `json:"id"`
	Uuid                string          `json:"uuid"`
	TenantID            int64           `json:"tenant_id"`
	SiteID              sql.NullInt64   `json:"site_id"`
	Subtype             string          `json:"subtype"`
	SubtypePayload      string          `json:"subtype_payload"`
	EnrollmentState     string          `json:"enrollment_state"`
	EnrolledAt          sql.NullTime    `json:"enrolled_at"`
	LastSeenAt          sql.NullTime    `json:"last_seen_at"`
	AgentVersion        sql.NullString  `json:"agent_version"`
	Labels              sql.NullString  `json:"labels"`
	LifecycleState      sql.NullString  `json:"lifecycle_state"`
	Location            sql.NullString  `json:"location"`
	OwnerIdentityID     sql.NullInt64   `json:"owner_identity_id"`
	Vendor              sql.NullString  `json:"vendor"`
	PurchaseDate        sql.NullTime    `json:"purchase_date"`
	PurchasePrice       sql.NullFloat64 `json:"purchase_price"`
	WarrantyExpiresAt   sql.NullTime    `json:"warranty_expires_at"`
	HumanID             sql.NullString  `json:"human_id"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	Description         sql.NullString  `json:"description"`
	ManagedByIdentityID sql.NullInt64   `json:"managed_by_identity_id"`
	DeletedAt           interface{}     `json:"deleted_at"`
	DeletedBy           interface{}     `json:"deleted_by"`
	TenantSlug          sql.NullString  `json:"tenant_slug"`
	SiteName            sql.NullString  `json:"site_name"`
	OwnerName           sql.NullString  `json:"owner_name"`
	ManagedByName       sql.NullString  `json:"managed_by_name"`
}

func (q *Queries) ListAssetsBySubtype(ctx context.Context, arg ListAssetsBySubtypeParams) ([]ListAssetsBySubtypeRow, error) {
	rows, err := q.db.QueryContext(ctx, ListAssetsBySubtype,
		arg.TenantID,
		arg.Subtype,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsBySubtypeRow{}
	for rows.Next() {
		var i ListAssetsBySubtypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.TenantSlug,
			&i.SiteName,
			&i.OwnerName,
			&i.ManagedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDeletedAssetsBySubtype = `-- name: ListDeletedAssetsBySubtype :many
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE tenant_id = ?1 AND subtype = ?2 AND deleted_at IS NOT NULL
ORDER BY last_seen_at DESC
LIMIT ?4 OFFSET ?3
`

type ListDeletedAssetsBySubtypeParams struct {
	TenantID int64  `json:"tenant_id"`
	Subtype  string `json:"subtype"`
	Offset   int64  `json:"offset"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListDeletedAssetsBySubtype(ctx context.Context, arg ListDeletedAssetsBySubtypeParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, ListDeletedAssetsBySubtype,
		arg.TenantID,
		arg.Subtype,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListExpiredAssets = `-- name: ListExpiredAssets :many
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE deleted_at IS NOT NULL AND deleted_at <= ?1
ORDER BY deleted_at, id
`

func (q *Queries) ListExpiredAssets(ctx context.Context, cutoff interface{}) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, ListExpiredAssets, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListStaleAssets = `-- name: ListStaleAssets :many
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE tenant_id = ?1
  AND deleted_at IS NULL
  AND last_seen_at < ?2
ORDER BY last_seen_at ASC
LIMIT ?3
`

type ListStaleAssetsParams struct {
	TenantID int64        `json:"tenant_id"`
	Since    sql.NullTime `json:"since"`
	Limit    int64        `json:"limit"`
}

// Get assets not seen since a timestamp (stale)
func (q *Queries) ListStaleAssets(ctx context.Context, arg ListStaleAssetsParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, ListStaleAssets, arg.TenantID, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RestoreAsset = `-- name: RestoreAsset :execrows
UPDATE assets
SET deleted_at = NULL, deleted_by = NULL
WHERE id = ?1 AND tenant_id = ?2 AND deleted_at IS NOT NULL
`

type RestoreAssetParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) RestoreAsset(ctx context.Context, arg RestoreAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, RestoreAsset, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const SearchAssets = `-- name: SearchAssets :many
SELECT 
    a.id, a.uuid, a.tenant_id, a.site_id, a.subtype, a.subtype_payload, a.enrollment_state, a.enrolled_at, a.last_seen_at, a.agent_version, a.labels, a.lifecycle_state, a.location, a.owner_identity_id, a.vendor, a.purchase_date, a.purchase_price, a.warranty_expires_at, a.human_id, a.created_at, a.updated_at, a.description, a.managed_by_identity_id, a.deleted_at, a.deleted_by,
    t.slug as tenant_slug,
    s.name as site_name
FROM assets a
LEFT JOIN tenants t ON a.tenant_id = t.id
LEFT JOIN sites s ON a.site_id = s.id
WHERE a.tenant_id = ?1
  AND a.deleted_at IS NULL
  AND (
    a.human_id LIKE '%' || ?2 || '%'
    OR json_extract(a.subtype_payload, '$.hostname') LIKE '%' || ?2 || '%'
    OR json_extract(a.subtype_payload, '$.name') LIKE '%' || ?2 || '%'
    OR a.uuid LIKE '%' || ?2 || '%'
  )
ORDER BY a.last_seen_at DESC
LIMIT ?3
`

type SearchAssetsParams struct {
	TenantID int64          `json:"tenant_id"`
	Search   sql.NullString `json:"search"`
	Limit    int64          `json:"limit"`
}

type SearchAssetsRow struct {
	ID                  int64           `json:"id"`
	Uuid                string          `json:"uuid"`
	TenantID            int64           `json:"tenant_id"`
	SiteID              sql.NullInt64   `json:"site_id"`
	Subtype             string          `json:"subtype"`
	SubtypePayload      string          `json:"subtype_payload"`
	EnrollmentState     string          `json:"enrollment_state"`
	EnrolledAt          sql.NullTime    `json:"enrolled_at"`
	LastSeenAt          sql.NullTime    `json:"last_seen_at"`
	AgentVersion        sql.NullString  `json:"agent_version"`
	Labels              sql.NullString  `json:"labels"`
	LifecycleState      sql.NullString  `json:"lifecycle_state"`
	Location            sql.NullString  `json:"location"`
	OwnerIdentityID     sql.NullInt64   `json:"owner_identity_id"`
	Vendor              sql.NullString  `json:"vendor"`
	PurchaseDate        sql.NullTime    `json:"purchase_date"`
	PurchasePrice       sql.NullFloat64 `json:"purchase_price"`
	WarrantyExpiresAt   sql.NullTime    `json:"warranty_expires_at"`
	HumanID             sql.NullString  `json:"human_id"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	Description         sql.NullString  `json:"description"`
	ManagedByIdentityID sql.NullInt64   `json:"managed_by_identity_id"`
	DeletedAt           interface{}     `json:"deleted_at"`
	DeletedBy           interface{}     `json:"deleted_by"`
	TenantSlug          sql.NullString  `json:"tenant_slug"`
	SiteName            sql.NullString  `json:"site_name"`
}

// Search assets across multiple fields
func (q *Queries) SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]SearchAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, SearchAssets, arg.TenantID, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAssetsRow{}
	for rows.Next() {
		var i SearchAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.TenantSlug,
			&i.SiteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchAssetsByHostname = `-- name: SearchAssetsByHostname :many
SELECT id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by FROM assets
WHERE tenant_id = ?1
  AND deleted_at IS NULL
  AND subtype IN ('computer', 'server')
  AND json_extract(subtype_payload, '$.hostname') LIKE '%' || ?2 || '%'
ORDER BY last_seen_at DESC
LIMIT ?3
`

type SearchAssetsByHostnameParams struct {
	TenantID int64          `json:"tenant_id"`
	Search   sql.NullString `json:"search"`
	Limit    int64          `json:"limit"`
}

// Search assets by JSON payload fields (hostname)
func (q *Queries) SearchAssetsByHostname(ctx context.Context, arg SearchAssetsByHostnameParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, SearchAssetsByHostname, arg.TenantID, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetAssetDescription = `-- name: SetAssetDescription :exec
UPDATE assets SET description = ?1, updated_at = CURRENT_TIMESTAMP WHERE id = ?2
`

type SetAssetDescriptionParams struct {
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) SetAssetDescription(ctx context.Context, arg SetAssetDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, SetAssetDescription, arg.Description, arg.ID)
	return err
}

const SetAssetManagedBy = `-- name: SetAssetManagedBy :exec
UPDATE assets SET managed_by_identity_id = ?1, updated_at = CURRENT_TIMESTAMP WHERE id = ?2
`

type SetAssetManagedByParams struct {
	ManagedBy sql.NullInt64 `json:"managed_by"`
	ID        int64         `json:"id"`
}

func (q *Queries) SetAssetManagedBy(ctx context.Context, arg SetAssetManagedByParams) error {
	_, err := q.db.ExecContext(ctx, SetAssetManagedBy, arg.ManagedBy, arg.ID)
	return err
}

const SetAssetOwner = `-- name: SetAssetOwner :exec
UPDATE assets SET owner_identity_id = ?1, updated_at = CURRENT_TIMESTAMP WHERE id = ?2
`

type SetAssetOwnerParams struct {
	OwnerID sql.NullInt64 `json:"owner_id"`
	ID      int64         `json:"id"`
}

// Narrow, single-column update: unlike UpdateAsset (which requires
// re-supplying site_id/subtype_payload/labels), this only ever touches
// ownership so callers cannot accidentally clobber unrelated fields.
func (q *Queries) SetAssetOwner(ctx context.Context, arg SetAssetOwnerParams) error {
	_, err := q.db.ExecContext(ctx, SetAssetOwner, arg.OwnerID, arg.ID)
	return err
}

const SoftDeleteAsset = `-- name: SoftDeleteAsset :execrows
UPDATE assets
SET deleted_at = CURRENT_TIMESTAMP, deleted_by = ?1
WHERE id = ?2 AND tenant_id = ?3 AND deleted_at IS NULL
`

type SoftDeleteAssetParams struct {
	DeletedBy interface{} `json:"deleted_by"`
	ID        int64       `json:"id"`
	TenantID  int64       `json:"tenant_id"`
}

func (q *Queries) SoftDeleteAsset(ctx context.Context, arg SoftDeleteAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, SoftDeleteAsset, arg.DeletedBy, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET site_id = ?1,
    owner_identity_id = ?2,
    subtype_payload = ?3,
    labels = ?4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?5
RETURNING id, uuid, tenant_id, site_id, subtype, subtype_payload, enrollment_state, enrolled_at, last_seen_at, agent_version, labels, lifecycle_state, location, owner_identity_id, vendor, purchase_date, purchase_price, warranty_expires_at, human_id, created_at, updated_at, description, managed_by_identity_id, deleted_at, deleted_by
`

type UpdateAssetParams struct {
	SiteID         sql.NullInt64  `json:"site_id"`
	OwnerID        sql.NullInt64  `json:"owner_id"`
	SubtypePayload string         `json:"subtype_payload"`
	Labels         sql.NullString `json:"labels"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, UpdateAsset,
		arg.SiteID,
		arg.OwnerID,
		arg.SubtypePayload,
		arg.Labels,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TenantID,
		&i.SiteID,
		&i.Subtype,
		&i.SubtypePayload,
		&i.EnrollmentState,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.Labels,
		&i.LifecycleState,
		&i.Location,
		&i.OwnerIdentityID,
		&i.Vendor,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.WarrantyExpiresAt,
		&i.HumanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.ManagedByIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const UpdateAssetCMDB = `-- name: UpdateAssetCMDB :exec
UPDATE assets
SET lifecycle_state = ?1,
    location = ?2,
    vendor = ?3,
    purchase_date = ?4,
    purchase_price = ?5,
    warranty_expires_at = ?6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?7
`

type UpdateAssetCMDBParams struct {
	LifecycleState    sql.NullString  `json:"lifecycle_state"`
	Location          sql.NullString  `json:"location"`
	Vendor            sql.NullString  `json:"vendor"`
	PurchaseDate      sql.NullTime    `json:"purchase_date"`
	PurchasePrice     sql.NullFloat64 `json:"purchase_price"`
	WarrantyExpiresAt sql.NullTime    `json:"warranty_expires_at"`
	ID                int64           `json:"id"`
}

func (q *Queries) UpdateAssetCMDB(ctx context.Context, arg UpdateAssetCMDBParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAssetCMDB,
		arg.LifecycleState,
		arg.Location,
		arg.Vendor,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.WarrantyExpiresAt,
		arg.ID,
	)
	return err
}

const UpdateAssetEditableColumns = `-- name: UpdateAssetEditableColumns :exec
UPDATE assets
SET description = ?1,
    lifecycle_state = ?2,
    vendor = ?3,
    location = ?4,
    purchase_date = ?5,
    warranty_expires_at = ?6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?7
`

type UpdateAssetEditableColumnsParams struct {
	Description       sql.NullString `json:"description"`
	LifecycleState    sql.NullString `json:"lifecycle_state"`
	Vendor            sql.NullString `json:"vendor"`
	Location          sql.NullString `json:"location"`
	PurchaseDate      sql.NullTime   `json:"purchase_date"`
	WarrantyExpiresAt sql.NullTime   `json:"warranty_expires_at"`
	ID                int64          `json:"id"`
}

// Column-backed keys editable through the field-update API (Task 8
// review Finding 2): the "identity" section's description plus the
// "lifecycle" section's lifecycle_state/vendor/location/purchase_date/
// warranty_expires_at. Every other assets-table column (uuid, tenant_id,
// site_id, owner_identity_id, enrollment_state, ...) is either computed,
// a link resolved through another entity, or agent-controlled, and is
// NOT touched here. Caller (AssetService.UpdateFields) fetches the
// current row first and re-supplies every column (fetched-then-mutated,
// same pattern as IdentityService.UpdateFields), so a request editing
// only one of these columns cannot clobber the others.
func (q *Queries) UpdateAssetEditableColumns(ctx context.Context, arg UpdateAssetEditableColumnsParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAssetEditableColumns,
		arg.Description,
		arg.LifecycleState,
		arg.Vendor,
		arg.Location,
		arg.PurchaseDate,
		arg.WarrantyExpiresAt,
		arg.ID,
	)
	return err
}

const UpdateAssetEnrollmentState = `-- name: UpdateAssetEnrollmentState :exec
UPDATE assets
SET enrollment_state = ?1,
    enrolled_at = CASE WHEN ?1 = 'enrolled' AND enrolled_at IS NULL THEN CURRENT_TIMESTAMP ELSE enrolled_at END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateAssetEnrollmentStateParams struct {
	State string `json:"state"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateAssetEnrollmentState(ctx context.Context, arg UpdateAssetEnrollmentStateParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAssetEnrollmentState, arg.State, arg.ID)
	return err
}

const UpdateAssetLastSeen = `-- name: UpdateAssetLastSeen :exec
UPDATE assets
SET last_seen_at = CURRENT_TIMESTAMP,
    agent_version = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateAssetLastSeenParams struct {
	AgentVersion sql.NullString `json:"agent_version"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateAssetLastSeen(ctx context.Context, arg UpdateAssetLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAssetLastSeen, arg.AgentVersion, arg.ID)
	return err
}

const UpdateAssetOwner = `-- name: UpdateAssetOwner :exec
UPDATE assets
SET owner_identity_id = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateAssetOwnerParams struct {
	OwnerID sql.NullInt64 `json:"owner_id"`
	ID      int64         `json:"id"`
}

// Superseded by SetAssetOwner for new call sites (added in the owner-pairing
// task); kept as-is here to avoid unrelated churn, not because both are needed.
func (q *Queries) UpdateAssetOwner(ctx context.Context, arg UpdateAssetOwnerParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAssetOwner, arg.OwnerID, arg.ID)
	return err
}

const UpdateAssetPayload = `-- name: UpdateAssetPayload :exec
UPDATE assets
SET subtype_payload = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateAssetPayloadParams struct {
	Payload string `json:"payload"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateAssetPayload(ctx context.Context, arg UpdateAssetPayloadParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAssetPayload, arg.Payload, arg.ID)
	return err
}

const UpdateAssetSite = `-- name: UpdateAssetSite :exec
UPDATE assets
SET site_id = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateAssetSiteParams struct {
	SiteID sql.NullInt64 `json:"site_id"`
	ID     int64         `json:"id"`
}

func (q *Queries) UpdateAssetSite(ctx context.Context, arg UpdateAssetSiteParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAssetSite, arg.SiteID, arg.ID)
	return err
}
