// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: asset_links.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CountLinksForAsset = `-- name: CountLinksForAsset :one
SELECT COUNT(*) FROM asset_links 
WHERE from_asset_id = ?1 OR to_asset_id = ?1
`

func (q *Queries) CountLinksForAsset(ctx context.Context, assetID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountLinksForAsset, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateAssetLink = `-- name: CreateAssetLink :one

INSERT INTO asset_links (
    tenant_id,
    from_asset_id,
    to_asset_id,
    relation,
    metadata
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
) RETURNING id, tenant_id, from_asset_id, to_asset_id, relation, metadata, created_at
`

type CreateAssetLinkParams struct {
	TenantID    int64          `json:"tenant_id"`
	FromAssetID int64          `json:"from_asset_id"`
	ToAssetID   int64          `json:"to_asset_id"`
	Relation    string         `json:"relation"`
	Metadata    sql.NullString `json:"metadata"`
}

// Asset link queries
// Asset links define relationships between assets (e.g., desk-to-computer, server-to-server)
func (q *Queries) CreateAssetLink(ctx context.Context, arg CreateAssetLinkParams) (AssetLink, error) {
	row := q.db.QueryRowContext(ctx, CreateAssetLink,
		arg.TenantID,
		arg.FromAssetID,
		arg.ToAssetID,
		arg.Relation,
		arg.Metadata,
	)
	var i AssetLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FromAssetID,
		&i.ToAssetID,
		&i.Relation,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteAssetLink = `-- name: DeleteAssetLink :exec
DELETE FROM asset_links WHERE id = ?1
`

func (q *Queries) DeleteAssetLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAssetLink, id)
	return err
}

const DeleteLinksByRelation = `-- name: DeleteLinksByRelation :exec
DELETE FROM asset_links 
WHERE tenant_id = ?1 AND relation = ?2
`

type DeleteLinksByRelationParams struct {
	TenantID int64  `json:"tenant_id"`
	Relation string `json:"relation"`
}

func (q *Queries) DeleteLinksByRelation(ctx context.Context, arg DeleteLinksByRelationParams) error {
	_, err := q.db.ExecContext(ctx, DeleteLinksByRelation, arg.TenantID, arg.Relation)
	return err
}

const DeleteLinksForAsset = `-- name: DeleteLinksForAsset :exec
DELETE FROM asset_links 
WHERE from_asset_id = ?1 OR to_asset_id = ?1
`

func (q *Queries) DeleteLinksForAsset(ctx context.Context, assetID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteLinksForAsset, assetID)
	return err
}

const GetAssetLink = `-- name: GetAssetLink :one
SELECT id, tenant_id, from_asset_id, to_asset_id, relation, metadata, created_at FROM asset_links WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetAssetLink(ctx context.Context, id int64) (AssetLink, error) {
	row := q.db.QueryRowContext(ctx, GetAssetLink, id)
	var i AssetLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FromAssetID,
		&i.ToAssetID,
		&i.Relation,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const GetAssetLinkByAssets = `-- name: GetAssetLinkByAssets :one
SELECT id, tenant_id, from_asset_id, to_asset_id, relation, metadata, created_at FROM asset_links 
WHERE from_asset_id = ?1 
  AND to_asset_id = ?2 
  AND relation = ?3
LIMIT 1
`

type GetAssetLinkByAssetsParams struct {
	FromAssetID int64  `json:"from_asset_id"`
	ToAssetID   int64  `json:"to_asset_id"`
	Relation    string `json:"relation"`
}

func (q *Queries) GetAssetLinkByAssets(ctx context.Context, arg GetAssetLinkByAssetsParams) (AssetLink, error) {
	row := q.db.QueryRowContext(ctx, GetAssetLinkByAssets, arg.FromAssetID, arg.ToAssetID, arg.Relation)
	var i AssetLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FromAssetID,
		&i.ToAssetID,
		&i.Relation,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const ListAllLinksForAsset = `-- name: ListAllLinksForAsset :many
SELECT 
    l.id, l.tenant_id, l.from_asset_id, l.to_asset_id, l.relation, l.metadata, l.created_at,
    CASE WHEN l.from_asset_id = ?1 THEN 'outgoing' ELSE 'incoming' END as direction,
    CASE WHEN l.from_asset_id = ?1 THEN ta.human_id ELSE fa.human_id END as related_asset_id,
    CASE WHEN l.from_asset_id = ?1 THEN ta.subtype ELSE fa.subtype END as related_asset_subtype
FROM asset_links l
JOIN assets fa ON fa.id = l.from_asset_id
JOIN assets ta ON ta.id = l.to_asset_id
WHERE l.from_asset_id = ?1 OR l.to_asset_id = ?1
ORDER BY l.relation
`

type ListAllLinksForAssetRow struct {
	ID                  int64          `json:"id"`
	TenantID            int64          `json:"tenant_id"`
	FromAssetID         int64          `json:"from_asset_id"`
	ToAssetID           int64          `json:"to_asset_id"`
	Relation            string         `json:"relation"`
	Metadata            sql.NullString `json:"metadata"`
	CreatedAt           time.Time      `json:"created_at"`
	Direction           string         `json:"direction"`
	RelatedAssetID      interface{}    `json:"related_asset_id"`
	RelatedAssetSubtype interface{}    `json:"related_asset_subtype"`
}

func (q *Queries) ListAllLinksForAsset(ctx context.Context, assetID int64) ([]ListAllLinksForAssetRow, error) {
	rows, err := q.db.QueryContext(ctx, ListAllLinksForAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllLinksForAssetRow{}
	for rows.Next() {
		var i ListAllLinksForAssetRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FromAssetID,
			&i.ToAssetID,
			&i.Relation,
			&i.Metadata,
			&i.CreatedAt,
			&i.Direction,
			&i.RelatedAssetID,
			&i.RelatedAssetSubtype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListLinksByRelation = `-- name: ListLinksByRelation :many
SELECT 
    l.id, l.tenant_id, l.from_asset_id, l.to_asset_id, l.relation, l.metadata, l.created_at,
    fa.human_id as from_human_id,
    ta.human_id as to_human_id
FROM asset_links l
JOIN assets fa ON fa.id = l.from_asset_id
JOIN assets ta ON ta.id = l.to_asset_id
WHERE l.tenant_id = ?1 AND l.relation = ?2
ORDER BY fa.human_id, ta.human_id
`

type ListLinksByRelationParams struct {
	TenantID int64  `json:"tenant_id"`
	Relation string `json:"relation"`
}

type ListLinksByRelationRow struct {
	ID          int64          `json:"id"`
	TenantID    int64          `json:"tenant_id"`
	FromAssetID int64          `json:"from_asset_id"`
	ToAssetID   int64          `json:"to_asset_id"`
	Relation    string         `json:"relation"`
	Metadata    sql.NullString `json:"metadata"`
	CreatedAt   time.Time      `json:"created_at"`
	FromHumanID sql.NullString `json:"from_human_id"`
	ToHumanID   sql.NullString `json:"to_human_id"`
}

func (q *Queries) ListLinksByRelation(ctx context.Context, arg ListLinksByRelationParams) ([]ListLinksByRelationRow, error) {
	rows, err := q.db.QueryContext(ctx, ListLinksByRelation, arg.TenantID, arg.Relation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksByRelationRow{}
	for rows.Next() {
		var i ListLinksByRelationRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FromAssetID,
			&i.ToAssetID,
			&i.Relation,
			&i.Metadata,
			&i.CreatedAt,
			&i.FromHumanID,
			&i.ToHumanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListLinksFromAsset = `-- name: ListLinksFromAsset :many
SELECT 
    l.id, l.tenant_id, l.from_asset_id, l.to_asset_id, l.relation, l.metadata, l.created_at,
    a.human_id as to_asset_human_id,
    a.subtype as to_asset_subtype,
    json_extract(a.subtype_payload, '$.hostname') as to_asset_hostname,
    json_extract(a.subtype_payload, '$.name') as to_asset_name
FROM asset_links l
JOIN assets a ON a.id = l.to_asset_id
WHERE l.from_asset_id = ?1
ORDER BY l.relation, a.human_id
`

type ListLinksFromAssetRow struct {
	ID              int64          `json:"id"`
	TenantID        int64          `json:"tenant_id"`
	FromAssetID     int64          `json:"from_asset_id"`
	ToAssetID       int64          `json:"to_asset_id"`
	Relation        string         `json:"relation"`
	Metadata        sql.NullString `json:"metadata"`
	CreatedAt       time.Time      `json:"created_at"`
	ToAssetHumanID  sql.NullString `json:"to_asset_human_id"`
	ToAssetSubtype  string         `json:"to_asset_subtype"`
	ToAssetHostname interface{}    `json:"to_asset_hostname"`
	ToAssetName     interface{}    `json:"to_asset_name"`
}

func (q *Queries) ListLinksFromAsset(ctx context.Context, fromAssetID int64) ([]ListLinksFromAssetRow, error) {
	rows, err := q.db.QueryContext(ctx, ListLinksFromAsset, fromAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksFromAssetRow{}
	for rows.Next() {
		var i ListLinksFromAssetRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FromAssetID,
			&i.ToAssetID,
			&i.Relation,
			&i.Metadata,
			&i.CreatedAt,
			&i.ToAssetHumanID,
			&i.ToAssetSubtype,
			&i.ToAssetHostname,
			&i.ToAssetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListLinksToAsset = `-- name: ListLinksToAsset :many
SELECT 
    l.id, l.tenant_id, l.from_asset_id, l.to_asset_id, l.relation, l.metadata, l.created_at,
    a.human_id as from_asset_human_id,
    a.subtype as from_asset_subtype,
    json_extract(a.subtype_payload, '$.hostname') as from_asset_hostname,
    json_extract(a.subtype_payload, '$.name') as from_asset_name
FROM asset_links l
JOIN assets a ON a.id = l.from_asset_id
WHERE l.to_asset_id = ?1
ORDER BY l.relation, a.human_id
`

type ListLinksToAssetRow struct {
	ID                int64          `json:"id"`
	TenantID          int64          `json:"tenant_id"`
	FromAssetID       int64          `json:"from_asset_id"`
	ToAssetID         int64          `json:"to_asset_id"`
	Relation          string         `json:"relation"`
	Metadata          sql.NullString `json:"metadata"`
	CreatedAt         time.Time      `json:"created_at"`
	FromAssetHumanID  sql.NullString `json:"from_asset_human_id"`
	FromAssetSubtype  string         `json:"from_asset_subtype"`
	FromAssetHostname interface{}    `json:"from_asset_hostname"`
	FromAssetName     interface{}    `json:"from_asset_name"`
}

func (q *Queries) ListLinksToAsset(ctx context.Context, toAssetID int64) ([]ListLinksToAssetRow, error) {
	rows, err := q.db.QueryContext(ctx, ListLinksToAsset, toAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksToAssetRow{}
	for rows.Next() {
		var i ListLinksToAssetRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FromAssetID,
			&i.ToAssetID,
			&i.Relation,
			&i.Metadata,
			&i.CreatedAt,
			&i.FromAssetHumanID,
			&i.FromAssetSubtype,
			&i.FromAssetHostname,
			&i.FromAssetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateAssetLink = `-- name: UpdateAssetLink :one
UPDATE asset_links SET
    relation = ?1,
    metadata = ?2
WHERE id = ?3
RETURNING id, tenant_id, from_asset_id, to_asset_id, relation, metadata, created_at
`

type UpdateAssetLinkParams struct {
	Relation string         `json:"relation"`
	Metadata sql.NullString `json:"metadata"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateAssetLink(ctx context.Context, arg UpdateAssetLinkParams) (AssetLink, error) {
	row := q.db.QueryRowContext(ctx, UpdateAssetLink, arg.Relation, arg.Metadata, arg.ID)
	var i AssetLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FromAssetID,
		&i.ToAssetID,
		&i.Relation,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
