// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: configuration_groups.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CountAssignmentsByGroup = `-- name: CountAssignmentsByGroup :one
SELECT COUNT(*) FROM configuration_group_assignments 
WHERE configuration_group_id = ?1
`

func (q *Queries) CountAssignmentsByGroup(ctx context.Context, configurationGroupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountAssignmentsByGroup, configurationGroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountBindingsByModule = `-- name: CountBindingsByModule :one
SELECT COUNT(*) FROM configuration_group_bindings WHERE module_id = ?1
`

// Used by the module service's DeleteModule guard: a module referenced
// by any configuration-group binding may not be deleted (see
// pkg/services/policymodules.go).
func (q *Queries) CountBindingsByModule(ctx context.Context, moduleID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountBindingsByModule, moduleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountConfigurationGroupsByTenant = `-- name: CountConfigurationGroupsByTenant :one
SELECT COUNT(*) FROM configuration_groups WHERE tenant_id = ?1
`

func (q *Queries) CountConfigurationGroupsByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountConfigurationGroupsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateConfigurationGroup = `-- name: CreateConfigurationGroup :one

INSERT INTO configuration_groups (
    tenant_id,
    name,
    description,
    scope,
    disabled
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
) RETURNING id, tenant_id, name, description, scope, disabled, created_at, updated_at
`

type CreateConfigurationGroupParams struct {
	TenantID    int64          `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Scope       string         `json:"scope"`
	Disabled    bool           `json:"disabled"`
}

// Configuration group queries
// Configuration groups bundle policy bindings for assignment
func (q *Queries) CreateConfigurationGroup(ctx context.Context, arg CreateConfigurationGroupParams) (ConfigurationGroup, error) {
	row := q.db.QueryRowContext(ctx, CreateConfigurationGroup,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Scope,
		arg.Disabled,
	)
	var i ConfigurationGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateConfigurationGroupAssignment = `-- name: CreateConfigurationGroupAssignment :one

INSERT INTO configuration_group_assignments (
    configuration_group_id,
    target_type,
    target_id,
    priority,
    enforced
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
) RETURNING id, configuration_group_id, target_type, target_id, priority, enforced, created_at
`

type CreateConfigurationGroupAssignmentParams struct {
	ConfigurationGroupID int64  `json:"configuration_group_id"`
	TargetType           string `json:"target_type"`
	TargetID             int64  `json:"target_id"`
	Priority             int64  `json:"priority"`
	Enforced             bool   `json:"enforced"`
}

// ============================================================================
// Configuration Group Assignments (who gets a group)
// ============================================================================
func (q *Queries) CreateConfigurationGroupAssignment(ctx context.Context, arg CreateConfigurationGroupAssignmentParams) (ConfigurationGroupAssignment, error) {
	row := q.db.QueryRowContext(ctx, CreateConfigurationGroupAssignment,
		arg.ConfigurationGroupID,
		arg.TargetType,
		arg.TargetID,
		arg.Priority,
		arg.Enforced,
	)
	var i ConfigurationGroupAssignment
	err := row.Scan(
		&i.ID,
		&i.ConfigurationGroupID,
		&i.TargetType,
		&i.TargetID,
		&i.Priority,
		&i.Enforced,
		&i.CreatedAt,
	)
	return i, err
}

const CreateConfigurationGroupBinding = `-- name: CreateConfigurationGroupBinding :one

INSERT INTO configuration_group_bindings (
    configuration_group_id,
    policy_urn,
    state,
    parameter_values,
    module_id,
    module_version_pinned,
    disabled
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
) RETURNING id, configuration_group_id, policy_urn, state, parameter_values, module_id, module_version_pinned, disabled, created_at, updated_at
`

type CreateConfigurationGroupBindingParams struct {
	ConfigurationGroupID int64          `json:"configuration_group_id"`
	PolicyUrn            string         `json:"policy_urn"`
	State                string         `json:"state"`
	ParameterValues      sql.NullString `json:"parameter_values"`
	ModuleID             sql.NullInt64  `json:"module_id"`
	ModuleVersionPinned  sql.NullString `json:"module_version_pinned"`
	Disabled             bool           `json:"disabled"`
}

// ============================================================================
// Configuration Group Bindings (which policies are in a group)
// ============================================================================
func (q *Queries) CreateConfigurationGroupBinding(ctx context.Context, arg CreateConfigurationGroupBindingParams) (ConfigurationGroupBinding, error) {
	row := q.db.QueryRowContext(ctx, CreateConfigurationGroupBinding,
		arg.ConfigurationGroupID,
		arg.PolicyUrn,
		arg.State,
		arg.ParameterValues,
		arg.ModuleID,
		arg.ModuleVersionPinned,
		arg.Disabled,
	)
	var i ConfigurationGroupBinding
	err := row.Scan(
		&i.ID,
		&i.ConfigurationGroupID,
		&i.PolicyUrn,
		&i.State,
		&i.ParameterValues,
		&i.ModuleID,
		&i.ModuleVersionPinned,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteAssignmentsByGroup = `-- name: DeleteAssignmentsByGroup :exec
DELETE FROM configuration_group_assignments WHERE configuration_group_id = ?1
`

func (q *Queries) DeleteAssignmentsByGroup(ctx context.Context, configurationGroupID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAssignmentsByGroup, configurationGroupID)
	return err
}

const DeleteAssignmentsByTarget = `-- name: DeleteAssignmentsByTarget :exec
DELETE FROM configuration_group_assignments 
WHERE target_type = ?1 AND target_id = ?2
`

type DeleteAssignmentsByTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
}

func (q *Queries) DeleteAssignmentsByTarget(ctx context.Context, arg DeleteAssignmentsByTargetParams) error {
	_, err := q.db.ExecContext(ctx, DeleteAssignmentsByTarget, arg.TargetType, arg.TargetID)
	return err
}

const DeleteBindingsByGroup = `-- name: DeleteBindingsByGroup :exec
DELETE FROM configuration_group_bindings WHERE configuration_group_id = ?1
`

func (q *Queries) DeleteBindingsByGroup(ctx context.Context, configurationGroupID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteBindingsByGroup, configurationGroupID)
	return err
}

const DeleteConfigurationGroup = `-- name: DeleteConfigurationGroup :exec
DELETE FROM configuration_groups WHERE id = ?1
`

func (q *Queries) DeleteConfigurationGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteConfigurationGroup, id)
	return err
}

const DeleteConfigurationGroupAssignment = `-- name: DeleteConfigurationGroupAssignment :exec
DELETE FROM configuration_group_assignments WHERE id = ?1
`

func (q *Queries) DeleteConfigurationGroupAssignment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteConfigurationGroupAssignment, id)
	return err
}

const DeleteConfigurationGroupBinding = `-- name: DeleteConfigurationGroupBinding :exec
DELETE FROM configuration_group_bindings WHERE id = ?1
`

func (q *Queries) DeleteConfigurationGroupBinding(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteConfigurationGroupBinding, id)
	return err
}

const GetBindingByGroupAndPolicy = `-- name: GetBindingByGroupAndPolicy :one
SELECT id, configuration_group_id, policy_urn, state, parameter_values, module_id, module_version_pinned, disabled, created_at, updated_at FROM configuration_group_bindings 
WHERE configuration_group_id = ?1 AND policy_urn = ?2
LIMIT 1
`

type GetBindingByGroupAndPolicyParams struct {
	ConfigurationGroupID int64  `json:"configuration_group_id"`
	PolicyUrn            string `json:"policy_urn"`
}

func (q *Queries) GetBindingByGroupAndPolicy(ctx context.Context, arg GetBindingByGroupAndPolicyParams) (ConfigurationGroupBinding, error) {
	row := q.db.QueryRowContext(ctx, GetBindingByGroupAndPolicy, arg.ConfigurationGroupID, arg.PolicyUrn)
	var i ConfigurationGroupBinding
	err := row.Scan(
		&i.ID,
		&i.ConfigurationGroupID,
		&i.PolicyUrn,
		&i.State,
		&i.ParameterValues,
		&i.ModuleID,
		&i.ModuleVersionPinned,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetConfigurationGroup = `-- name: GetConfigurationGroup :one
SELECT id, tenant_id, name, description, scope, disabled, created_at, updated_at FROM configuration_groups WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetConfigurationGroup(ctx context.Context, id int64) (ConfigurationGroup, error) {
	row := q.db.QueryRowContext(ctx, GetConfigurationGroup, id)
	var i ConfigurationGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetConfigurationGroupAssignment = `-- name: GetConfigurationGroupAssignment :one
SELECT id, configuration_group_id, target_type, target_id, priority, enforced, created_at FROM configuration_group_assignments WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetConfigurationGroupAssignment(ctx context.Context, id int64) (ConfigurationGroupAssignment, error) {
	row := q.db.QueryRowContext(ctx, GetConfigurationGroupAssignment, id)
	var i ConfigurationGroupAssignment
	err := row.Scan(
		&i.ID,
		&i.ConfigurationGroupID,
		&i.TargetType,
		&i.TargetID,
		&i.Priority,
		&i.Enforced,
		&i.CreatedAt,
	)
	return i, err
}

const GetConfigurationGroupBinding = `-- name: GetConfigurationGroupBinding :one
SELECT id, configuration_group_id, policy_urn, state, parameter_values, module_id, module_version_pinned, disabled, created_at, updated_at FROM configuration_group_bindings WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetConfigurationGroupBinding(ctx context.Context, id int64) (ConfigurationGroupBinding, error) {
	row := q.db.QueryRowContext(ctx, GetConfigurationGroupBinding, id)
	var i ConfigurationGroupBinding
	err := row.Scan(
		&i.ID,
		&i.ConfigurationGroupID,
		&i.PolicyUrn,
		&i.State,
		&i.ParameterValues,
		&i.ModuleID,
		&i.ModuleVersionPinned,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetConfigurationGroupByName = `-- name: GetConfigurationGroupByName :one
SELECT id, tenant_id, name, description, scope, disabled, created_at, updated_at FROM configuration_groups 
WHERE tenant_id = ?1 AND name = ?2 
LIMIT 1
`

type GetConfigurationGroupByNameParams struct {
	TenantID int64  `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) GetConfigurationGroupByName(ctx context.Context, arg GetConfigurationGroupByNameParams) (ConfigurationGroup, error) {
	row := q.db.QueryRowContext(ctx, GetConfigurationGroupByName, arg.TenantID, arg.Name)
	var i ConfigurationGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAssignmentsByGroup = `-- name: ListAssignmentsByGroup :many
SELECT id, configuration_group_id, target_type, target_id, priority, enforced, created_at FROM configuration_group_assignments
WHERE configuration_group_id = ?1
ORDER BY target_type, target_id
`

func (q *Queries) ListAssignmentsByGroup(ctx context.Context, configurationGroupID int64) ([]ConfigurationGroupAssignment, error) {
	rows, err := q.db.QueryContext(ctx, ListAssignmentsByGroup, configurationGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationGroupAssignment{}
	for rows.Next() {
		var i ConfigurationGroupAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ConfigurationGroupID,
			&i.TargetType,
			&i.TargetID,
			&i.Priority,
			&i.Enforced,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAssignmentsByTarget = `-- name: ListAssignmentsByTarget :many
SELECT a.id, a.configuration_group_id, a.target_type, a.target_id, a.priority, a.enforced, a.created_at, g.name as group_name, g.scope as group_scope
FROM configuration_group_assignments a
JOIN configuration_groups g ON g.id = a.configuration_group_id
WHERE a.target_type = ?1 AND a.target_id = ?2
ORDER BY a.priority DESC
`

type ListAssignmentsByTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   int64  `json:"target_id"`
}

type ListAssignmentsByTargetRow struct {
	ID                   int64     `json:"id"`
	ConfigurationGroupID int64     `json:"configuration_group_id"`
	TargetType           string    `json:"target_type"`
	TargetID             int64     `json:"target_id"`
	Priority             int64     `json:"priority"`
	Enforced             bool      `json:"enforced"`
	CreatedAt            time.Time `json:"created_at"`
	GroupName            string    `json:"group_name"`
	GroupScope           string    `json:"group_scope"`
}

func (q *Queries) ListAssignmentsByTarget(ctx context.Context, arg ListAssignmentsByTargetParams) ([]ListAssignmentsByTargetRow, error) {
	rows, err := q.db.QueryContext(ctx, ListAssignmentsByTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsByTargetRow{}
	for rows.Next() {
		var i ListAssignmentsByTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfigurationGroupID,
			&i.TargetType,
			&i.TargetID,
			&i.Priority,
			&i.Enforced,
			&i.CreatedAt,
			&i.GroupName,
			&i.GroupScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListBindingsByGroup = `-- name: ListBindingsByGroup :many
SELECT b.id, b.configuration_group_id, b.policy_urn, b.state, b.parameter_values, b.module_id, b.module_version_pinned, b.disabled, b.created_at, b.updated_at, m.title as module_title
FROM configuration_group_bindings b
LEFT JOIN policy_modules m ON m.id = b.module_id
WHERE b.configuration_group_id = ?1
ORDER BY b.policy_urn
`

type ListBindingsByGroupRow struct {
	ID                   int64          `json:"id"`
	ConfigurationGroupID int64          `json:"configuration_group_id"`
	PolicyUrn            string         `json:"policy_urn"`
	State                string         `json:"state"`
	ParameterValues      sql.NullString `json:"parameter_values"`
	ModuleID             sql.NullInt64  `json:"module_id"`
	ModuleVersionPinned  sql.NullString `json:"module_version_pinned"`
	Disabled             bool           `json:"disabled"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	ModuleTitle          sql.NullString `json:"module_title"`
}

func (q *Queries) ListBindingsByGroup(ctx context.Context, configurationGroupID int64) ([]ListBindingsByGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, ListBindingsByGroup, configurationGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBindingsByGroupRow{}
	for rows.Next() {
		var i ListBindingsByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfigurationGroupID,
			&i.PolicyUrn,
			&i.State,
			&i.ParameterValues,
			&i.ModuleID,
			&i.ModuleVersionPinned,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModuleTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListBindingsByModule = `-- name: ListBindingsByModule :many
SELECT b.id, b.configuration_group_id, b.policy_urn, b.state, b.parameter_values, b.module_id, b.module_version_pinned, b.disabled, b.created_at, b.updated_at, g.name as group_name
FROM configuration_group_bindings b
JOIN configuration_groups g ON g.id = b.configuration_group_id
WHERE b.module_id = ?1
`

type ListBindingsByModuleRow struct {
	ID                   int64          `json:"id"`
	ConfigurationGroupID int64          `json:"configuration_group_id"`
	PolicyUrn            string         `json:"policy_urn"`
	State                string         `json:"state"`
	ParameterValues      sql.NullString `json:"parameter_values"`
	ModuleID             sql.NullInt64  `json:"module_id"`
	ModuleVersionPinned  sql.NullString `json:"module_version_pinned"`
	Disabled             bool           `json:"disabled"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	GroupName            string         `json:"group_name"`
}

func (q *Queries) ListBindingsByModule(ctx context.Context, moduleID sql.NullInt64) ([]ListBindingsByModuleRow, error) {
	rows, err := q.db.QueryContext(ctx, ListBindingsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBindingsByModuleRow{}
	for rows.Next() {
		var i ListBindingsByModuleRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfigurationGroupID,
			&i.PolicyUrn,
			&i.State,
			&i.ParameterValues,
			&i.ModuleID,
			&i.ModuleVersionPinned,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListConfigGroupsForAsset = `-- name: ListConfigGroupsForAsset :many
SELECT DISTINCT g.id, g.tenant_id, g.name, g.description, g.scope, g.disabled, g.created_at, g.updated_at
FROM configuration_groups g
JOIN configuration_group_assignments a ON a.configuration_group_id = g.id
WHERE g.disabled = FALSE
  AND ((a.target_type = 'asset' AND a.target_id = ?1)
   OR (a.target_type = 'group' AND a.target_id IN (
       SELECT gm.group_id FROM group_memberships gm WHERE gm.asset_id = ?1
   ))
   OR (a.target_type = 'site' AND a.target_id = ?2)
   OR (a.target_type = 'tenant' AND a.target_id = ?3))
ORDER BY a.priority DESC
`

type ListConfigGroupsForAssetParams struct {
	AssetID  int64 `json:"asset_id"`
	SiteID   int64 `json:"site_id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) ListConfigGroupsForAsset(ctx context.Context, arg ListConfigGroupsForAssetParams) ([]ConfigurationGroup, error) {
	rows, err := q.db.QueryContext(ctx, ListConfigGroupsForAsset, arg.AssetID, arg.SiteID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationGroup{}
	for rows.Next() {
		var i ConfigurationGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListConfigurationGroupsByTenant = `-- name: ListConfigurationGroupsByTenant :many
SELECT id, tenant_id, name, description, scope, disabled, created_at, updated_at FROM configuration_groups 
WHERE tenant_id = ?1 
ORDER BY name
LIMIT ?3 OFFSET ?2
`

type ListConfigurationGroupsByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Offset   int64 `json:"offset"`
	Limit    int64 `json:"limit"`
}

func (q *Queries) ListConfigurationGroupsByTenant(ctx context.Context, arg ListConfigurationGroupsByTenantParams) ([]ConfigurationGroup, error) {
	rows, err := q.db.QueryContext(ctx, ListConfigurationGroupsByTenant, arg.TenantID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationGroup{}
	for rows.Next() {
		var i ConfigurationGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListEnabledConfigurationGroups = `-- name: ListEnabledConfigurationGroups :many
SELECT id, tenant_id, name, description, scope, disabled, created_at, updated_at FROM configuration_groups 
WHERE tenant_id = ?1 AND disabled = FALSE
ORDER BY name
`

func (q *Queries) ListEnabledConfigurationGroups(ctx context.Context, tenantID int64) ([]ConfigurationGroup, error) {
	rows, err := q.db.QueryContext(ctx, ListEnabledConfigurationGroups, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationGroup{}
	for rows.Next() {
		var i ConfigurationGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchConfigurationGroups = `-- name: SearchConfigurationGroups :many
SELECT id, tenant_id, name, description, scope, disabled, created_at, updated_at FROM configuration_groups
WHERE tenant_id = ?1
  AND (name LIKE '%' || ?2 || '%' OR description LIKE '%' || ?2 || '%')
ORDER BY name
LIMIT ?3
`

type SearchConfigurationGroupsParams struct {
	TenantID int64          `json:"tenant_id"`
	Search   sql.NullString `json:"search"`
	Limit    int64          `json:"limit"`
}

func (q *Queries) SearchConfigurationGroups(ctx context.Context, arg SearchConfigurationGroupsParams) ([]ConfigurationGroup, error) {
	rows, err := q.db.QueryContext(ctx, SearchConfigurationGroups, arg.TenantID, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationGroup{}
	for rows.Next() {
		var i ConfigurationGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateConfigurationGroup = `-- name: UpdateConfigurationGroup :one
UPDATE configuration_groups SET
    name = ?1,
    description = ?2,
    scope = ?3,
    disabled = ?4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?5
RETURNING id, tenant_id, name, description, scope, disabled, created_at, updated_at
`

type UpdateConfigurationGroupParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Scope       string         `json:"scope"`
	Disabled    bool           `json:"disabled"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateConfigurationGroup(ctx context.Context, arg UpdateConfigurationGroupParams) (ConfigurationGroup, error) {
	row := q.db.QueryRowContext(ctx, UpdateConfigurationGroup,
		arg.Name,
		arg.Description,
		arg.Scope,
		arg.Disabled,
		arg.ID,
	)
	var i ConfigurationGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateConfigurationGroupAssignment = `-- name: UpdateConfigurationGroupAssignment :one
UPDATE configuration_group_assignments SET
    priority = ?1,
    enforced = ?2
WHERE id = ?3
RETURNING id, configuration_group_id, target_type, target_id, priority, enforced, created_at
`

type UpdateConfigurationGroupAssignmentParams struct {
	Priority int64 `json:"priority"`
	Enforced bool  `json:"enforced"`
	ID       int64 `json:"id"`
}

// Updates priority/enforced on an existing assignment. target_type/
// target_id/group are immutable after creation (remove + re-add to
// retarget); this only covers the fields the detail-page assignments
// table lets an admin tweak in place.
func (q *Queries) UpdateConfigurationGroupAssignment(ctx context.Context, arg UpdateConfigurationGroupAssignmentParams) (ConfigurationGroupAssignment, error) {
	row := q.db.QueryRowContext(ctx, UpdateConfigurationGroupAssignment, arg.Priority, arg.Enforced, arg.ID)
	var i ConfigurationGroupAssignment
	err := row.Scan(
		&i.ID,
		&i.ConfigurationGroupID,
		&i.TargetType,
		&i.TargetID,
		&i.Priority,
		&i.Enforced,
		&i.CreatedAt,
	)
	return i, err
}

const UpdateConfigurationGroupBinding = `-- name: UpdateConfigurationGroupBinding :one
UPDATE configuration_group_bindings SET
    state = ?1,
    parameter_values = ?2,
    module_id = ?3,
    module_version_pinned = ?4,
    disabled = ?5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?6
RETURNING id, configuration_group_id, policy_urn, state, parameter_values, module_id, module_version_pinned, disabled, created_at, updated_at
`

type UpdateConfigurationGroupBindingParams struct {
	State               string         `json:"state"`
	ParameterValues     sql.NullString `json:"parameter_values"`
	ModuleID            sql.NullInt64  `json:"module_id"`
	ModuleVersionPinned sql.NullString `json:"module_version_pinned"`
	Disabled            bool           `json:"disabled"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateConfigurationGroupBinding(ctx context.Context, arg UpdateConfigurationGroupBindingParams) (ConfigurationGroupBinding, error) {
	row := q.db.QueryRowContext(ctx, UpdateConfigurationGroupBinding,
		arg.State,
		arg.ParameterValues,
		arg.ModuleID,
		arg.ModuleVersionPinned,
		arg.Disabled,
		arg.ID,
	)
	var i ConfigurationGroupBinding
	err := row.Scan(
		&i.ID,
		&i.ConfigurationGroupID,
		&i.PolicyUrn,
		&i.State,
		&i.ParameterValues,
		&i.ModuleID,
		&i.ModuleVersionPinned,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
