// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: custom_policies.sql

package db

import (
	"context"
	"database/sql"
)

const CountCustomPoliciesByTenant = `-- name: CountCustomPoliciesByTenant :one
SELECT COUNT(*) FROM custom_policies WHERE tenant_id = ?1
`

func (q *Queries) CountCustomPoliciesByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountCustomPoliciesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateCustomPolicy = `-- name: CreateCustomPolicy :one

INSERT INTO custom_policies (
    tenant_id,
    policy_urn,
    name,
    description,
    scope,
    category_path,
    parameters_schema
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
) RETURNING id, tenant_id, policy_urn, name, description, scope, category_path, parameters_schema, created_at
`

type CreateCustomPolicyParams struct {
	TenantID         int64          `json:"tenant_id"`
	PolicyUrn        string         `json:"policy_urn"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Scope            string         `json:"scope"`
	CategoryPath     string         `json:"category_path"`
	ParametersSchema sql.NullString `json:"parameters_schema"`
}

// Custom policy queries
// Custom policies are tenant-specific policy definitions (not from bundled catalog)
func (q *Queries) CreateCustomPolicy(ctx context.Context, arg CreateCustomPolicyParams) (CustomPolicy, error) {
	row := q.db.QueryRowContext(ctx, CreateCustomPolicy,
		arg.TenantID,
		arg.PolicyUrn,
		arg.Name,
		arg.Description,
		arg.Scope,
		arg.CategoryPath,
		arg.ParametersSchema,
	)
	var i CustomPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyUrn,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.CategoryPath,
		&i.ParametersSchema,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteCustomPolicy = `-- name: DeleteCustomPolicy :exec
DELETE FROM custom_policies WHERE id = ?1
`

func (q *Queries) DeleteCustomPolicy(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteCustomPolicy, id)
	return err
}

const GetCustomPolicy = `-- name: GetCustomPolicy :one
SELECT id, tenant_id, policy_urn, name, description, scope, category_path, parameters_schema, created_at FROM custom_policies WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetCustomPolicy(ctx context.Context, id int64) (CustomPolicy, error) {
	row := q.db.QueryRowContext(ctx, GetCustomPolicy, id)
	var i CustomPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyUrn,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.CategoryPath,
		&i.ParametersSchema,
		&i.CreatedAt,
	)
	return i, err
}

const GetCustomPolicyByURN = `-- name: GetCustomPolicyByURN :one
SELECT id, tenant_id, policy_urn, name, description, scope, category_path, parameters_schema, created_at FROM custom_policies 
WHERE tenant_id = ?1 AND policy_urn = ?2 
LIMIT 1
`

type GetCustomPolicyByURNParams struct {
	TenantID  int64  `json:"tenant_id"`
	PolicyUrn string `json:"policy_urn"`
}

func (q *Queries) GetCustomPolicyByURN(ctx context.Context, arg GetCustomPolicyByURNParams) (CustomPolicy, error) {
	row := q.db.QueryRowContext(ctx, GetCustomPolicyByURN, arg.TenantID, arg.PolicyUrn)
	var i CustomPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyUrn,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.CategoryPath,
		&i.ParametersSchema,
		&i.CreatedAt,
	)
	return i, err
}

const ListCustomPoliciesByCategory = `-- name: ListCustomPoliciesByCategory :many
SELECT id, tenant_id, policy_urn, name, description, scope, category_path, parameters_schema, created_at FROM custom_policies 
WHERE tenant_id = ?1 AND category_path LIKE ?2 || '%'
ORDER BY name
`

type ListCustomPoliciesByCategoryParams struct {
	TenantID       int64          `json:"tenant_id"`
	CategoryPrefix sql.NullString `json:"category_prefix"`
}

func (q *Queries) ListCustomPoliciesByCategory(ctx context.Context, arg ListCustomPoliciesByCategoryParams) ([]CustomPolicy, error) {
	rows, err := q.db.QueryContext(ctx, ListCustomPoliciesByCategory, arg.TenantID, arg.CategoryPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomPolicy{}
	for rows.Next() {
		var i CustomPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PolicyUrn,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.CategoryPath,
			&i.ParametersSchema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCustomPoliciesByScope = `-- name: ListCustomPoliciesByScope :many
SELECT id, tenant_id, policy_urn, name, description, scope, category_path, parameters_schema, created_at FROM custom_policies 
WHERE tenant_id = ?1 AND scope = ?2
ORDER BY category_path, name
`

type ListCustomPoliciesByScopeParams struct {
	TenantID int64  `json:"tenant_id"`
	Scope    string `json:"scope"`
}

func (q *Queries) ListCustomPoliciesByScope(ctx context.Context, arg ListCustomPoliciesByScopeParams) ([]CustomPolicy, error) {
	rows, err := q.db.QueryContext(ctx, ListCustomPoliciesByScope, arg.TenantID, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomPolicy{}
	for rows.Next() {
		var i CustomPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PolicyUrn,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.CategoryPath,
			&i.ParametersSchema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCustomPoliciesByTenant = `-- name: ListCustomPoliciesByTenant :many
SELECT id, tenant_id, policy_urn, name, description, scope, category_path, parameters_schema, created_at FROM custom_policies 
WHERE tenant_id = ?1 
ORDER BY category_path, name
LIMIT ?3 OFFSET ?2
`

type ListCustomPoliciesByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Offset   int64 `json:"offset"`
	Limit    int64 `json:"limit"`
}

func (q *Queries) ListCustomPoliciesByTenant(ctx context.Context, arg ListCustomPoliciesByTenantParams) ([]CustomPolicy, error) {
	rows, err := q.db.QueryContext(ctx, ListCustomPoliciesByTenant, arg.TenantID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomPolicy{}
	for rows.Next() {
		var i CustomPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PolicyUrn,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.CategoryPath,
			&i.ParametersSchema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchCustomPolicies = `-- name: SearchCustomPolicies :many
SELECT id, tenant_id, policy_urn, name, description, scope, category_path, parameters_schema, created_at FROM custom_policies
WHERE tenant_id = ?1
  AND (name LIKE '%' || ?2 || '%' OR policy_urn LIKE '%' || ?2 || '%')
ORDER BY category_path, name
LIMIT ?3
`

type SearchCustomPoliciesParams struct {
	TenantID int64          `json:"tenant_id"`
	Search   sql.NullString `json:"search"`
	Limit    int64          `json:"limit"`
}

func (q *Queries) SearchCustomPolicies(ctx context.Context, arg SearchCustomPoliciesParams) ([]CustomPolicy, error) {
	rows, err := q.db.QueryContext(ctx, SearchCustomPolicies, arg.TenantID, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomPolicy{}
	for rows.Next() {
		var i CustomPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PolicyUrn,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.CategoryPath,
			&i.ParametersSchema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateCustomPolicy = `-- name: UpdateCustomPolicy :one
UPDATE custom_policies SET
    name = ?1,
    description = ?2,
    scope = ?3,
    category_path = ?4,
    parameters_schema = ?5
WHERE id = ?6
RETURNING id, tenant_id, policy_urn, name, description, scope, category_path, parameters_schema, created_at
`

type UpdateCustomPolicyParams struct {
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Scope            string         `json:"scope"`
	CategoryPath     string         `json:"category_path"`
	ParametersSchema sql.NullString `json:"parameters_schema"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateCustomPolicy(ctx context.Context, arg UpdateCustomPolicyParams) (CustomPolicy, error) {
	row := q.db.QueryRowContext(ctx, UpdateCustomPolicy,
		arg.Name,
		arg.Description,
		arg.Scope,
		arg.CategoryPath,
		arg.ParametersSchema,
		arg.ID,
	)
	var i CustomPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyUrn,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.CategoryPath,
		&i.ParametersSchema,
		&i.CreatedAt,
	)
	return i, err
}
