// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dependency_groups.sql

package db

import (
	"context"
	"database/sql"
)

const CountLinksForGroup = `-- name: CountLinksForGroup :one
SELECT COUNT(*) FROM module_dependency_links WHERE group_id = ?1
`

func (q *Queries) CountLinksForGroup(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountLinksForGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountLinksForModule = `-- name: CountLinksForModule :one
SELECT COUNT(*) FROM module_dependency_links WHERE tenant_id = ?1 AND module_id = ?2
`

type CountLinksForModuleParams struct {
	TenantID int64  `json:"tenant_id"`
	ModuleID string `json:"module_id"`
}

// Used by the module service's DeleteModule guard: a module referenced
// by any dependency-group link may not be deleted (see
// pkg/services/policymodules.go).
func (q *Queries) CountLinksForModule(ctx context.Context, arg CountLinksForModuleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountLinksForModule, arg.TenantID, arg.ModuleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateDependencyGroup = `-- name: CreateDependencyGroup :one

INSERT INTO dependency_groups (tenant_id, slug, name, description, is_builtin)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, tenant_id, slug, name, description, is_builtin, created_at, updated_at, match_mode
`

type CreateDependencyGroupParams struct {
	TenantID    int64          `json:"tenant_id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsBuiltin   bool           `json:"is_builtin"`
}

// Dependency group queries. Matches the tables in
// db/schema/004_dependency_groups.sql. Groups are per tenant module
// applicability filters; conditions AND within a group; module links
// attach a group to a module in a role (platform or requirement).
func (q *Queries) CreateDependencyGroup(ctx context.Context, arg CreateDependencyGroupParams) (DependencyGroup, error) {
	row := q.db.QueryRowContext(ctx, CreateDependencyGroup,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.IsBuiltin,
	)
	var i DependencyGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchMode,
	)
	return i, err
}

const CreateDependencyGroupCondition = `-- name: CreateDependencyGroupCondition :one
INSERT INTO dependency_group_conditions (group_id, param_path, operator, value_json, seq, kind, script_source, script_expect)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING id, group_id, param_path, operator, value_json, seq, kind, script_source, script_expect
`

type CreateDependencyGroupConditionParams struct {
	GroupID      int64  `json:"group_id"`
	ParamPath    string `json:"param_path"`
	Operator     string `json:"operator"`
	ValueJson    string `json:"value_json"`
	Seq          int64  `json:"seq"`
	Kind         string `json:"kind"`
	ScriptSource string `json:"script_source"`
	ScriptExpect string `json:"script_expect"`
}

func (q *Queries) CreateDependencyGroupCondition(ctx context.Context, arg CreateDependencyGroupConditionParams) (DependencyGroupCondition, error) {
	row := q.db.QueryRowContext(ctx, CreateDependencyGroupCondition,
		arg.GroupID,
		arg.ParamPath,
		arg.Operator,
		arg.ValueJson,
		arg.Seq,
		arg.Kind,
		arg.ScriptSource,
		arg.ScriptExpect,
	)
	var i DependencyGroupCondition
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ParamPath,
		&i.Operator,
		&i.ValueJson,
		&i.Seq,
		&i.Kind,
		&i.ScriptSource,
		&i.ScriptExpect,
	)
	return i, err
}

const CreateModuleDependencyLink = `-- name: CreateModuleDependencyLink :exec
INSERT OR IGNORE INTO module_dependency_links (tenant_id, module_id, group_id, role)
VALUES (?1, ?2, ?3, ?4)
`

type CreateModuleDependencyLinkParams struct {
	TenantID int64  `json:"tenant_id"`
	ModuleID string `json:"module_id"`
	GroupID  int64  `json:"group_id"`
	Role     string `json:"role"`
}

func (q *Queries) CreateModuleDependencyLink(ctx context.Context, arg CreateModuleDependencyLinkParams) error {
	_, err := q.db.ExecContext(ctx, CreateModuleDependencyLink,
		arg.TenantID,
		arg.ModuleID,
		arg.GroupID,
		arg.Role,
	)
	return err
}

const DeleteConditionsForGroup = `-- name: DeleteConditionsForGroup :exec
DELETE FROM dependency_group_conditions WHERE group_id = ?1
`

func (q *Queries) DeleteConditionsForGroup(ctx context.Context, groupID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteConditionsForGroup, groupID)
	return err
}

const DeleteDependencyGroup = `-- name: DeleteDependencyGroup :exec
DELETE FROM dependency_groups WHERE id = ?1
`

func (q *Queries) DeleteDependencyGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteDependencyGroup, id)
	return err
}

const DeleteDependencyGroupCondition = `-- name: DeleteDependencyGroupCondition :exec
DELETE FROM dependency_group_conditions WHERE id = ?1 AND group_id = ?2
`

type DeleteDependencyGroupConditionParams struct {
	ID      int64 `json:"id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) DeleteDependencyGroupCondition(ctx context.Context, arg DeleteDependencyGroupConditionParams) error {
	_, err := q.db.ExecContext(ctx, DeleteDependencyGroupCondition, arg.ID, arg.GroupID)
	return err
}

const DeleteModuleDependencyLink = `-- name: DeleteModuleDependencyLink :exec
DELETE FROM module_dependency_links
WHERE tenant_id = ?1 AND module_id = ?2 AND group_id = ?3
`

type DeleteModuleDependencyLinkParams struct {
	TenantID int64  `json:"tenant_id"`
	ModuleID string `json:"module_id"`
	GroupID  int64  `json:"group_id"`
}

func (q *Queries) DeleteModuleDependencyLink(ctx context.Context, arg DeleteModuleDependencyLinkParams) error {
	_, err := q.db.ExecContext(ctx, DeleteModuleDependencyLink, arg.TenantID, arg.ModuleID, arg.GroupID)
	return err
}

const GetDependencyGroup = `-- name: GetDependencyGroup :one
SELECT id, tenant_id, slug, name, description, is_builtin, created_at, updated_at, match_mode FROM dependency_groups WHERE id = ?1
`

func (q *Queries) GetDependencyGroup(ctx context.Context, id int64) (DependencyGroup, error) {
	row := q.db.QueryRowContext(ctx, GetDependencyGroup, id)
	var i DependencyGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchMode,
	)
	return i, err
}

const GetDependencyGroupBySlug = `-- name: GetDependencyGroupBySlug :one
SELECT id, tenant_id, slug, name, description, is_builtin, created_at, updated_at, match_mode FROM dependency_groups
WHERE tenant_id = ?1 AND slug = ?2
LIMIT 1
`

type GetDependencyGroupBySlugParams struct {
	TenantID int64  `json:"tenant_id"`
	Slug     string `json:"slug"`
}

func (q *Queries) GetDependencyGroupBySlug(ctx context.Context, arg GetDependencyGroupBySlugParams) (DependencyGroup, error) {
	row := q.db.QueryRowContext(ctx, GetDependencyGroupBySlug, arg.TenantID, arg.Slug)
	var i DependencyGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchMode,
	)
	return i, err
}

const ListConditionsForGroup = `-- name: ListConditionsForGroup :many
SELECT id, group_id, param_path, operator, value_json, seq, kind, script_source, script_expect FROM dependency_group_conditions
WHERE group_id = ?1
ORDER BY seq, id
`

func (q *Queries) ListConditionsForGroup(ctx context.Context, groupID int64) ([]DependencyGroupCondition, error) {
	rows, err := q.db.QueryContext(ctx, ListConditionsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DependencyGroupCondition{}
	for rows.Next() {
		var i DependencyGroupCondition
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ParamPath,
			&i.Operator,
			&i.ValueJson,
			&i.Seq,
			&i.Kind,
			&i.ScriptSource,
			&i.ScriptExpect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDependencyGroupsByTenant = `-- name: ListDependencyGroupsByTenant :many
SELECT id, tenant_id, slug, name, description, is_builtin, created_at, updated_at, match_mode FROM dependency_groups
WHERE tenant_id = ?1
ORDER BY is_builtin DESC, name
`

func (q *Queries) ListDependencyGroupsByTenant(ctx context.Context, tenantID int64) ([]DependencyGroup, error) {
	rows, err := q.db.QueryContext(ctx, ListDependencyGroupsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DependencyGroup{}
	for rows.Next() {
		var i DependencyGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsBuiltin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListLinksForGroup = `-- name: ListLinksForGroup :many
SELECT id, tenant_id, module_id, group_id, role FROM module_dependency_links
WHERE group_id = ?1
ORDER BY module_id
`

func (q *Queries) ListLinksForGroup(ctx context.Context, groupID int64) ([]ModuleDependencyLink, error) {
	rows, err := q.db.QueryContext(ctx, ListLinksForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModuleDependencyLink{}
	for rows.Next() {
		var i ModuleDependencyLink
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ModuleID,
			&i.GroupID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListLinksForModule = `-- name: ListLinksForModule :many
SELECT id, tenant_id, module_id, group_id, role FROM module_dependency_links
WHERE tenant_id = ?1 AND module_id = ?2
ORDER BY role, group_id
`

type ListLinksForModuleParams struct {
	TenantID int64  `json:"tenant_id"`
	ModuleID string `json:"module_id"`
}

func (q *Queries) ListLinksForModule(ctx context.Context, arg ListLinksForModuleParams) ([]ModuleDependencyLink, error) {
	rows, err := q.db.QueryContext(ctx, ListLinksForModule, arg.TenantID, arg.ModuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModuleDependencyLink{}
	for rows.Next() {
		var i ModuleDependencyLink
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ModuleID,
			&i.GroupID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDependencyGroup = `-- name: UpdateDependencyGroup :exec
UPDATE dependency_groups
SET name = ?1, description = ?2, updated_at = CURRENT_TIMESTAMP
WHERE id = ?3
`

type UpdateDependencyGroupParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateDependencyGroup(ctx context.Context, arg UpdateDependencyGroupParams) error {
	_, err := q.db.ExecContext(ctx, UpdateDependencyGroup, arg.Name, arg.Description, arg.ID)
	return err
}

const UpdateGroupMatchMode = `-- name: UpdateGroupMatchMode :exec
UPDATE dependency_groups
SET match_mode = ?1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateGroupMatchModeParams struct {
	MatchMode string `json:"match_mode"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateGroupMatchMode(ctx context.Context, arg UpdateGroupMatchModeParams) error {
	_, err := q.db.ExecContext(ctx, UpdateGroupMatchMode, arg.MatchMode, arg.ID)
	return err
}
