// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: group_rules.sql

package db

import (
	"context"
	"database/sql"
)

const AddAssetToGroupWithSource = `-- name: AddAssetToGroupWithSource :exec

INSERT INTO group_memberships (group_id, asset_id, source)
VALUES (?1, ?2, ?3)
ON CONFLICT DO NOTHING
`

type AddAssetToGroupWithSourceParams struct {
	GroupID int64         `json:"group_id"`
	AssetID sql.NullInt64 `json:"asset_id"`
	Source  string        `json:"source"`
}

// ============================================================================
// Rule-sourced membership reconciliation
// ============================================================================
func (q *Queries) AddAssetToGroupWithSource(ctx context.Context, arg AddAssetToGroupWithSourceParams) error {
	_, err := q.db.ExecContext(ctx, AddAssetToGroupWithSource, arg.GroupID, arg.AssetID, arg.Source)
	return err
}

const AddIdentityToGroupWithSource = `-- name: AddIdentityToGroupWithSource :exec
INSERT INTO group_memberships (group_id, identity_id, source)
VALUES (?1, ?2, ?3)
ON CONFLICT DO NOTHING
`

type AddIdentityToGroupWithSourceParams struct {
	GroupID    int64         `json:"group_id"`
	IdentityID sql.NullInt64 `json:"identity_id"`
	Source     string        `json:"source"`
}

func (q *Queries) AddIdentityToGroupWithSource(ctx context.Context, arg AddIdentityToGroupWithSourceParams) error {
	_, err := q.db.ExecContext(ctx, AddIdentityToGroupWithSource, arg.GroupID, arg.IdentityID, arg.Source)
	return err
}

const CountDirectAssetsInGroup = `-- name: CountDirectAssetsInGroup :one
SELECT COUNT(*) FROM group_memberships
WHERE group_id = ?1 AND asset_id IS NOT NULL AND source = 'direct'
`

func (q *Queries) CountDirectAssetsInGroup(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountDirectAssetsInGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountDirectIdentitiesInGroup = `-- name: CountDirectIdentitiesInGroup :one
SELECT COUNT(*) FROM group_memberships
WHERE group_id = ?1 AND identity_id IS NOT NULL AND source = 'direct'
`

func (q *Queries) CountDirectIdentitiesInGroup(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountDirectIdentitiesInGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateGroupMembershipRule = `-- name: CreateGroupMembershipRule :one

INSERT INTO group_membership_rules (group_id, kind, param_path, operator, value_json, script_source, script_expect, seq)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING id, group_id, kind, param_path, operator, value_json, script_source, script_expect, seq
`

type CreateGroupMembershipRuleParams struct {
	GroupID      int64  `json:"group_id"`
	Kind         string `json:"kind"`
	ParamPath    string `json:"param_path"`
	Operator     string `json:"operator"`
	ValueJson    string `json:"value_json"`
	ScriptSource string `json:"script_source"`
	ScriptExpect string `json:"script_expect"`
	Seq          int64  `json:"seq"`
}

// ============================================================================
// Membership rules (group_membership_rules)
// ============================================================================
func (q *Queries) CreateGroupMembershipRule(ctx context.Context, arg CreateGroupMembershipRuleParams) (GroupMembershipRule, error) {
	row := q.db.QueryRowContext(ctx, CreateGroupMembershipRule,
		arg.GroupID,
		arg.Kind,
		arg.ParamPath,
		arg.Operator,
		arg.ValueJson,
		arg.ScriptSource,
		arg.ScriptExpect,
		arg.Seq,
	)
	var i GroupMembershipRule
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Kind,
		&i.ParamPath,
		&i.Operator,
		&i.ValueJson,
		&i.ScriptSource,
		&i.ScriptExpect,
		&i.Seq,
	)
	return i, err
}

const DeleteAllRuleSourcedMembersForGroup = `-- name: DeleteAllRuleSourcedMembersForGroup :exec
DELETE FROM group_memberships
WHERE group_id = ?1 AND source = 'rule'
`

func (q *Queries) DeleteAllRuleSourcedMembersForGroup(ctx context.Context, groupID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAllRuleSourcedMembersForGroup, groupID)
	return err
}

const DeleteGroupMembershipRule = `-- name: DeleteGroupMembershipRule :exec
DELETE FROM group_membership_rules WHERE id = ?1 AND group_id = ?2
`

type DeleteGroupMembershipRuleParams struct {
	ID      int64 `json:"id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) DeleteGroupMembershipRule(ctx context.Context, arg DeleteGroupMembershipRuleParams) error {
	_, err := q.db.ExecContext(ctx, DeleteGroupMembershipRule, arg.ID, arg.GroupID)
	return err
}

const DeleteRuleSourcedAssetFromGroup = `-- name: DeleteRuleSourcedAssetFromGroup :exec
DELETE FROM group_memberships
WHERE group_id = ?1 AND asset_id = ?2 AND source = 'rule'
`

type DeleteRuleSourcedAssetFromGroupParams struct {
	GroupID int64         `json:"group_id"`
	AssetID sql.NullInt64 `json:"asset_id"`
}

func (q *Queries) DeleteRuleSourcedAssetFromGroup(ctx context.Context, arg DeleteRuleSourcedAssetFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, DeleteRuleSourcedAssetFromGroup, arg.GroupID, arg.AssetID)
	return err
}

const DeleteRuleSourcedIdentityFromGroup = `-- name: DeleteRuleSourcedIdentityFromGroup :exec
DELETE FROM group_memberships
WHERE group_id = ?1 AND identity_id = ?2 AND source = 'rule'
`

type DeleteRuleSourcedIdentityFromGroupParams struct {
	GroupID    int64         `json:"group_id"`
	IdentityID sql.NullInt64 `json:"identity_id"`
}

func (q *Queries) DeleteRuleSourcedIdentityFromGroup(ctx context.Context, arg DeleteRuleSourcedIdentityFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, DeleteRuleSourcedIdentityFromGroup, arg.GroupID, arg.IdentityID)
	return err
}

const DeleteRulesForGroup = `-- name: DeleteRulesForGroup :exec
DELETE FROM group_membership_rules WHERE group_id = ?1
`

func (q *Queries) DeleteRulesForGroup(ctx context.Context, groupID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteRulesForGroup, groupID)
	return err
}

const ListDirectAssetIDsForGroup = `-- name: ListDirectAssetIDsForGroup :many
SELECT asset_id FROM group_memberships
WHERE group_id = ?1 AND source = 'direct' AND asset_id IS NOT NULL
`

func (q *Queries) ListDirectAssetIDsForGroup(ctx context.Context, groupID int64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, ListDirectAssetIDsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var asset_id sql.NullInt64
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDirectIdentityIDsForGroup = `-- name: ListDirectIdentityIDsForGroup :many
SELECT identity_id FROM group_memberships
WHERE group_id = ?1 AND source = 'direct' AND identity_id IS NOT NULL
`

func (q *Queries) ListDirectIdentityIDsForGroup(ctx context.Context, groupID int64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, ListDirectIdentityIDsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var identity_id sql.NullInt64
		if err := rows.Scan(&identity_id); err != nil {
			return nil, err
		}
		items = append(items, identity_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRuleSourcedAssetIDsForGroup = `-- name: ListRuleSourcedAssetIDsForGroup :many
SELECT asset_id FROM group_memberships
WHERE group_id = ?1 AND source = 'rule' AND asset_id IS NOT NULL
`

func (q *Queries) ListRuleSourcedAssetIDsForGroup(ctx context.Context, groupID int64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, ListRuleSourcedAssetIDsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var asset_id sql.NullInt64
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRuleSourcedIdentityIDsForGroup = `-- name: ListRuleSourcedIdentityIDsForGroup :many
SELECT identity_id FROM group_memberships
WHERE group_id = ?1 AND source = 'rule' AND identity_id IS NOT NULL
`

func (q *Queries) ListRuleSourcedIdentityIDsForGroup(ctx context.Context, groupID int64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, ListRuleSourcedIdentityIDsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var identity_id sql.NullInt64
		if err := rows.Scan(&identity_id); err != nil {
			return nil, err
		}
		items = append(items, identity_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRulesForGroup = `-- name: ListRulesForGroup :many
SELECT id, group_id, kind, param_path, operator, value_json, script_source, script_expect, seq FROM group_membership_rules
WHERE group_id = ?1
ORDER BY seq, id
`

func (q *Queries) ListRulesForGroup(ctx context.Context, groupID int64) ([]GroupMembershipRule, error) {
	rows, err := q.db.QueryContext(ctx, ListRulesForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMembershipRule{}
	for rows.Next() {
		var i GroupMembershipRule
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Kind,
			&i.ParamPath,
			&i.Operator,
			&i.ValueJson,
			&i.ScriptSource,
			&i.ScriptExpect,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateGroupMeta = `-- name: UpdateGroupMeta :exec


UPDATE groups SET
    description = ?1,
    member_kind = ?2,
    membership = ?3,
    rules_match_mode = ?4
WHERE id = ?5
`

type UpdateGroupMetaParams struct {
	Description    string `json:"description"`
	MemberKind     string `json:"member_kind"`
	Membership     string `json:"membership"`
	RulesMatchMode string `json:"rules_match_mode"`
	ID             int64  `json:"id"`
}

// Group member-kind/membership metadata and dynamic membership rules.
// Matches db/schema/009_group_kinds_rules.sql. group_membership_rules
// mirrors dependency_group_conditions column-for-column (see that
// migration's header comment) so both are driven by the same eval
// engine (catalog/dependencygroups/eval.go).
// ============================================================================
// Group metadata (member_kind / membership / rules_match_mode / description)
// ============================================================================
func (q *Queries) UpdateGroupMeta(ctx context.Context, arg UpdateGroupMetaParams) error {
	_, err := q.db.ExecContext(ctx, UpdateGroupMeta,
		arg.Description,
		arg.MemberKind,
		arg.Membership,
		arg.RulesMatchMode,
		arg.ID,
	)
	return err
}
