// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_members_detail.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CountConfigGroupAssignmentsForGroupTarget = `-- name: CountConfigGroupAssignmentsForGroupTarget :one
SELECT COUNT(*) FROM configuration_group_assignments
WHERE target_type = 'group' AND target_id = ?1
`

// Delete-guard: configuration_group_assignments.target_id is a
// polymorphic reference (no FK -- see 001_initial.sql's comment on that
// table) so deleting a group referenced there would leave a dangling
// assignment row pointing at a now-nonexistent group id. Group deletion
// is blocked while any assignment still targets it (target_type='group').
func (q *Queries) CountConfigGroupAssignmentsForGroupTarget(ctx context.Context, targetID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountConfigGroupAssignmentsForGroupTarget, targetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateGroupFull = `-- name: CreateGroupFull :one
INSERT INTO groups (tenant_id, site_id, name, slug, group_category, group_scope, description, member_kind, membership, rules_match_mode)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
RETURNING id, tenant_id, site_id, name, slug, created_at, group_category, group_scope, description, member_kind, membership, rules_match_mode, deleted_at, deleted_by
`

type CreateGroupFullParams struct {
	TenantID       int64         `json:"tenant_id"`
	SiteID         sql.NullInt64 `json:"site_id"`
	Name           string        `json:"name"`
	Slug           string        `json:"slug"`
	GroupCategory  string        `json:"group_category"`
	GroupScope     string        `json:"group_scope"`
	Description    string        `json:"description"`
	MemberKind     string        `json:"member_kind"`
	Membership     string        `json:"membership"`
	RulesMatchMode string        `json:"rules_match_mode"`
}

// Create-page insert: every column the create form + presets need in one
// round trip, rather than CreateGroup (name/slug only) followed by a
// second UpdateGroupMeta call.
func (q *Queries) CreateGroupFull(ctx context.Context, arg CreateGroupFullParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, CreateGroupFull,
		arg.TenantID,
		arg.SiteID,
		arg.Name,
		arg.Slug,
		arg.GroupCategory,
		arg.GroupScope,
		arg.Description,
		arg.MemberKind,
		arg.Membership,
		arg.RulesMatchMode,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.GroupCategory,
		&i.GroupScope,
		&i.Description,
		&i.MemberKind,
		&i.Membership,
		&i.RulesMatchMode,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const GetGroupMembershipSourceForAsset = `-- name: GetGroupMembershipSourceForAsset :one
SELECT source FROM group_memberships WHERE group_id = ?1 AND asset_id = ?2
`

type GetGroupMembershipSourceForAssetParams struct {
	GroupID int64         `json:"group_id"`
	AssetID sql.NullInt64 `json:"asset_id"`
}

func (q *Queries) GetGroupMembershipSourceForAsset(ctx context.Context, arg GetGroupMembershipSourceForAssetParams) (string, error) {
	row := q.db.QueryRowContext(ctx, GetGroupMembershipSourceForAsset, arg.GroupID, arg.AssetID)
	var source string
	err := row.Scan(&source)
	return source, err
}

const GetGroupMembershipSourceForIdentity = `-- name: GetGroupMembershipSourceForIdentity :one
SELECT source FROM group_memberships WHERE group_id = ?1 AND identity_id = ?2
`

type GetGroupMembershipSourceForIdentityParams struct {
	GroupID    int64         `json:"group_id"`
	IdentityID sql.NullInt64 `json:"identity_id"`
}

func (q *Queries) GetGroupMembershipSourceForIdentity(ctx context.Context, arg GetGroupMembershipSourceForIdentityParams) (string, error) {
	row := q.db.QueryRowContext(ctx, GetGroupMembershipSourceForIdentity, arg.GroupID, arg.IdentityID)
	var source string
	err := row.Scan(&source)
	return source, err
}

const ListAssetMembersForGroup = `-- name: ListAssetMembersForGroup :many

SELECT a.id, a.uuid, a.tenant_id, a.site_id, a.subtype, a.subtype_payload, a.enrollment_state, a.enrolled_at, a.last_seen_at, a.agent_version, a.labels, a.lifecycle_state, a.location, a.owner_identity_id, a.vendor, a.purchase_date, a.purchase_price, a.warranty_expires_at, a.human_id, a.created_at, a.updated_at, a.description, a.managed_by_identity_id, a.deleted_at, a.deleted_by, gm.source AS source, gm.created_at AS added_at FROM assets a
INNER JOIN group_memberships gm ON a.id = gm.asset_id
WHERE gm.group_id = ?1 AND a.deleted_at IS NULL
ORDER BY a.human_id
`

type ListAssetMembersForGroupRow struct {
	ID                  int64           `json:"id"`
	Uuid                string          `json:"uuid"`
	TenantID            int64           `json:"tenant_id"`
	SiteID              sql.NullInt64   `json:"site_id"`
	Subtype             string          `json:"subtype"`
	SubtypePayload      string          `json:"subtype_payload"`
	EnrollmentState     string          `json:"enrollment_state"`
	EnrolledAt          sql.NullTime    `json:"enrolled_at"`
	LastSeenAt          sql.NullTime    `json:"last_seen_at"`
	AgentVersion        sql.NullString  `json:"agent_version"`
	Labels              sql.NullString  `json:"labels"`
	LifecycleState      sql.NullString  `json:"lifecycle_state"`
	Location            sql.NullString  `json:"location"`
	OwnerIdentityID     sql.NullInt64   `json:"owner_identity_id"`
	Vendor              sql.NullString  `json:"vendor"`
	PurchaseDate        sql.NullTime    `json:"purchase_date"`
	PurchasePrice       sql.NullFloat64 `json:"purchase_price"`
	WarrantyExpiresAt   sql.NullTime    `json:"warranty_expires_at"`
	HumanID             sql.NullString  `json:"human_id"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	Description         sql.NullString  `json:"description"`
	ManagedByIdentityID sql.NullInt64   `json:"managed_by_identity_id"`
	DeletedAt           interface{}     `json:"deleted_at"`
	DeletedBy           interface{}     `json:"deleted_by"`
	Source              string          `json:"source"`
	AddedAt             time.Time       `json:"added_at"`
}

// Task 6.2 -- Group detail page Members tab + create/delete-guard support.
// Mirrors group_detail.sql's "g.*, gm.created_at AS added_at" shape:
// these two queries add gm.source so the Members tab can render a
// Direct/Dynamic chip per row (fixing the GroupService.ListForAsset/
// ListForIdentity Source hardcoding carry-forward at its root: the raw
// membership row's source column, not a hardcoded "Direct" string).
func (q *Queries) ListAssetMembersForGroup(ctx context.Context, groupID int64) ([]ListAssetMembersForGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, ListAssetMembersForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetMembersForGroupRow{}
	for rows.Next() {
		var i ListAssetMembersForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Source,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListIdentityMembersForGroup = `-- name: ListIdentityMembersForGroup :many
SELECT i.id, i.tenant_id, i.site_id, i.username, i.user_principal_name, i.email, i.display_name, i.given_name, i.surname, i.initials, i.title, i.department, i.company, i.employee_id, i.employee_type, i.manager_id, i.phone_office, i.phone_mobile, i.phone_home, i.fax, i.office, i.street_address, i.city, i.state, i.postal_code, i.country, i.country_code, i.home_directory, i.home_drive, i.profile_path, i.logon_script, i.account_enabled, i.account_locked, i.account_expires_at, i.password_hash, i.password_last_set_at, i.password_never_expires, i.must_change_password, i.last_logon_at, i.logon_count, i.bad_password_count, i.last_bad_password_at, i.role, i.avatar_url, i.locale, i.timezone, i.description, i.notes, i.created_at, i.updated_at, i.deleted_at, i.deleted_by, gm.source AS source, gm.created_at AS added_at FROM identities i
INNER JOIN group_memberships gm ON i.id = gm.identity_id
WHERE gm.group_id = ?1 AND i.deleted_at IS NULL
ORDER BY i.display_name
`

type ListIdentityMembersForGroupRow struct {
	ID                   int64          `json:"id"`
	TenantID             int64          `json:"tenant_id"`
	SiteID               sql.NullInt64  `json:"site_id"`
	Username             string         `json:"username"`
	UserPrincipalName    sql.NullString `json:"user_principal_name"`
	Email                string         `json:"email"`
	DisplayName          string         `json:"display_name"`
	GivenName            sql.NullString `json:"given_name"`
	Surname              sql.NullString `json:"surname"`
	Initials             sql.NullString `json:"initials"`
	Title                sql.NullString `json:"title"`
	Department           sql.NullString `json:"department"`
	Company              sql.NullString `json:"company"`
	EmployeeID           sql.NullString `json:"employee_id"`
	EmployeeType         sql.NullString `json:"employee_type"`
	ManagerID            sql.NullInt64  `json:"manager_id"`
	PhoneOffice          sql.NullString `json:"phone_office"`
	PhoneMobile          sql.NullString `json:"phone_mobile"`
	PhoneHome            sql.NullString `json:"phone_home"`
	Fax                  sql.NullString `json:"fax"`
	Office               sql.NullString `json:"office"`
	StreetAddress        sql.NullString `json:"street_address"`
	City                 sql.NullString `json:"city"`
	State                sql.NullString `json:"state"`
	PostalCode           sql.NullString `json:"postal_code"`
	Country              sql.NullString `json:"country"`
	CountryCode          sql.NullString `json:"country_code"`
	HomeDirectory        sql.NullString `json:"home_directory"`
	HomeDrive            sql.NullString `json:"home_drive"`
	ProfilePath          sql.NullString `json:"profile_path"`
	LogonScript          sql.NullString `json:"logon_script"`
	AccountEnabled       bool           `json:"account_enabled"`
	AccountLocked        bool           `json:"account_locked"`
	AccountExpiresAt     sql.NullTime   `json:"account_expires_at"`
	PasswordHash         sql.NullString `json:"password_hash"`
	PasswordLastSetAt    sql.NullTime   `json:"password_last_set_at"`
	PasswordNeverExpires bool           `json:"password_never_expires"`
	MustChangePassword   bool           `json:"must_change_password"`
	LastLogonAt          sql.NullTime   `json:"last_logon_at"`
	LogonCount           int64          `json:"logon_count"`
	BadPasswordCount     int64          `json:"bad_password_count"`
	LastBadPasswordAt    sql.NullTime   `json:"last_bad_password_at"`
	Role                 string         `json:"role"`
	AvatarUrl            sql.NullString `json:"avatar_url"`
	Locale               string         `json:"locale"`
	Timezone             string         `json:"timezone"`
	Description          sql.NullString `json:"description"`
	Notes                sql.NullString `json:"notes"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedAt            interface{}    `json:"deleted_at"`
	DeletedBy            interface{}    `json:"deleted_by"`
	Source               string         `json:"source"`
	AddedAt              time.Time      `json:"added_at"`
}

func (q *Queries) ListIdentityMembersForGroup(ctx context.Context, groupID int64) ([]ListIdentityMembersForGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, ListIdentityMembersForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdentityMembersForGroupRow{}
	for rows.Next() {
		var i ListIdentityMembersForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Username,
			&i.UserPrincipalName,
			&i.Email,
			&i.DisplayName,
			&i.GivenName,
			&i.Surname,
			&i.Initials,
			&i.Title,
			&i.Department,
			&i.Company,
			&i.EmployeeID,
			&i.EmployeeType,
			&i.ManagerID,
			&i.PhoneOffice,
			&i.PhoneMobile,
			&i.PhoneHome,
			&i.Fax,
			&i.Office,
			&i.StreetAddress,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.CountryCode,
			&i.HomeDirectory,
			&i.HomeDrive,
			&i.ProfilePath,
			&i.LogonScript,
			&i.AccountEnabled,
			&i.AccountLocked,
			&i.AccountExpiresAt,
			&i.PasswordHash,
			&i.PasswordLastSetAt,
			&i.PasswordNeverExpires,
			&i.MustChangePassword,
			&i.LastLogonAt,
			&i.LogonCount,
			&i.BadPasswordCount,
			&i.LastBadPasswordAt,
			&i.Role,
			&i.AvatarUrl,
			&i.Locale,
			&i.Timezone,
			&i.Description,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Source,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
