// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: identity_audit.sql

package db

import (
	"context"
	"database/sql"
)

const InsertIdentityAuditLog = `-- name: InsertIdentityAuditLog :exec

INSERT INTO identity_audit_log (
    tenant_id, identity_id, event_type, ip_address, detail
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)
`

type InsertIdentityAuditLogParams struct {
	TenantID   sql.NullInt64  `json:"tenant_id"`
	IdentityID sql.NullInt64  `json:"identity_id"`
	EventType  string         `json:"event_type"`
	IpAddress  sql.NullString `json:"ip_address"`
	Detail     sql.NullString `json:"detail"`
}

// Audit trail for authentication and identity-management events.
func (q *Queries) InsertIdentityAuditLog(ctx context.Context, arg InsertIdentityAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, InsertIdentityAuditLog,
		arg.TenantID,
		arg.IdentityID,
		arg.EventType,
		arg.IpAddress,
		arg.Detail,
	)
	return err
}

const ListIdentityAuditLogByTenant = `-- name: ListIdentityAuditLogByTenant :many
SELECT id, tenant_id, identity_id, event_type, ip_address, detail, created_at FROM identity_audit_log
WHERE tenant_id = ?1
ORDER BY created_at DESC
LIMIT ?2
`

type ListIdentityAuditLogByTenantParams struct {
	TenantID sql.NullInt64 `json:"tenant_id"`
	Limit    int64         `json:"limit"`
}

func (q *Queries) ListIdentityAuditLogByTenant(ctx context.Context, arg ListIdentityAuditLogByTenantParams) ([]IdentityAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, ListIdentityAuditLogByTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityAuditLog{}
	for rows.Next() {
		var i IdentityAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdentityID,
			&i.EventType,
			&i.IpAddress,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
