// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: identities.sql

package db

import (
	"context"
	"database/sql"
)

const CountIdentitiesByTenant = `-- name: CountIdentitiesByTenant :one
SELECT COUNT(*) FROM identities WHERE tenant_id = ?1
`

func (q *Queries) CountIdentitiesByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountIdentitiesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountIdentitiesGlobal = `-- name: CountIdentitiesGlobal :one
SELECT COUNT(*) FROM identities
`

// Used by the setup-gate middleware: "does any identity exist anywhere?"
func (q *Queries) CountIdentitiesGlobal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountIdentitiesGlobal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateIdentity = `-- name: CreateIdentity :one

INSERT INTO identities (
    tenant_id, site_id, username, user_principal_name, email, display_name,
    given_name, surname, title, department, company, employee_id,
    employee_type, manager_id, phone_office, phone_mobile, role
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10, ?11, ?12,
    ?13, ?14, ?15, ?16, ?17
) RETURNING id, tenant_id, site_id, username, user_principal_name, email, display_name, given_name, surname, initials, title, department, company, employee_id, employee_type, manager_id, phone_office, phone_mobile, phone_home, fax, office, street_address, city, state, postal_code, country, country_code, home_directory, home_drive, profile_path, logon_script, account_enabled, account_locked, account_expires_at, password_hash, password_last_set_at, password_never_expires, must_change_password, last_logon_at, logon_count, bad_password_count, last_bad_password_at, role, avatar_url, locale, timezone, description, notes, created_at, updated_at
`

type CreateIdentityParams struct {
	TenantID          int64          `json:"tenant_id"`
	SiteID            sql.NullInt64  `json:"site_id"`
	Username          string         `json:"username"`
	UserPrincipalName sql.NullString `json:"user_principal_name"`
	Email             string         `json:"email"`
	DisplayName       string         `json:"display_name"`
	GivenName         sql.NullString `json:"given_name"`
	Surname           sql.NullString `json:"surname"`
	Title             sql.NullString `json:"title"`
	Department        sql.NullString `json:"department"`
	Company           sql.NullString `json:"company"`
	EmployeeID        sql.NullString `json:"employee_id"`
	EmployeeType      sql.NullString `json:"employee_type"`
	ManagerID         sql.NullInt64  `json:"manager_id"`
	PhoneOffice       sql.NullString `json:"phone_office"`
	PhoneMobile       sql.NullString `json:"phone_mobile"`
	Role              string         `json:"role"`
}

// Identity management queries - matches the schema in
// db/schema/002_identity_ad_compat.sql. Identities are both the
// end-user directory (owner of assets) and the accounts that log into
// the console (role-gated).
func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, CreateIdentity,
		arg.TenantID,
		arg.SiteID,
		arg.Username,
		arg.UserPrincipalName,
		arg.Email,
		arg.DisplayName,
		arg.GivenName,
		arg.Surname,
		arg.Title,
		arg.Department,
		arg.Company,
		arg.EmployeeID,
		arg.EmployeeType,
		arg.ManagerID,
		arg.PhoneOffice,
		arg.PhoneMobile,
		arg.Role,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Username,
		&i.UserPrincipalName,
		&i.Email,
		&i.DisplayName,
		&i.GivenName,
		&i.Surname,
		&i.Initials,
		&i.Title,
		&i.Department,
		&i.Company,
		&i.EmployeeID,
		&i.EmployeeType,
		&i.ManagerID,
		&i.PhoneOffice,
		&i.PhoneMobile,
		&i.PhoneHome,
		&i.Fax,
		&i.Office,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.CountryCode,
		&i.HomeDirectory,
		&i.HomeDrive,
		&i.ProfilePath,
		&i.LogonScript,
		&i.AccountEnabled,
		&i.AccountLocked,
		&i.AccountExpiresAt,
		&i.PasswordHash,
		&i.PasswordLastSetAt,
		&i.PasswordNeverExpires,
		&i.MustChangePassword,
		&i.LastLogonAt,
		&i.LogonCount,
		&i.BadPasswordCount,
		&i.LastBadPasswordAt,
		&i.Role,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteIdentity = `-- name: DeleteIdentity :exec
DELETE FROM identities WHERE id = ?1
`

func (q *Queries) DeleteIdentity(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteIdentity, id)
	return err
}

const GetIdentity = `-- name: GetIdentity :one
SELECT id, tenant_id, site_id, username, user_principal_name, email, display_name, given_name, surname, initials, title, department, company, employee_id, employee_type, manager_id, phone_office, phone_mobile, phone_home, fax, office, street_address, city, state, postal_code, country, country_code, home_directory, home_drive, profile_path, logon_script, account_enabled, account_locked, account_expires_at, password_hash, password_last_set_at, password_never_expires, must_change_password, last_logon_at, logon_count, bad_password_count, last_bad_password_at, role, avatar_url, locale, timezone, description, notes, created_at, updated_at FROM identities WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetIdentity(ctx context.Context, id int64) (Identity, error) {
	row := q.db.QueryRowContext(ctx, GetIdentity, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Username,
		&i.UserPrincipalName,
		&i.Email,
		&i.DisplayName,
		&i.GivenName,
		&i.Surname,
		&i.Initials,
		&i.Title,
		&i.Department,
		&i.Company,
		&i.EmployeeID,
		&i.EmployeeType,
		&i.ManagerID,
		&i.PhoneOffice,
		&i.PhoneMobile,
		&i.PhoneHome,
		&i.Fax,
		&i.Office,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.CountryCode,
		&i.HomeDirectory,
		&i.HomeDrive,
		&i.ProfilePath,
		&i.LogonScript,
		&i.AccountEnabled,
		&i.AccountLocked,
		&i.AccountExpiresAt,
		&i.PasswordHash,
		&i.PasswordLastSetAt,
		&i.PasswordNeverExpires,
		&i.MustChangePassword,
		&i.LastLogonAt,
		&i.LogonCount,
		&i.BadPasswordCount,
		&i.LastBadPasswordAt,
		&i.Role,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetIdentityByEmail = `-- name: GetIdentityByEmail :one
SELECT id, tenant_id, site_id, username, user_principal_name, email, display_name, given_name, surname, initials, title, department, company, employee_id, employee_type, manager_id, phone_office, phone_mobile, phone_home, fax, office, street_address, city, state, postal_code, country, country_code, home_directory, home_drive, profile_path, logon_script, account_enabled, account_locked, account_expires_at, password_hash, password_last_set_at, password_never_expires, must_change_password, last_logon_at, logon_count, bad_password_count, last_bad_password_at, role, avatar_url, locale, timezone, description, notes, created_at, updated_at FROM identities
WHERE tenant_id = ?1 AND email = ?2
LIMIT 1
`

type GetIdentityByEmailParams struct {
	TenantID int64  `json:"tenant_id"`
	Email    string `json:"email"`
}

func (q *Queries) GetIdentityByEmail(ctx context.Context, arg GetIdentityByEmailParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, GetIdentityByEmail, arg.TenantID, arg.Email)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Username,
		&i.UserPrincipalName,
		&i.Email,
		&i.DisplayName,
		&i.GivenName,
		&i.Surname,
		&i.Initials,
		&i.Title,
		&i.Department,
		&i.Company,
		&i.EmployeeID,
		&i.EmployeeType,
		&i.ManagerID,
		&i.PhoneOffice,
		&i.PhoneMobile,
		&i.PhoneHome,
		&i.Fax,
		&i.Office,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.CountryCode,
		&i.HomeDirectory,
		&i.HomeDrive,
		&i.ProfilePath,
		&i.LogonScript,
		&i.AccountEnabled,
		&i.AccountLocked,
		&i.AccountExpiresAt,
		&i.PasswordHash,
		&i.PasswordLastSetAt,
		&i.PasswordNeverExpires,
		&i.MustChangePassword,
		&i.LastLogonAt,
		&i.LogonCount,
		&i.BadPasswordCount,
		&i.LastBadPasswordAt,
		&i.Role,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetIdentityByEmailGlobal = `-- name: GetIdentityByEmailGlobal :many
SELECT id, tenant_id, site_id, username, user_principal_name, email, display_name, given_name, surname, initials, title, department, company, employee_id, employee_type, manager_id, phone_office, phone_mobile, phone_home, fax, office, street_address, city, state, postal_code, country, country_code, home_directory, home_drive, profile_path, logon_script, account_enabled, account_locked, account_expires_at, password_hash, password_last_set_at, password_never_expires, must_change_password, last_logon_at, logon_count, bad_password_count, last_bad_password_at, role, avatar_url, locale, timezone, description, notes, created_at, updated_at FROM identities WHERE email = ?1
`

// Used at login: the user only enters an email, not a tenant, so this
// resolves across all tenants. Returns 0, 1, or (in the rare case two
// tenants share an email) more than 1 row - callers MUST check the
// length and treat >1 as an ambiguous-account error, never just take
// the first result.
func (q *Queries) GetIdentityByEmailGlobal(ctx context.Context, email string) ([]Identity, error) {
	rows, err := q.db.QueryContext(ctx, GetIdentityByEmailGlobal, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Username,
			&i.UserPrincipalName,
			&i.Email,
			&i.DisplayName,
			&i.GivenName,
			&i.Surname,
			&i.Initials,
			&i.Title,
			&i.Department,
			&i.Company,
			&i.EmployeeID,
			&i.EmployeeType,
			&i.ManagerID,
			&i.PhoneOffice,
			&i.PhoneMobile,
			&i.PhoneHome,
			&i.Fax,
			&i.Office,
			&i.StreetAddress,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.CountryCode,
			&i.HomeDirectory,
			&i.HomeDrive,
			&i.ProfilePath,
			&i.LogonScript,
			&i.AccountEnabled,
			&i.AccountLocked,
			&i.AccountExpiresAt,
			&i.PasswordHash,
			&i.PasswordLastSetAt,
			&i.PasswordNeverExpires,
			&i.MustChangePassword,
			&i.LastLogonAt,
			&i.LogonCount,
			&i.BadPasswordCount,
			&i.LastBadPasswordAt,
			&i.Role,
			&i.AvatarUrl,
			&i.Locale,
			&i.Timezone,
			&i.Description,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListIdentitiesByTenant = `-- name: ListIdentitiesByTenant :many
SELECT id, tenant_id, site_id, username, user_principal_name, email, display_name, given_name, surname, initials, title, department, company, employee_id, employee_type, manager_id, phone_office, phone_mobile, phone_home, fax, office, street_address, city, state, postal_code, country, country_code, home_directory, home_drive, profile_path, logon_script, account_enabled, account_locked, account_expires_at, password_hash, password_last_set_at, password_never_expires, must_change_password, last_logon_at, logon_count, bad_password_count, last_bad_password_at, role, avatar_url, locale, timezone, description, notes, created_at, updated_at FROM identities
WHERE tenant_id = ?1
ORDER BY display_name
LIMIT ?3 OFFSET ?2
`

type ListIdentitiesByTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Offset   int64 `json:"offset"`
	Limit    int64 `json:"limit"`
}

func (q *Queries) ListIdentitiesByTenant(ctx context.Context, arg ListIdentitiesByTenantParams) ([]Identity, error) {
	rows, err := q.db.QueryContext(ctx, ListIdentitiesByTenant, arg.TenantID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Username,
			&i.UserPrincipalName,
			&i.Email,
			&i.DisplayName,
			&i.GivenName,
			&i.Surname,
			&i.Initials,
			&i.Title,
			&i.Department,
			&i.Company,
			&i.EmployeeID,
			&i.EmployeeType,
			&i.ManagerID,
			&i.PhoneOffice,
			&i.PhoneMobile,
			&i.PhoneHome,
			&i.Fax,
			&i.Office,
			&i.StreetAddress,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.CountryCode,
			&i.HomeDirectory,
			&i.HomeDrive,
			&i.ProfilePath,
			&i.LogonScript,
			&i.AccountEnabled,
			&i.AccountLocked,
			&i.AccountExpiresAt,
			&i.PasswordHash,
			&i.PasswordLastSetAt,
			&i.PasswordNeverExpires,
			&i.MustChangePassword,
			&i.LastLogonAt,
			&i.LogonCount,
			&i.BadPasswordCount,
			&i.LastBadPasswordAt,
			&i.Role,
			&i.AvatarUrl,
			&i.Locale,
			&i.Timezone,
			&i.Description,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const LockIdentityIfThresholdExceeded = `-- name: LockIdentityIfThresholdExceeded :exec
UPDATE identities SET account_locked = TRUE
WHERE id = ?1 AND bad_password_count >= ?2
`

type LockIdentityIfThresholdExceededParams struct {
	ID        int64 `json:"id"`
	Threshold int64 `json:"threshold"`
}

func (q *Queries) LockIdentityIfThresholdExceeded(ctx context.Context, arg LockIdentityIfThresholdExceededParams) error {
	_, err := q.db.ExecContext(ctx, LockIdentityIfThresholdExceeded, arg.ID, arg.Threshold)
	return err
}

const RecordLoginFailure = `-- name: RecordLoginFailure :exec
UPDATE identities SET
    bad_password_count = bad_password_count + 1,
    last_bad_password_at = CURRENT_TIMESTAMP
WHERE id = ?1
`

func (q *Queries) RecordLoginFailure(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, RecordLoginFailure, id)
	return err
}

const RecordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE identities SET
    last_logon_at = CURRENT_TIMESTAMP,
    logon_count = logon_count + 1,
    bad_password_count = 0,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
`

func (q *Queries) RecordLoginSuccess(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, RecordLoginSuccess, id)
	return err
}

const SearchIdentities = `-- name: SearchIdentities :many
SELECT id, tenant_id, site_id, username, user_principal_name, email, display_name, given_name, surname, initials, title, department, company, employee_id, employee_type, manager_id, phone_office, phone_mobile, phone_home, fax, office, street_address, city, state, postal_code, country, country_code, home_directory, home_drive, profile_path, logon_script, account_enabled, account_locked, account_expires_at, password_hash, password_last_set_at, password_never_expires, must_change_password, last_logon_at, logon_count, bad_password_count, last_bad_password_at, role, avatar_url, locale, timezone, description, notes, created_at, updated_at FROM identities
WHERE tenant_id = ?1
  AND (display_name LIKE '%' || ?2 || '%'
       OR email LIKE '%' || ?2 || '%'
       OR username LIKE '%' || ?2 || '%'
       OR department LIKE '%' || ?2 || '%')
ORDER BY display_name
LIMIT ?3
`

type SearchIdentitiesParams struct {
	TenantID int64          `json:"tenant_id"`
	Search   sql.NullString `json:"search"`
	Limit    int64          `json:"limit"`
}

func (q *Queries) SearchIdentities(ctx context.Context, arg SearchIdentitiesParams) ([]Identity, error) {
	rows, err := q.db.QueryContext(ctx, SearchIdentities, arg.TenantID, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Username,
			&i.UserPrincipalName,
			&i.Email,
			&i.DisplayName,
			&i.GivenName,
			&i.Surname,
			&i.Initials,
			&i.Title,
			&i.Department,
			&i.Company,
			&i.EmployeeID,
			&i.EmployeeType,
			&i.ManagerID,
			&i.PhoneOffice,
			&i.PhoneMobile,
			&i.PhoneHome,
			&i.Fax,
			&i.Office,
			&i.StreetAddress,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.CountryCode,
			&i.HomeDirectory,
			&i.HomeDrive,
			&i.ProfilePath,
			&i.LogonScript,
			&i.AccountEnabled,
			&i.AccountLocked,
			&i.AccountExpiresAt,
			&i.PasswordHash,
			&i.PasswordLastSetAt,
			&i.PasswordNeverExpires,
			&i.MustChangePassword,
			&i.LastLogonAt,
			&i.LogonCount,
			&i.BadPasswordCount,
			&i.LastBadPasswordAt,
			&i.Role,
			&i.AvatarUrl,
			&i.Locale,
			&i.Timezone,
			&i.Description,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetIdentityEnabled = `-- name: SetIdentityEnabled :exec
UPDATE identities SET account_enabled = ?1, updated_at = CURRENT_TIMESTAMP WHERE id = ?2
`

type SetIdentityEnabledParams struct {
	AccountEnabled bool  `json:"account_enabled"`
	ID             int64 `json:"id"`
}

func (q *Queries) SetIdentityEnabled(ctx context.Context, arg SetIdentityEnabledParams) error {
	_, err := q.db.ExecContext(ctx, SetIdentityEnabled, arg.AccountEnabled, arg.ID)
	return err
}

const SetIdentityLocked = `-- name: SetIdentityLocked :exec
UPDATE identities SET account_locked = ?1, updated_at = CURRENT_TIMESTAMP WHERE id = ?2
`

type SetIdentityLockedParams struct {
	AccountLocked bool  `json:"account_locked"`
	ID            int64 `json:"id"`
}

func (q *Queries) SetIdentityLocked(ctx context.Context, arg SetIdentityLockedParams) error {
	_, err := q.db.ExecContext(ctx, SetIdentityLocked, arg.AccountLocked, arg.ID)
	return err
}

const SetIdentityPasswordHash = `-- name: SetIdentityPasswordHash :exec
UPDATE identities SET
    password_hash = ?1,
    password_last_set_at = CURRENT_TIMESTAMP,
    must_change_password = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type SetIdentityPasswordHashParams struct {
	PasswordHash sql.NullString `json:"password_hash"`
	ID           int64          `json:"id"`
}

func (q *Queries) SetIdentityPasswordHash(ctx context.Context, arg SetIdentityPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, SetIdentityPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const UpdateIdentity = `-- name: UpdateIdentity :one
UPDATE identities SET
    display_name = ?1,
    given_name = ?2,
    surname = ?3,
    initials = ?4,
    email = ?5,
    title = ?6,
    department = ?7,
    company = ?8,
    employee_id = ?9,
    employee_type = ?10,
    manager_id = ?11,
    phone_office = ?12,
    phone_mobile = ?13,
    phone_home = ?14,
    fax = ?15,
    office = ?16,
    street_address = ?17,
    city = ?18,
    state = ?19,
    postal_code = ?20,
    country = ?21,
    country_code = ?22,
    home_directory = ?23,
    home_drive = ?24,
    profile_path = ?25,
    logon_script = ?26,
    account_enabled = ?27,
    account_locked = ?28,
    account_expires_at = ?29,
    password_never_expires = ?30,
    must_change_password = ?31,
    locale = ?32,
    timezone = ?33,
    description = ?34,
    notes = ?35,
    site_id = ?36,
    avatar_url = ?37,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?38
RETURNING id, tenant_id, site_id, username, user_principal_name, email, display_name, given_name, surname, initials, title, department, company, employee_id, employee_type, manager_id, phone_office, phone_mobile, phone_home, fax, office, street_address, city, state, postal_code, country, country_code, home_directory, home_drive, profile_path, logon_script, account_enabled, account_locked, account_expires_at, password_hash, password_last_set_at, password_never_expires, must_change_password, last_logon_at, logon_count, bad_password_count, last_bad_password_at, role, avatar_url, locale, timezone, description, notes, created_at, updated_at
`

type UpdateIdentityParams struct {
	DisplayName          string         `json:"display_name"`
	GivenName            sql.NullString `json:"given_name"`
	Surname              sql.NullString `json:"surname"`
	Initials             sql.NullString `json:"initials"`
	Email                string         `json:"email"`
	Title                sql.NullString `json:"title"`
	Department           sql.NullString `json:"department"`
	Company              sql.NullString `json:"company"`
	EmployeeID           sql.NullString `json:"employee_id"`
	EmployeeType         sql.NullString `json:"employee_type"`
	ManagerID            sql.NullInt64  `json:"manager_id"`
	PhoneOffice          sql.NullString `json:"phone_office"`
	PhoneMobile          sql.NullString `json:"phone_mobile"`
	PhoneHome            sql.NullString `json:"phone_home"`
	Fax                  sql.NullString `json:"fax"`
	Office               sql.NullString `json:"office"`
	StreetAddress        sql.NullString `json:"street_address"`
	City                 sql.NullString `json:"city"`
	State                sql.NullString `json:"state"`
	PostalCode           sql.NullString `json:"postal_code"`
	Country              sql.NullString `json:"country"`
	CountryCode          sql.NullString `json:"country_code"`
	HomeDirectory        sql.NullString `json:"home_directory"`
	HomeDrive            sql.NullString `json:"home_drive"`
	ProfilePath          sql.NullString `json:"profile_path"`
	LogonScript          sql.NullString `json:"logon_script"`
	AccountEnabled       bool           `json:"account_enabled"`
	AccountLocked        bool           `json:"account_locked"`
	AccountExpiresAt     sql.NullTime   `json:"account_expires_at"`
	PasswordNeverExpires bool           `json:"password_never_expires"`
	MustChangePassword   bool           `json:"must_change_password"`
	Locale               string         `json:"locale"`
	Timezone             string         `json:"timezone"`
	Description          sql.NullString `json:"description"`
	Notes                sql.NullString `json:"notes"`
	SiteID               sql.NullInt64  `json:"site_id"`
	AvatarUrl            sql.NullString `json:"avatar_url"`
	ID                   int64          `json:"id"`
}

// Writes every field the Users UI (detail-page editor + inline-edit field
// API, see console/handlers/field_api.go) can set on an identity. Kept as
// one wide UPDATE (rather than narrow SetIdentityX statements per field)
// so IdentityService.Update stays the single write path callers use --
// ID/AccountEnabled/AccountLocked/Role/password fields have their own
// narrower statements below for flows that must not clobber unrelated
// columns.
func (q *Queries) UpdateIdentity(ctx context.Context, arg UpdateIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, UpdateIdentity,
		arg.DisplayName,
		arg.GivenName,
		arg.Surname,
		arg.Initials,
		arg.Email,
		arg.Title,
		arg.Department,
		arg.Company,
		arg.EmployeeID,
		arg.EmployeeType,
		arg.ManagerID,
		arg.PhoneOffice,
		arg.PhoneMobile,
		arg.PhoneHome,
		arg.Fax,
		arg.Office,
		arg.StreetAddress,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.CountryCode,
		arg.HomeDirectory,
		arg.HomeDrive,
		arg.ProfilePath,
		arg.LogonScript,
		arg.AccountEnabled,
		arg.AccountLocked,
		arg.AccountExpiresAt,
		arg.PasswordNeverExpires,
		arg.MustChangePassword,
		arg.Locale,
		arg.Timezone,
		arg.Description,
		arg.Notes,
		arg.SiteID,
		arg.AvatarUrl,
		arg.ID,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Username,
		&i.UserPrincipalName,
		&i.Email,
		&i.DisplayName,
		&i.GivenName,
		&i.Surname,
		&i.Initials,
		&i.Title,
		&i.Department,
		&i.Company,
		&i.EmployeeID,
		&i.EmployeeType,
		&i.ManagerID,
		&i.PhoneOffice,
		&i.PhoneMobile,
		&i.PhoneHome,
		&i.Fax,
		&i.Office,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.CountryCode,
		&i.HomeDirectory,
		&i.HomeDrive,
		&i.ProfilePath,
		&i.LogonScript,
		&i.AccountEnabled,
		&i.AccountLocked,
		&i.AccountExpiresAt,
		&i.PasswordHash,
		&i.PasswordLastSetAt,
		&i.PasswordNeverExpires,
		&i.MustChangePassword,
		&i.LastLogonAt,
		&i.LogonCount,
		&i.BadPasswordCount,
		&i.LastBadPasswordAt,
		&i.Role,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateIdentityRole = `-- name: UpdateIdentityRole :exec
UPDATE identities SET role = ?1, updated_at = CURRENT_TIMESTAMP WHERE id = ?2
`

type UpdateIdentityRoleParams struct {
	Role string `json:"role"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateIdentityRole(ctx context.Context, arg UpdateIdentityRoleParams) error {
	_, err := q.db.ExecContext(ctx, UpdateIdentityRole, arg.Role, arg.ID)
	return err
}
