// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: installed_software.sql

package db

import (
	"context"
	"database/sql"
)

const CreateInstalledSoftware = `-- name: CreateInstalledSoftware :one

INSERT INTO installed_software (asset_id, name, version, publisher, pkg_type, installed_at, size_mb)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, asset_id, name, version, publisher, pkg_type, installed_at, size_mb, created_at
`

type CreateInstalledSoftwareParams struct {
	AssetID     int64          `json:"asset_id"`
	Name        string         `json:"name"`
	Version     sql.NullString `json:"version"`
	Publisher   sql.NullString `json:"publisher"`
	PkgType     string         `json:"pkg_type"`
	InstalledAt sql.NullTime   `json:"installed_at"`
	SizeMb      sql.NullInt64  `json:"size_mb"`
}

// Installed software queries - per asset software inventory backed by
// the installed_software table in db/schema/003_roles_software_logs.sql.
func (q *Queries) CreateInstalledSoftware(ctx context.Context, arg CreateInstalledSoftwareParams) (InstalledSoftware, error) {
	row := q.db.QueryRowContext(ctx, CreateInstalledSoftware,
		arg.AssetID,
		arg.Name,
		arg.Version,
		arg.Publisher,
		arg.PkgType,
		arg.InstalledAt,
		arg.SizeMb,
	)
	var i InstalledSoftware
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Name,
		&i.Version,
		&i.Publisher,
		&i.PkgType,
		&i.InstalledAt,
		&i.SizeMb,
		&i.CreatedAt,
	)
	return i, err
}

const ListSoftwareForAsset = `-- name: ListSoftwareForAsset :many
SELECT id, asset_id, name, version, publisher, pkg_type, installed_at, size_mb, created_at FROM installed_software
WHERE asset_id = ?1
ORDER BY name
`

func (q *Queries) ListSoftwareForAsset(ctx context.Context, assetID int64) ([]InstalledSoftware, error) {
	rows, err := q.db.QueryContext(ctx, ListSoftwareForAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstalledSoftware{}
	for rows.Next() {
		var i InstalledSoftware
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.Name,
			&i.Version,
			&i.Publisher,
			&i.PkgType,
			&i.InstalledAt,
			&i.SizeMb,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
