// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type ActivityLog struct {
	ID              int64          `json:"id"`
	TenantID        int64          `json:"tenant_id"`
	EntityType      string         `json:"entity_type"`
	EntityID        int64          `json:"entity_id"`
	Event           string         `json:"event"`
	Detail          sql.NullString `json:"detail"`
	ActorIdentityID sql.NullInt64  `json:"actor_identity_id"`
	CreatedAt       time.Time      `json:"created_at"`
}

type Asset struct {
	ID                  int64           `json:"id"`
	Uuid                string          `json:"uuid"`
	TenantID            int64           `json:"tenant_id"`
	SiteID              sql.NullInt64   `json:"site_id"`
	Subtype             string          `json:"subtype"`
	SubtypePayload      string          `json:"subtype_payload"`
	EnrollmentState     string          `json:"enrollment_state"`
	EnrolledAt          sql.NullTime    `json:"enrolled_at"`
	LastSeenAt          sql.NullTime    `json:"last_seen_at"`
	AgentVersion        sql.NullString  `json:"agent_version"`
	Labels              sql.NullString  `json:"labels"`
	LifecycleState      sql.NullString  `json:"lifecycle_state"`
	Location            sql.NullString  `json:"location"`
	OwnerIdentityID     sql.NullInt64   `json:"owner_identity_id"`
	Vendor              sql.NullString  `json:"vendor"`
	PurchaseDate        sql.NullTime    `json:"purchase_date"`
	PurchasePrice       sql.NullFloat64 `json:"purchase_price"`
	WarrantyExpiresAt   sql.NullTime    `json:"warranty_expires_at"`
	HumanID             sql.NullString  `json:"human_id"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	Description         sql.NullString  `json:"description"`
	ManagedByIdentityID sql.NullInt64   `json:"managed_by_identity_id"`
	DeletedAt           interface{}     `json:"deleted_at"`
	DeletedBy           interface{}     `json:"deleted_by"`
}

type AssetLink struct {
	ID          int64          `json:"id"`
	TenantID    int64          `json:"tenant_id"`
	FromAssetID int64          `json:"from_asset_id"`
	ToAssetID   int64          `json:"to_asset_id"`
	Relation    string         `json:"relation"`
	Metadata    sql.NullString `json:"metadata"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ConfigurationGroup struct {
	ID          int64          `json:"id"`
	TenantID    int64          `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Scope       string         `json:"scope"`
	Disabled    bool           `json:"disabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   interface{}    `json:"deleted_at"`
	DeletedBy   interface{}    `json:"deleted_by"`
}

type ConfigurationGroupAssignment struct {
	ID                   int64     `json:"id"`
	ConfigurationGroupID int64     `json:"configuration_group_id"`
	TargetType           string    `json:"target_type"`
	TargetID             int64     `json:"target_id"`
	Priority             int64     `json:"priority"`
	Enforced             bool      `json:"enforced"`
	CreatedAt            time.Time `json:"created_at"`
}

type ConfigurationGroupBinding struct {
	ID                   int64          `json:"id"`
	ConfigurationGroupID int64          `json:"configuration_group_id"`
	PolicyUrn            string         `json:"policy_urn"`
	State                string         `json:"state"`
	ParameterValues      sql.NullString `json:"parameter_values"`
	ModuleID             sql.NullInt64  `json:"module_id"`
	ModuleVersionPinned  sql.NullString `json:"module_version_pinned"`
	Disabled             bool           `json:"disabled"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type CustomPolicy struct {
	ID               int64          `json:"id"`
	TenantID         int64          `json:"tenant_id"`
	PolicyUrn        string         `json:"policy_urn"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	Scope            string         `json:"scope"`
	CategoryPath     string         `json:"category_path"`
	ParametersSchema sql.NullString `json:"parameters_schema"`
	CreatedAt        time.Time      `json:"created_at"`
}

type DependencyGroup struct {
	ID          int64          `json:"id"`
	TenantID    int64          `json:"tenant_id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsBuiltin   bool           `json:"is_builtin"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	MatchMode   string         `json:"match_mode"`
	DeletedAt   interface{}    `json:"deleted_at"`
	DeletedBy   interface{}    `json:"deleted_by"`
}

type DependencyGroupCondition struct {
	ID           int64  `json:"id"`
	GroupID      int64  `json:"group_id"`
	ParamPath    string `json:"param_path"`
	Operator     string `json:"operator"`
	ValueJson    string `json:"value_json"`
	Seq          int64  `json:"seq"`
	Kind         string `json:"kind"`
	ScriptSource string `json:"script_source"`
	ScriptExpect string `json:"script_expect"`
	ScriptRef    string `json:"script_ref"`
}

type Group struct {
	ID             int64         `json:"id"`
	TenantID       int64         `json:"tenant_id"`
	SiteID         sql.NullInt64 `json:"site_id"`
	Name           string        `json:"name"`
	Slug           string        `json:"slug"`
	CreatedAt      time.Time     `json:"created_at"`
	GroupCategory  string        `json:"group_category"`
	GroupScope     string        `json:"group_scope"`
	Description    string        `json:"description"`
	MemberKind     string        `json:"member_kind"`
	Membership     string        `json:"membership"`
	RulesMatchMode string        `json:"rules_match_mode"`
	DeletedAt      interface{}   `json:"deleted_at"`
	DeletedBy      interface{}   `json:"deleted_by"`
}

type GroupMembership struct {
	ID         int64         `json:"id"`
	GroupID    int64         `json:"group_id"`
	AssetID    sql.NullInt64 `json:"asset_id"`
	IdentityID sql.NullInt64 `json:"identity_id"`
	CreatedAt  time.Time     `json:"created_at"`
	Source     string        `json:"source"`
}

type GroupMembershipRule struct {
	ID           int64  `json:"id"`
	GroupID      int64  `json:"group_id"`
	Kind         string `json:"kind"`
	ParamPath    string `json:"param_path"`
	Operator     string `json:"operator"`
	ValueJson    string `json:"value_json"`
	ScriptSource string `json:"script_source"`
	ScriptExpect string `json:"script_expect"`
	Seq          int64  `json:"seq"`
	ScriptRef    string `json:"script_ref"`
}

type GroupRole struct {
	ID         int64         `json:"id"`
	GroupID    int64         `json:"group_id"`
	RoleID     int64         `json:"role_id"`
	AssignedAt time.Time     `json:"assigned_at"`
	AssignedBy sql.NullInt64 `json:"assigned_by"`
}

type Identity struct {
	ID                   int64          `json:"id"`
	TenantID             int64          `json:"tenant_id"`
	SiteID               sql.NullInt64  `json:"site_id"`
	Username             string         `json:"username"`
	UserPrincipalName    sql.NullString `json:"user_principal_name"`
	Email                string         `json:"email"`
	DisplayName          string         `json:"display_name"`
	GivenName            sql.NullString `json:"given_name"`
	Surname              sql.NullString `json:"surname"`
	Initials             sql.NullString `json:"initials"`
	Title                sql.NullString `json:"title"`
	Department           sql.NullString `json:"department"`
	Company              sql.NullString `json:"company"`
	EmployeeID           sql.NullString `json:"employee_id"`
	EmployeeType         sql.NullString `json:"employee_type"`
	ManagerID            sql.NullInt64  `json:"manager_id"`
	PhoneOffice          sql.NullString `json:"phone_office"`
	PhoneMobile          sql.NullString `json:"phone_mobile"`
	PhoneHome            sql.NullString `json:"phone_home"`
	Fax                  sql.NullString `json:"fax"`
	Office               sql.NullString `json:"office"`
	StreetAddress        sql.NullString `json:"street_address"`
	City                 sql.NullString `json:"city"`
	State                sql.NullString `json:"state"`
	PostalCode           sql.NullString `json:"postal_code"`
	Country              sql.NullString `json:"country"`
	CountryCode          sql.NullString `json:"country_code"`
	HomeDirectory        sql.NullString `json:"home_directory"`
	HomeDrive            sql.NullString `json:"home_drive"`
	ProfilePath          sql.NullString `json:"profile_path"`
	LogonScript          sql.NullString `json:"logon_script"`
	AccountEnabled       bool           `json:"account_enabled"`
	AccountLocked        bool           `json:"account_locked"`
	AccountExpiresAt     sql.NullTime   `json:"account_expires_at"`
	PasswordHash         sql.NullString `json:"password_hash"`
	PasswordLastSetAt    sql.NullTime   `json:"password_last_set_at"`
	PasswordNeverExpires bool           `json:"password_never_expires"`
	MustChangePassword   bool           `json:"must_change_password"`
	LastLogonAt          sql.NullTime   `json:"last_logon_at"`
	LogonCount           int64          `json:"logon_count"`
	BadPasswordCount     int64          `json:"bad_password_count"`
	LastBadPasswordAt    sql.NullTime   `json:"last_bad_password_at"`
	Role                 string         `json:"role"`
	AvatarUrl            sql.NullString `json:"avatar_url"`
	Locale               string         `json:"locale"`
	Timezone             string         `json:"timezone"`
	Description          sql.NullString `json:"description"`
	Notes                sql.NullString `json:"notes"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedAt            interface{}    `json:"deleted_at"`
	DeletedBy            interface{}    `json:"deleted_by"`
}

type IdentityAuditLog struct {
	ID         int64          `json:"id"`
	TenantID   sql.NullInt64  `json:"tenant_id"`
	IdentityID sql.NullInt64  `json:"identity_id"`
	EventType  string         `json:"event_type"`
	IpAddress  sql.NullString `json:"ip_address"`
	Detail     sql.NullString `json:"detail"`
	CreatedAt  time.Time      `json:"created_at"`
}

type IdentityRole struct {
	ID         int64         `json:"id"`
	IdentityID int64         `json:"identity_id"`
	RoleID     int64         `json:"role_id"`
	AssignedAt time.Time     `json:"assigned_at"`
	AssignedBy sql.NullInt64 `json:"assigned_by"`
}

type IdentitySession struct {
	ID             int64          `json:"id"`
	IdentityID     int64          `json:"identity_id"`
	TokenHash      string         `json:"token_hash"`
	ActiveTenantID sql.NullInt64  `json:"active_tenant_id"`
	IpAddress      sql.NullString `json:"ip_address"`
	UserAgent      sql.NullString `json:"user_agent"`
	CreatedAt      time.Time      `json:"created_at"`
	ExpiresAt      time.Time      `json:"expires_at"`
	RevokedAt      sql.NullTime   `json:"revoked_at"`
}

type InstalledSoftware struct {
	ID          int64          `json:"id"`
	AssetID     int64          `json:"asset_id"`
	Name        string         `json:"name"`
	Version     sql.NullString `json:"version"`
	Publisher   sql.NullString `json:"publisher"`
	PkgType     string         `json:"pkg_type"`
	InstalledAt sql.NullTime   `json:"installed_at"`
	SizeMb      sql.NullInt64  `json:"size_mb"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ModuleDependencyLink struct {
	ID       int64  `json:"id"`
	TenantID int64  `json:"tenant_id"`
	ModuleID string `json:"module_id"`
	GroupID  int64  `json:"group_id"`
	Role     string `json:"role"`
}

type ModuleGrant struct {
	ID          int64     `json:"id"`
	ModuleID    int64     `json:"module_id"`
	SubjectType string    `json:"subject_type"`
	SubjectID   int64     `json:"subject_id"`
	Level       string    `json:"level"`
	CreatedAt   time.Time `json:"created_at"`
}

type ModuleInstallation struct {
	ID                  int64          `json:"id"`
	AssetID             int64          `json:"asset_id"`
	ModuleID            int64          `json:"module_id"`
	ModuleVersionPinned string         `json:"module_version_pinned"`
	State               string         `json:"state"`
	AppliedAt           sql.NullTime   `json:"applied_at"`
	LastValidatedAt     sql.NullTime   `json:"last_validated_at"`
	LastReport          sql.NullString `json:"last_report"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type ModuleInstallationDependency struct {
	ID                      int64     `json:"id"`
	InstallationID          int64     `json:"installation_id"`
	DependsOnInstallationID int64     `json:"depends_on_installation_id"`
	CreatedAt               time.Time `json:"created_at"`
}

type ModuleVersionCondition struct {
	ID           int64  `json:"id"`
	VersionID    int64  `json:"version_id"`
	Kind         string `json:"kind"`
	ParamPath    string `json:"param_path"`
	Operator     string `json:"operator"`
	ValueJson    string `json:"value_json"`
	ScriptSource string `json:"script_source"`
	ScriptRef    string `json:"script_ref"`
	ScriptExpect string `json:"script_expect"`
	Seq          int64  `json:"seq"`
}

type PolicyModule struct {
	ID              int64          `json:"id"`
	ModuleUrn       string         `json:"module_urn"`
	TenantID        sql.NullInt64  `json:"tenant_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	IsBundled       bool           `json:"is_bundled"`
	CreatedAt       time.Time      `json:"created_at"`
	OwnerIdentityID sql.NullInt64  `json:"owner_identity_id"`
	DeletedAt       interface{}    `json:"deleted_at"`
	DeletedBy       interface{}    `json:"deleted_by"`
	Origin          string         `json:"origin"`
}

type PolicyModuleAction struct {
	ID        int64  `json:"id"`
	VersionID int64  `json:"version_id"`
	ActionKey string `json:"action_key"`
	Label     string `json:"label"`
	Kind      string `json:"kind"`
	Value     string `json:"value"`
	Origin    string `json:"origin"`
	Seq       int64  `json:"seq"`
}

type PolicyModuleScript struct {
	ID        int64  `json:"id"`
	VersionID int64  `json:"version_id"`
	Name      string `json:"name"`
	Language  string `json:"language"`
	Source    string `json:"source"`
	Origin    string `json:"origin"`
	Seq       int64  `json:"seq"`
}

type PolicyModuleVersion struct {
	ID                  int64          `json:"id"`
	ModuleID            int64          `json:"module_id"`
	Version             string         `json:"version"`
	State               string         `json:"state"`
	TargetOs            string         `json:"target_os"`
	Scope               string         `json:"scope"`
	Satisfies           string         `json:"satisfies"`
	ParametersSchema    sql.NullString `json:"parameters_schema"`
	DependsOn           sql.NullString `json:"depends_on"`
	Conflicts           sql.NullString `json:"conflicts"`
	SandboxProfile      string         `json:"sandbox_profile"`
	ReportSchema        string         `json:"report_schema"`
	ManifestYaml        string         `json:"manifest_yaml"`
	SignatureAlgo       sql.NullString `json:"signature_algo"`
	SignatureData       sql.NullString `json:"signature_data"`
	SignedBy            sql.NullString `json:"signed_by"`
	PublishedAt         sql.NullTime   `json:"published_at"`
	PublishedBy         sql.NullInt64  `json:"published_by"`
	SupersededByVersion sql.NullString `json:"superseded_by_version"`
	CreatedAt           time.Time      `json:"created_at"`
	ConditionsMatchMode string         `json:"conditions_match_mode"`
}

type RetentionSetting struct {
	EntityKind     string      `json:"entity_kind"`
	PurgeAfterDays interface{} `json:"purge_after_days"`
	Mode           string      `json:"mode"`
	UpdatedAt      time.Time   `json:"updated_at"`
	UpdatedBy      interface{} `json:"updated_by"`
}

type Role struct {
	ID           int64          `json:"id"`
	TenantID     int64          `json:"tenant_id"`
	Slug         string         `json:"slug"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	IsBuiltin    bool           `json:"is_builtin"`
	TemplateSlug sql.NullString `json:"template_slug"`
	Permissions  string         `json:"permissions"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ParentRoleID sql.NullInt64  `json:"parent_role_id"`
}

type Site struct {
	ID        int64     `json:"id"`
	TenantID  int64     `json:"tenant_id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type Tenant struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}
