// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: module_grants.sql

package db

import (
	"context"
)

const DeleteModuleGrant = `-- name: DeleteModuleGrant :exec
DELETE FROM module_grants
WHERE module_id = ?1
  AND subject_type = ?2
  AND subject_id = ?3
`

type DeleteModuleGrantParams struct {
	ModuleID    int64  `json:"module_id"`
	SubjectType string `json:"subject_type"`
	SubjectID   int64  `json:"subject_id"`
}

func (q *Queries) DeleteModuleGrant(ctx context.Context, arg DeleteModuleGrantParams) error {
	_, err := q.db.ExecContext(ctx, DeleteModuleGrant, arg.ModuleID, arg.SubjectType, arg.SubjectID)
	return err
}

const ListGrantsForModule = `-- name: ListGrantsForModule :many

SELECT id, module_id, subject_type, subject_id, level, created_at FROM module_grants
WHERE module_id = ?1
ORDER BY subject_type, subject_id
`

// Module grants queries.
//
// module_grants is the single, shared per-module access-grant table for
// both policy modules and the future Scripts feature (a script is an
// unpackaged module row in policy_modules) -- see db/schema/007's header
// comment. subject_type/level are validated in Go, not the schema; see
// pkg/authz/modules.go for the decision logic these rows feed.
func (q *Queries) ListGrantsForModule(ctx context.Context, moduleID int64) ([]ModuleGrant, error) {
	rows, err := q.db.QueryContext(ctx, ListGrantsForModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModuleGrant{}
	for rows.Next() {
		var i ModuleGrant
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertModuleGrant = `-- name: UpsertModuleGrant :one
INSERT INTO module_grants (
    module_id,
    subject_type,
    subject_id,
    level
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
ON CONFLICT(module_id, subject_type, subject_id)
DO UPDATE SET level = excluded.level
RETURNING id, module_id, subject_type, subject_id, level, created_at
`

type UpsertModuleGrantParams struct {
	ModuleID    int64  `json:"module_id"`
	SubjectType string `json:"subject_type"`
	SubjectID   int64  `json:"subject_id"`
	Level       string `json:"level"`
}

// Creates a grant, or -- if this (module, subject) pair already has a
// grant row -- updates it in place to the new level, so a subject never
// ends up with more than one grant per module.
func (q *Queries) UpsertModuleGrant(ctx context.Context, arg UpsertModuleGrantParams) (ModuleGrant, error) {
	row := q.db.QueryRowContext(ctx, UpsertModuleGrant,
		arg.ModuleID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Level,
	)
	var i ModuleGrant
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}
