// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: module_installations.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CountInstallationsByAsset = `-- name: CountInstallationsByAsset :one
SELECT COUNT(*) FROM module_installations WHERE asset_id = ?1
`

func (q *Queries) CountInstallationsByAsset(ctx context.Context, assetID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountInstallationsByAsset, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountInstallationsByModule = `-- name: CountInstallationsByModule :one
SELECT COUNT(*) FROM module_installations WHERE module_id = ?1
`

func (q *Queries) CountInstallationsByModule(ctx context.Context, moduleID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountInstallationsByModule, moduleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountInstallationsByState = `-- name: CountInstallationsByState :one
SELECT COUNT(*) FROM module_installations WHERE state = ?1
`

func (q *Queries) CountInstallationsByState(ctx context.Context, state string) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountInstallationsByState, state)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateInstallationDependency = `-- name: CreateInstallationDependency :one

INSERT INTO module_installation_dependencies (
    installation_id,
    depends_on_installation_id
) VALUES (
    ?1,
    ?2
) RETURNING id, installation_id, depends_on_installation_id, created_at
`

type CreateInstallationDependencyParams struct {
	InstallationID          int64 `json:"installation_id"`
	DependsOnInstallationID int64 `json:"depends_on_installation_id"`
}

// ============================================================================
// Module Installation Dependencies
// ============================================================================
func (q *Queries) CreateInstallationDependency(ctx context.Context, arg CreateInstallationDependencyParams) (ModuleInstallationDependency, error) {
	row := q.db.QueryRowContext(ctx, CreateInstallationDependency, arg.InstallationID, arg.DependsOnInstallationID)
	var i ModuleInstallationDependency
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.DependsOnInstallationID,
		&i.CreatedAt,
	)
	return i, err
}

const CreateModuleInstallation = `-- name: CreateModuleInstallation :one

INSERT INTO module_installations (
    asset_id,
    module_id,
    module_version_pinned,
    state
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
) RETURNING id, asset_id, module_id, module_version_pinned, state, applied_at, last_validated_at, last_report, created_at, updated_at
`

type CreateModuleInstallationParams struct {
	AssetID             int64  `json:"asset_id"`
	ModuleID            int64  `json:"module_id"`
	ModuleVersionPinned string `json:"module_version_pinned"`
	State               string `json:"state"`
}

// Module installation queries
// Tracks which policy modules are installed on which assets
func (q *Queries) CreateModuleInstallation(ctx context.Context, arg CreateModuleInstallationParams) (ModuleInstallation, error) {
	row := q.db.QueryRowContext(ctx, CreateModuleInstallation,
		arg.AssetID,
		arg.ModuleID,
		arg.ModuleVersionPinned,
		arg.State,
	)
	var i ModuleInstallation
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ModuleID,
		&i.ModuleVersionPinned,
		&i.State,
		&i.AppliedAt,
		&i.LastValidatedAt,
		&i.LastReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteDependenciesForInstallation = `-- name: DeleteDependenciesForInstallation :exec
DELETE FROM module_installation_dependencies WHERE installation_id = ?1
`

func (q *Queries) DeleteDependenciesForInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteDependenciesForInstallation, installationID)
	return err
}

const DeleteDependenciesOnInstallation = `-- name: DeleteDependenciesOnInstallation :exec
DELETE FROM module_installation_dependencies WHERE depends_on_installation_id = ?1
`

func (q *Queries) DeleteDependenciesOnInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteDependenciesOnInstallation, installationID)
	return err
}

const DeleteInstallationDependency = `-- name: DeleteInstallationDependency :exec
DELETE FROM module_installation_dependencies WHERE id = ?1
`

func (q *Queries) DeleteInstallationDependency(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteInstallationDependency, id)
	return err
}

const DeleteInstallationsByAsset = `-- name: DeleteInstallationsByAsset :exec
DELETE FROM module_installations WHERE asset_id = ?1
`

func (q *Queries) DeleteInstallationsByAsset(ctx context.Context, assetID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteInstallationsByAsset, assetID)
	return err
}

const DeleteInstallationsByModule = `-- name: DeleteInstallationsByModule :exec
DELETE FROM module_installations WHERE module_id = ?1
`

func (q *Queries) DeleteInstallationsByModule(ctx context.Context, moduleID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteInstallationsByModule, moduleID)
	return err
}

const DeleteModuleInstallation = `-- name: DeleteModuleInstallation :exec
DELETE FROM module_installations WHERE id = ?1
`

func (q *Queries) DeleteModuleInstallation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteModuleInstallation, id)
	return err
}

const GetInstallationByAssetAndModule = `-- name: GetInstallationByAssetAndModule :one
SELECT id, asset_id, module_id, module_version_pinned, state, applied_at, last_validated_at, last_report, created_at, updated_at FROM module_installations 
WHERE asset_id = ?1 AND module_id = ?2 
LIMIT 1
`

type GetInstallationByAssetAndModuleParams struct {
	AssetID  int64 `json:"asset_id"`
	ModuleID int64 `json:"module_id"`
}

func (q *Queries) GetInstallationByAssetAndModule(ctx context.Context, arg GetInstallationByAssetAndModuleParams) (ModuleInstallation, error) {
	row := q.db.QueryRowContext(ctx, GetInstallationByAssetAndModule, arg.AssetID, arg.ModuleID)
	var i ModuleInstallation
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ModuleID,
		&i.ModuleVersionPinned,
		&i.State,
		&i.AppliedAt,
		&i.LastValidatedAt,
		&i.LastReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetModuleInstallation = `-- name: GetModuleInstallation :one
SELECT id, asset_id, module_id, module_version_pinned, state, applied_at, last_validated_at, last_report, created_at, updated_at FROM module_installations WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetModuleInstallation(ctx context.Context, id int64) (ModuleInstallation, error) {
	row := q.db.QueryRowContext(ctx, GetModuleInstallation, id)
	var i ModuleInstallation
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ModuleID,
		&i.ModuleVersionPinned,
		&i.State,
		&i.AppliedAt,
		&i.LastValidatedAt,
		&i.LastReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListDependenciesForInstallation = `-- name: ListDependenciesForInstallation :many
SELECT 
    d.id, d.installation_id, d.depends_on_installation_id, d.created_at,
    i.module_id as depends_on_module_id,
    m.title as depends_on_module_title
FROM module_installation_dependencies d
JOIN module_installations i ON i.id = d.depends_on_installation_id
JOIN policy_modules m ON m.id = i.module_id
WHERE d.installation_id = ?1
`

type ListDependenciesForInstallationRow struct {
	ID                      int64     `json:"id"`
	InstallationID          int64     `json:"installation_id"`
	DependsOnInstallationID int64     `json:"depends_on_installation_id"`
	CreatedAt               time.Time `json:"created_at"`
	DependsOnModuleID       int64     `json:"depends_on_module_id"`
	DependsOnModuleTitle    string    `json:"depends_on_module_title"`
}

func (q *Queries) ListDependenciesForInstallation(ctx context.Context, installationID int64) ([]ListDependenciesForInstallationRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDependenciesForInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDependenciesForInstallationRow{}
	for rows.Next() {
		var i ListDependenciesForInstallationRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.DependsOnInstallationID,
			&i.CreatedAt,
			&i.DependsOnModuleID,
			&i.DependsOnModuleTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDependentsOfInstallation = `-- name: ListDependentsOfInstallation :many
SELECT 
    d.id, d.installation_id, d.depends_on_installation_id, d.created_at,
    i.module_id as dependent_module_id,
    m.title as dependent_module_title
FROM module_installation_dependencies d
JOIN module_installations i ON i.id = d.installation_id
JOIN policy_modules m ON m.id = i.module_id
WHERE d.depends_on_installation_id = ?1
`

type ListDependentsOfInstallationRow struct {
	ID                      int64     `json:"id"`
	InstallationID          int64     `json:"installation_id"`
	DependsOnInstallationID int64     `json:"depends_on_installation_id"`
	CreatedAt               time.Time `json:"created_at"`
	DependentModuleID       int64     `json:"dependent_module_id"`
	DependentModuleTitle    string    `json:"dependent_module_title"`
}

func (q *Queries) ListDependentsOfInstallation(ctx context.Context, installationID int64) ([]ListDependentsOfInstallationRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDependentsOfInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDependentsOfInstallationRow{}
	for rows.Next() {
		var i ListDependentsOfInstallationRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.DependsOnInstallationID,
			&i.CreatedAt,
			&i.DependentModuleID,
			&i.DependentModuleTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListFailingInstallations = `-- name: ListFailingInstallations :many
SELECT 
    i.id, i.asset_id, i.module_id, i.module_version_pinned, i.state, i.applied_at, i.last_validated_at, i.last_report, i.created_at, i.updated_at,
    a.human_id as asset_human_id,
    m.title as module_title
FROM module_installations i
JOIN assets a ON a.id = i.asset_id
JOIN policy_modules m ON m.id = i.module_id
WHERE i.state = 'failing' AND a.deleted_at IS NULL AND m.deleted_at IS NULL
ORDER BY i.updated_at DESC
LIMIT ?1
`

type ListFailingInstallationsRow struct {
	ID                  int64          `json:"id"`
	AssetID             int64          `json:"asset_id"`
	ModuleID            int64          `json:"module_id"`
	ModuleVersionPinned string         `json:"module_version_pinned"`
	State               string         `json:"state"`
	AppliedAt           sql.NullTime   `json:"applied_at"`
	LastValidatedAt     sql.NullTime   `json:"last_validated_at"`
	LastReport          sql.NullString `json:"last_report"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	AssetHumanID        sql.NullString `json:"asset_human_id"`
	ModuleTitle         string         `json:"module_title"`
}

func (q *Queries) ListFailingInstallations(ctx context.Context, limit int64) ([]ListFailingInstallationsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListFailingInstallations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailingInstallationsRow{}
	for rows.Next() {
		var i ListFailingInstallationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.ModuleID,
			&i.ModuleVersionPinned,
			&i.State,
			&i.AppliedAt,
			&i.LastValidatedAt,
			&i.LastReport,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssetHumanID,
			&i.ModuleTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListInstallationsByAsset = `-- name: ListInstallationsByAsset :many
SELECT 
    i.id, i.asset_id, i.module_id, i.module_version_pinned, i.state, i.applied_at, i.last_validated_at, i.last_report, i.created_at, i.updated_at,
    m.module_urn,
    m.title as module_title
FROM module_installations i
JOIN policy_modules m ON m.id = i.module_id
WHERE i.asset_id = ?1 AND m.deleted_at IS NULL
ORDER BY m.title
`

type ListInstallationsByAssetRow struct {
	ID                  int64          `json:"id"`
	AssetID             int64          `json:"asset_id"`
	ModuleID            int64          `json:"module_id"`
	ModuleVersionPinned string         `json:"module_version_pinned"`
	State               string         `json:"state"`
	AppliedAt           sql.NullTime   `json:"applied_at"`
	LastValidatedAt     sql.NullTime   `json:"last_validated_at"`
	LastReport          sql.NullString `json:"last_report"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	ModuleUrn           string         `json:"module_urn"`
	ModuleTitle         string         `json:"module_title"`
}

func (q *Queries) ListInstallationsByAsset(ctx context.Context, assetID int64) ([]ListInstallationsByAssetRow, error) {
	rows, err := q.db.QueryContext(ctx, ListInstallationsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstallationsByAssetRow{}
	for rows.Next() {
		var i ListInstallationsByAssetRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.ModuleID,
			&i.ModuleVersionPinned,
			&i.State,
			&i.AppliedAt,
			&i.LastValidatedAt,
			&i.LastReport,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModuleUrn,
			&i.ModuleTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListInstallationsByModule = `-- name: ListInstallationsByModule :many
SELECT 
    i.id, i.asset_id, i.module_id, i.module_version_pinned, i.state, i.applied_at, i.last_validated_at, i.last_report, i.created_at, i.updated_at,
    a.human_id as asset_human_id,
    json_extract(a.subtype_payload, '$.hostname') as asset_hostname
FROM module_installations i
JOIN assets a ON a.id = i.asset_id
WHERE i.module_id = ?1 AND a.deleted_at IS NULL
ORDER BY i.state, a.human_id
`

type ListInstallationsByModuleRow struct {
	ID                  int64          `json:"id"`
	AssetID             int64          `json:"asset_id"`
	ModuleID            int64          `json:"module_id"`
	ModuleVersionPinned string         `json:"module_version_pinned"`
	State               string         `json:"state"`
	AppliedAt           sql.NullTime   `json:"applied_at"`
	LastValidatedAt     sql.NullTime   `json:"last_validated_at"`
	LastReport          sql.NullString `json:"last_report"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	AssetHumanID        sql.NullString `json:"asset_human_id"`
	AssetHostname       interface{}    `json:"asset_hostname"`
}

func (q *Queries) ListInstallationsByModule(ctx context.Context, moduleID int64) ([]ListInstallationsByModuleRow, error) {
	rows, err := q.db.QueryContext(ctx, ListInstallationsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstallationsByModuleRow{}
	for rows.Next() {
		var i ListInstallationsByModuleRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.ModuleID,
			&i.ModuleVersionPinned,
			&i.State,
			&i.AppliedAt,
			&i.LastValidatedAt,
			&i.LastReport,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssetHumanID,
			&i.AssetHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListInstallationsByState = `-- name: ListInstallationsByState :many
SELECT 
    i.id, i.asset_id, i.module_id, i.module_version_pinned, i.state, i.applied_at, i.last_validated_at, i.last_report, i.created_at, i.updated_at,
    a.human_id as asset_human_id,
    m.title as module_title
FROM module_installations i
JOIN assets a ON a.id = i.asset_id
JOIN policy_modules m ON m.id = i.module_id
WHERE i.state = ?1 AND a.deleted_at IS NULL AND m.deleted_at IS NULL
ORDER BY i.updated_at DESC
LIMIT ?2
`

type ListInstallationsByStateParams struct {
	State string `json:"state"`
	Limit int64  `json:"limit"`
}

type ListInstallationsByStateRow struct {
	ID                  int64          `json:"id"`
	AssetID             int64          `json:"asset_id"`
	ModuleID            int64          `json:"module_id"`
	ModuleVersionPinned string         `json:"module_version_pinned"`
	State               string         `json:"state"`
	AppliedAt           sql.NullTime   `json:"applied_at"`
	LastValidatedAt     sql.NullTime   `json:"last_validated_at"`
	LastReport          sql.NullString `json:"last_report"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	AssetHumanID        sql.NullString `json:"asset_human_id"`
	ModuleTitle         string         `json:"module_title"`
}

func (q *Queries) ListInstallationsByState(ctx context.Context, arg ListInstallationsByStateParams) ([]ListInstallationsByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, ListInstallationsByState, arg.State, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstallationsByStateRow{}
	for rows.Next() {
		var i ListInstallationsByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.ModuleID,
			&i.ModuleVersionPinned,
			&i.State,
			&i.AppliedAt,
			&i.LastValidatedAt,
			&i.LastReport,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssetHumanID,
			&i.ModuleTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPendingInstallations = `-- name: ListPendingInstallations :many
SELECT 
    i.id, i.asset_id, i.module_id, i.module_version_pinned, i.state, i.applied_at, i.last_validated_at, i.last_report, i.created_at, i.updated_at,
    a.human_id as asset_human_id,
    m.module_urn
FROM module_installations i
JOIN assets a ON a.id = i.asset_id
JOIN policy_modules m ON m.id = i.module_id
WHERE i.state = 'pending' AND a.deleted_at IS NULL AND m.deleted_at IS NULL
ORDER BY i.created_at
LIMIT ?1
`

type ListPendingInstallationsRow struct {
	ID                  int64          `json:"id"`
	AssetID             int64          `json:"asset_id"`
	ModuleID            int64          `json:"module_id"`
	ModuleVersionPinned string         `json:"module_version_pinned"`
	State               string         `json:"state"`
	AppliedAt           sql.NullTime   `json:"applied_at"`
	LastValidatedAt     sql.NullTime   `json:"last_validated_at"`
	LastReport          sql.NullString `json:"last_report"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	AssetHumanID        sql.NullString `json:"asset_human_id"`
	ModuleUrn           string         `json:"module_urn"`
}

func (q *Queries) ListPendingInstallations(ctx context.Context, limit int64) ([]ListPendingInstallationsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPendingInstallations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInstallationsRow{}
	for rows.Next() {
		var i ListPendingInstallationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.ModuleID,
			&i.ModuleVersionPinned,
			&i.State,
			&i.AppliedAt,
			&i.LastValidatedAt,
			&i.LastReport,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssetHumanID,
			&i.ModuleUrn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateInstallationApplied = `-- name: UpdateInstallationApplied :exec
UPDATE module_installations SET
    state = 'applied',
    applied_at = CURRENT_TIMESTAMP,
    last_validated_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
`

func (q *Queries) UpdateInstallationApplied(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, UpdateInstallationApplied, id)
	return err
}

const UpdateInstallationState = `-- name: UpdateInstallationState :exec
UPDATE module_installations SET
    state = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateInstallationStateParams struct {
	State string `json:"state"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateInstallationState(ctx context.Context, arg UpdateInstallationStateParams) error {
	_, err := q.db.ExecContext(ctx, UpdateInstallationState, arg.State, arg.ID)
	return err
}

const UpdateModuleInstallation = `-- name: UpdateModuleInstallation :one
UPDATE module_installations SET
    module_version_pinned = ?1,
    state = ?2,
    last_report = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?4
RETURNING id, asset_id, module_id, module_version_pinned, state, applied_at, last_validated_at, last_report, created_at, updated_at
`

type UpdateModuleInstallationParams struct {
	ModuleVersionPinned string         `json:"module_version_pinned"`
	State               string         `json:"state"`
	LastReport          sql.NullString `json:"last_report"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateModuleInstallation(ctx context.Context, arg UpdateModuleInstallationParams) (ModuleInstallation, error) {
	row := q.db.QueryRowContext(ctx, UpdateModuleInstallation,
		arg.ModuleVersionPinned,
		arg.State,
		arg.LastReport,
		arg.ID,
	)
	var i ModuleInstallation
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ModuleID,
		&i.ModuleVersionPinned,
		&i.State,
		&i.AppliedAt,
		&i.LastValidatedAt,
		&i.LastReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
