// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy_modules.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CacheVersionManifest = `-- name: CacheVersionManifest :exec
UPDATE policy_module_versions SET manifest_yaml = ?1 WHERE id = ?2
`

type CacheVersionManifestParams struct {
	ManifestYaml string `json:"manifest_yaml"`
	ID           int64  `json:"id"`
}

// manifest_yaml is a derived export artifact (008 header); this cache
// write happens at .pmdl export time and is never read back as input.
func (q *Queries) CacheVersionManifest(ctx context.Context, arg CacheVersionManifestParams) error {
	_, err := q.db.ExecContext(ctx, CacheVersionManifest, arg.ManifestYaml, arg.ID)
	return err
}

const CountPolicyModulesByTenant = `-- name: CountPolicyModulesByTenant :one
SELECT COUNT(*) FROM policy_modules WHERE tenant_id = ?1 AND deleted_at IS NULL
`

func (q *Queries) CountPolicyModulesByTenant(ctx context.Context, tenantID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPolicyModulesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountVersionsByModule = `-- name: CountVersionsByModule :one
SELECT COUNT(*) FROM policy_module_versions WHERE module_id = ?1
`

func (q *Queries) CountVersionsByModule(ctx context.Context, moduleID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountVersionsByModule, moduleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreatePolicyModule = `-- name: CreatePolicyModule :one

INSERT INTO policy_modules (
    module_urn,
    tenant_id,
    title,
    description,
    is_bundled
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
) RETURNING id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin
`

type CreatePolicyModuleParams struct {
	ModuleUrn   string         `json:"module_urn"`
	TenantID    sql.NullInt64  `json:"tenant_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	IsBundled   bool           `json:"is_bundled"`
}

// Policy module queries
// Policy modules are versioned, signed policy definitions
func (q *Queries) CreatePolicyModule(ctx context.Context, arg CreatePolicyModuleParams) (PolicyModule, error) {
	row := q.db.QueryRowContext(ctx, CreatePolicyModule,
		arg.ModuleUrn,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.IsBundled,
	)
	var i PolicyModule
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
		&i.OwnerIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Origin,
	)
	return i, err
}

const CreatePolicyModuleVersion = `-- name: CreatePolicyModuleVersion :one

INSERT INTO policy_module_versions (
    module_id,
    version,
    state,
    manifest_yaml,
    target_os,
    scope,
    satisfies,
    parameters_schema,
    depends_on,
    conflicts,
    sandbox_profile,
    report_schema
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
) RETURNING id, module_id, version, state, target_os, scope, satisfies, parameters_schema, depends_on, conflicts, sandbox_profile, report_schema, manifest_yaml, signature_algo, signature_data, signed_by, published_at, published_by, superseded_by_version, created_at, conditions_match_mode
`

type CreatePolicyModuleVersionParams struct {
	ModuleID         int64          `json:"module_id"`
	Version          string         `json:"version"`
	State            string         `json:"state"`
	ManifestYaml     string         `json:"manifest_yaml"`
	TargetOs         string         `json:"target_os"`
	Scope            string         `json:"scope"`
	Satisfies        string         `json:"satisfies"`
	ParametersSchema sql.NullString `json:"parameters_schema"`
	DependsOn        sql.NullString `json:"depends_on"`
	Conflicts        sql.NullString `json:"conflicts"`
	SandboxProfile   string         `json:"sandbox_profile"`
	ReportSchema     string         `json:"report_schema"`
}

// ============================================================================
// Policy Module Versions
//
// Migration 008 reconciled this table with the catalog/policymodules
// domain model: runtime moved to per-phase (derived in Go from
// LifecyclePhase, never stored -- see 008's header), and the fixed
// enforce_script/validate_script/rollback_script columns were replaced
// by the policy_module_scripts child table below.
// ============================================================================
func (q *Queries) CreatePolicyModuleVersion(ctx context.Context, arg CreatePolicyModuleVersionParams) (PolicyModuleVersion, error) {
	row := q.db.QueryRowContext(ctx, CreatePolicyModuleVersion,
		arg.ModuleID,
		arg.Version,
		arg.State,
		arg.ManifestYaml,
		arg.TargetOs,
		arg.Scope,
		arg.Satisfies,
		arg.ParametersSchema,
		arg.DependsOn,
		arg.Conflicts,
		arg.SandboxProfile,
		arg.ReportSchema,
	)
	var i PolicyModuleVersion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.State,
		&i.TargetOs,
		&i.Scope,
		&i.Satisfies,
		&i.ParametersSchema,
		&i.DependsOn,
		&i.Conflicts,
		&i.SandboxProfile,
		&i.ReportSchema,
		&i.ManifestYaml,
		&i.SignatureAlgo,
		&i.SignatureData,
		&i.SignedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.SupersededByVersion,
		&i.CreatedAt,
		&i.ConditionsMatchMode,
	)
	return i, err
}

const CreateVersionConditionGuarded = `-- name: CreateVersionConditionGuarded :one
INSERT INTO module_version_conditions (version_id, kind, param_path, operator, value_json, script_source, script_ref, seq)
SELECT ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
WHERE EXISTS (
    SELECT 1 FROM policy_module_versions
    WHERE id = ?1 AND state = 'draft'
)
RETURNING id, version_id, kind, param_path, operator, value_json, script_source, script_ref, script_expect, seq
`

type CreateVersionConditionGuardedParams struct {
	VersionID    int64  `json:"version_id"`
	Kind         string `json:"kind"`
	ParamPath    string `json:"param_path"`
	Operator     string `json:"operator"`
	ValueJson    string `json:"value_json"`
	ScriptSource string `json:"script_source"`
	ScriptRef    string `json:"script_ref"`
	Seq          int64  `json:"seq"`
}

func (q *Queries) CreateVersionConditionGuarded(ctx context.Context, arg CreateVersionConditionGuardedParams) (ModuleVersionCondition, error) {
	row := q.db.QueryRowContext(ctx, CreateVersionConditionGuarded,
		arg.VersionID,
		arg.Kind,
		arg.ParamPath,
		arg.Operator,
		arg.ValueJson,
		arg.ScriptSource,
		arg.ScriptRef,
		arg.Seq,
	)
	var i ModuleVersionCondition
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Kind,
		&i.ParamPath,
		&i.Operator,
		&i.ValueJson,
		&i.ScriptSource,
		&i.ScriptRef,
		&i.ScriptExpect,
		&i.Seq,
	)
	return i, err
}

const DeleteCustomActionsForVersion = `-- name: DeleteCustomActionsForVersion :exec
DELETE FROM policy_module_actions WHERE version_id = ?1 AND origin = 'custom'
`

func (q *Queries) DeleteCustomActionsForVersion(ctx context.Context, versionID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteCustomActionsForVersion, versionID)
	return err
}

const DeleteCustomScriptsForVersion = `-- name: DeleteCustomScriptsForVersion :exec
DELETE FROM policy_module_scripts WHERE version_id = ?1 AND origin = 'custom'
`

func (q *Queries) DeleteCustomScriptsForVersion(ctx context.Context, versionID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteCustomScriptsForVersion, versionID)
	return err
}

const DeleteDraftModuleVersion = `-- name: DeleteDraftModuleVersion :execrows
DELETE FROM policy_module_versions WHERE id = ?1 AND state = 'draft'
`

// State-guarded in the statement itself (same pattern as
// PublishModuleVersion): only a draft can be deleted, so a concurrent
// publish landing between a caller's read and this delete can never
// destroy a published version.
func (q *Queries) DeleteDraftModuleVersion(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteDraftModuleVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeleteModuleActionGuarded = `-- name: DeleteModuleActionGuarded :execrows
DELETE FROM policy_module_actions
WHERE version_id = ?1 AND action_key = ?2
  AND EXISTS (
    SELECT 1 FROM policy_module_versions
    WHERE id = ?1 AND state = 'draft'
  )
`

type DeleteModuleActionGuardedParams struct {
	VersionID int64  `json:"version_id"`
	ActionKey string `json:"action_key"`
}

func (q *Queries) DeleteModuleActionGuarded(ctx context.Context, arg DeleteModuleActionGuardedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteModuleActionGuarded, arg.VersionID, arg.ActionKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeleteModuleScriptGuarded = `-- name: DeleteModuleScriptGuarded :execrows
DELETE FROM policy_module_scripts
WHERE version_id = ?1 AND name = ?2
  AND EXISTS (
    SELECT 1 FROM policy_module_versions
    WHERE id = ?1 AND state = 'draft'
  )
`

type DeleteModuleScriptGuardedParams struct {
	VersionID int64  `json:"version_id"`
	Name      string `json:"name"`
}

func (q *Queries) DeleteModuleScriptGuarded(ctx context.Context, arg DeleteModuleScriptGuardedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteModuleScriptGuarded, arg.VersionID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeletePolicyModule = `-- name: DeletePolicyModule :exec
DELETE FROM policy_modules WHERE id = ?1
`

func (q *Queries) DeletePolicyModule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeletePolicyModule, id)
	return err
}

const DeletePolicyModuleVersion = `-- name: DeletePolicyModuleVersion :exec
DELETE FROM policy_module_versions WHERE id = ?1
`

func (q *Queries) DeletePolicyModuleVersion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeletePolicyModuleVersion, id)
	return err
}

const DeleteVersionConditionGuarded = `-- name: DeleteVersionConditionGuarded :execrows
DELETE FROM module_version_conditions
WHERE module_version_conditions.id = ?1 AND version_id = ?2
  AND EXISTS (
    SELECT 1 FROM policy_module_versions v
    WHERE v.id = ?2 AND v.state = 'draft'
  )
`

type DeleteVersionConditionGuardedParams struct {
	ID        int64 `json:"id"`
	VersionID int64 `json:"version_id"`
}

func (q *Queries) DeleteVersionConditionGuarded(ctx context.Context, arg DeleteVersionConditionGuardedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteVersionConditionGuarded, arg.ID, arg.VersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const GetLatestPublishedVersion = `-- name: GetLatestPublishedVersion :one
SELECT id, module_id, version, state, target_os, scope, satisfies, parameters_schema, depends_on, conflicts, sandbox_profile, report_schema, manifest_yaml, signature_algo, signature_data, signed_by, published_at, published_by, superseded_by_version, created_at, conditions_match_mode FROM policy_module_versions
WHERE module_id = ?1 AND state = 'published'
ORDER BY published_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPublishedVersion(ctx context.Context, moduleID int64) (PolicyModuleVersion, error) {
	row := q.db.QueryRowContext(ctx, GetLatestPublishedVersion, moduleID)
	var i PolicyModuleVersion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.State,
		&i.TargetOs,
		&i.Scope,
		&i.Satisfies,
		&i.ParametersSchema,
		&i.DependsOn,
		&i.Conflicts,
		&i.SandboxProfile,
		&i.ReportSchema,
		&i.ManifestYaml,
		&i.SignatureAlgo,
		&i.SignatureData,
		&i.SignedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.SupersededByVersion,
		&i.CreatedAt,
		&i.ConditionsMatchMode,
	)
	return i, err
}

const GetModuleOwner = `-- name: GetModuleOwner :one
SELECT owner_identity_id FROM policy_modules WHERE id = ?1 LIMIT 1
`

// Returns just the owner_identity_id column; GetPolicyModule's SELECT *
// already includes it, but this narrow query is convenient for authz
// checks that only need the owner, not the whole row.
func (q *Queries) GetModuleOwner(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, GetModuleOwner, id)
	var owner_identity_id sql.NullInt64
	err := row.Scan(&owner_identity_id)
	return owner_identity_id, err
}

const GetModuleWithLatestVersion = `-- name: GetModuleWithLatestVersion :one
SELECT
    m.id, m.module_urn, m.tenant_id, m.title, m.description, m.is_bundled, m.created_at, m.owner_identity_id, m.deleted_at, m.deleted_by, m.origin,
    v.id as latest_version_id,
    v.version as latest_version,
    v.published_at as latest_published_at
FROM policy_modules m
LEFT JOIN policy_module_versions v ON v.module_id = m.id AND v.state = 'published'
WHERE m.id = ?1
ORDER BY v.published_at DESC
LIMIT 1
`

type GetModuleWithLatestVersionRow struct {
	ID                int64          `json:"id"`
	ModuleUrn         string         `json:"module_urn"`
	TenantID          sql.NullInt64  `json:"tenant_id"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	IsBundled         bool           `json:"is_bundled"`
	CreatedAt         time.Time      `json:"created_at"`
	OwnerIdentityID   sql.NullInt64  `json:"owner_identity_id"`
	DeletedAt         interface{}    `json:"deleted_at"`
	DeletedBy         interface{}    `json:"deleted_by"`
	Origin            string         `json:"origin"`
	LatestVersionID   sql.NullInt64  `json:"latest_version_id"`
	LatestVersion     sql.NullString `json:"latest_version"`
	LatestPublishedAt sql.NullTime   `json:"latest_published_at"`
}

func (q *Queries) GetModuleWithLatestVersion(ctx context.Context, id int64) (GetModuleWithLatestVersionRow, error) {
	row := q.db.QueryRowContext(ctx, GetModuleWithLatestVersion, id)
	var i GetModuleWithLatestVersionRow
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
		&i.OwnerIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Origin,
		&i.LatestVersionID,
		&i.LatestVersion,
		&i.LatestPublishedAt,
	)
	return i, err
}

const GetPolicyModule = `-- name: GetPolicyModule :one
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin FROM policy_modules WHERE id = ?1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetPolicyModule(ctx context.Context, id int64) (PolicyModule, error) {
	row := q.db.QueryRowContext(ctx, GetPolicyModule, id)
	var i PolicyModule
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
		&i.OwnerIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Origin,
	)
	return i, err
}

const GetPolicyModuleByURN = `-- name: GetPolicyModuleByURN :one
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin FROM policy_modules 
WHERE module_urn = ?1 
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPolicyModuleByURN(ctx context.Context, moduleUrn string) (PolicyModule, error) {
	row := q.db.QueryRowContext(ctx, GetPolicyModuleByURN, moduleUrn)
	var i PolicyModule
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
		&i.OwnerIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Origin,
	)
	return i, err
}

const GetPolicyModuleByURNIncludingDeleted = `-- name: GetPolicyModuleByURNIncludingDeleted :one
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin FROM policy_modules
WHERE module_urn = ?1
LIMIT 1
`

func (q *Queries) GetPolicyModuleByURNIncludingDeleted(ctx context.Context, moduleUrn string) (PolicyModule, error) {
	row := q.db.QueryRowContext(ctx, GetPolicyModuleByURNIncludingDeleted, moduleUrn)
	var i PolicyModule
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
		&i.OwnerIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Origin,
	)
	return i, err
}

const GetPolicyModuleVersion = `-- name: GetPolicyModuleVersion :one
SELECT id, module_id, version, state, target_os, scope, satisfies, parameters_schema, depends_on, conflicts, sandbox_profile, report_schema, manifest_yaml, signature_algo, signature_data, signed_by, published_at, published_by, superseded_by_version, created_at, conditions_match_mode FROM policy_module_versions WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetPolicyModuleVersion(ctx context.Context, id int64) (PolicyModuleVersion, error) {
	row := q.db.QueryRowContext(ctx, GetPolicyModuleVersion, id)
	var i PolicyModuleVersion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.State,
		&i.TargetOs,
		&i.Scope,
		&i.Satisfies,
		&i.ParametersSchema,
		&i.DependsOn,
		&i.Conflicts,
		&i.SandboxProfile,
		&i.ReportSchema,
		&i.ManifestYaml,
		&i.SignatureAlgo,
		&i.SignatureData,
		&i.SignedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.SupersededByVersion,
		&i.CreatedAt,
		&i.ConditionsMatchMode,
	)
	return i, err
}

const GetPolicyModuleVersionByNumber = `-- name: GetPolicyModuleVersionByNumber :one
SELECT id, module_id, version, state, target_os, scope, satisfies, parameters_schema, depends_on, conflicts, sandbox_profile, report_schema, manifest_yaml, signature_algo, signature_data, signed_by, published_at, published_by, superseded_by_version, created_at, conditions_match_mode FROM policy_module_versions
WHERE module_id = ?1 AND version = ?2
LIMIT 1
`

type GetPolicyModuleVersionByNumberParams struct {
	ModuleID int64  `json:"module_id"`
	Version  string `json:"version"`
}

func (q *Queries) GetPolicyModuleVersionByNumber(ctx context.Context, arg GetPolicyModuleVersionByNumberParams) (PolicyModuleVersion, error) {
	row := q.db.QueryRowContext(ctx, GetPolicyModuleVersionByNumber, arg.ModuleID, arg.Version)
	var i PolicyModuleVersion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.State,
		&i.TargetOs,
		&i.Scope,
		&i.Satisfies,
		&i.ParametersSchema,
		&i.DependsOn,
		&i.Conflicts,
		&i.SandboxProfile,
		&i.ReportSchema,
		&i.ManifestYaml,
		&i.SignatureAlgo,
		&i.SignatureData,
		&i.SignedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.SupersededByVersion,
		&i.CreatedAt,
		&i.ConditionsMatchMode,
	)
	return i, err
}

const GetScriptByName = `-- name: GetScriptByName :one
SELECT id, version_id, name, language, source, origin, seq FROM policy_module_scripts WHERE version_id = ?1 AND name = ?2
`

type GetScriptByNameParams struct {
	VersionID int64  `json:"version_id"`
	Name      string `json:"name"`
}

func (q *Queries) GetScriptByName(ctx context.Context, arg GetScriptByNameParams) (PolicyModuleScript, error) {
	row := q.db.QueryRowContext(ctx, GetScriptByName, arg.VersionID, arg.Name)
	var i PolicyModuleScript
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Name,
		&i.Language,
		&i.Source,
		&i.Origin,
		&i.Seq,
	)
	return i, err
}

const ListActionsForVersion = `-- name: ListActionsForVersion :many
SELECT id, version_id, action_key, label, kind, value, origin, seq FROM policy_module_actions WHERE version_id = ?1 ORDER BY seq, action_key
`

func (q *Queries) ListActionsForVersion(ctx context.Context, versionID int64) ([]PolicyModuleAction, error) {
	rows, err := q.db.QueryContext(ctx, ListActionsForVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModuleAction{}
	for rows.Next() {
		var i PolicyModuleAction
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.ActionKey,
			&i.Label,
			&i.Kind,
			&i.Value,
			&i.Origin,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListBundledModules = `-- name: ListBundledModules :many
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin FROM policy_modules 
WHERE is_bundled = TRUE
  AND deleted_at IS NULL
ORDER BY title
`

func (q *Queries) ListBundledModules(ctx context.Context) ([]PolicyModule, error) {
	rows, err := q.db.QueryContext(ctx, ListBundledModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModule{}
	for rows.Next() {
		var i PolicyModule
		if err := rows.Scan(
			&i.ID,
			&i.ModuleUrn,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.IsBundled,
			&i.CreatedAt,
			&i.OwnerIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDeletedVisibleModules = `-- name: ListDeletedVisibleModules :many
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin FROM policy_modules
WHERE (tenant_id = ?1 OR is_bundled = TRUE)
  AND deleted_at IS NOT NULL
ORDER BY title
`

func (q *Queries) ListDeletedVisibleModules(ctx context.Context, tenantID sql.NullInt64) ([]PolicyModule, error) {
	rows, err := q.db.QueryContext(ctx, ListDeletedVisibleModules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModule{}
	for rows.Next() {
		var i PolicyModule
		if err := rows.Scan(
			&i.ID,
			&i.ModuleUrn,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.IsBundled,
			&i.CreatedAt,
			&i.OwnerIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListExpiredPolicyModules = `-- name: ListExpiredPolicyModules :many
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin FROM policy_modules
WHERE deleted_at IS NOT NULL
  AND deleted_at <= ?1
ORDER BY deleted_at, id
`

func (q *Queries) ListExpiredPolicyModules(ctx context.Context, cutoff interface{}) ([]PolicyModule, error) {
	rows, err := q.db.QueryContext(ctx, ListExpiredPolicyModules, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModule{}
	for rows.Next() {
		var i PolicyModule
		if err := rows.Scan(
			&i.ID,
			&i.ModuleUrn,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.IsBundled,
			&i.CreatedAt,
			&i.OwnerIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPolicyModulesByTenant = `-- name: ListPolicyModulesByTenant :many
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin FROM policy_modules 
WHERE tenant_id = ?1 
  AND deleted_at IS NULL
ORDER BY title
LIMIT ?3 OFFSET ?2
`

type ListPolicyModulesByTenantParams struct {
	TenantID sql.NullInt64 `json:"tenant_id"`
	Offset   int64         `json:"offset"`
	Limit    int64         `json:"limit"`
}

func (q *Queries) ListPolicyModulesByTenant(ctx context.Context, arg ListPolicyModulesByTenantParams) ([]PolicyModule, error) {
	rows, err := q.db.QueryContext(ctx, ListPolicyModulesByTenant, arg.TenantID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModule{}
	for rows.Next() {
		var i PolicyModule
		if err := rows.Scan(
			&i.ID,
			&i.ModuleUrn,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.IsBundled,
			&i.CreatedAt,
			&i.OwnerIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListScriptsForVersion = `-- name: ListScriptsForVersion :many

SELECT id, version_id, name, language, source, origin, seq FROM policy_module_scripts WHERE version_id = ?1 ORDER BY seq, name
`

// ============================================================================
// Policy Module Scripts + Actions (migration 012, replaces migration 008)
//
// Scripts are now first-class named rows (name/language/origin) instead
// of phase-keyed. Actions are the enforcement wiring: a separate table
// that references a script by name (kind='script') or holds an inline
// command (kind='command'). origin distinguishes seeded defaults
// (never mutated in place; the Go service layer forks an edited
// default into a custom row) from tenant-authored rows.
// ============================================================================
func (q *Queries) ListScriptsForVersion(ctx context.Context, versionID int64) ([]PolicyModuleScript, error) {
	rows, err := q.db.QueryContext(ctx, ListScriptsForVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModuleScript{}
	for rows.Next() {
		var i PolicyModuleScript
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.Name,
			&i.Language,
			&i.Source,
			&i.Origin,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListVersionConditions = `-- name: ListVersionConditions :many

SELECT id, version_id, kind, param_path, operator, value_json, script_source, script_ref, script_expect, seq FROM module_version_conditions
WHERE version_id = ?1
ORDER BY seq, id
`

// ============================================================================
// Module Version Conditions (migration 011)
//
// Per-version applicability tests, column parity with
// dependency_group_conditions so the same eval engine and condition
// builder drive both (INV-CB). All writes are draft-guarded via a
// WHERE EXISTS subquery on the parent version state, mirroring
// UpsertModuleScriptGuarded: zero rows affected on a non-draft version
// surfaces as sql.ErrNoRows / 0 execrows, which the service maps to
// ErrVersionNotDraft. script_expect exists for parity only and is
// never written (legacy dead column, see 011 header).
// ============================================================================
func (q *Queries) ListVersionConditions(ctx context.Context, versionID int64) ([]ModuleVersionCondition, error) {
	rows, err := q.db.QueryContext(ctx, ListVersionConditions, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModuleVersionCondition{}
	for rows.Next() {
		var i ModuleVersionCondition
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.Kind,
			&i.ParamPath,
			&i.Operator,
			&i.ValueJson,
			&i.ScriptSource,
			&i.ScriptRef,
			&i.ScriptExpect,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListVersionsByModule = `-- name: ListVersionsByModule :many
SELECT v.id, v.module_id, v.version, v.state, v.target_os, v.scope, v.satisfies, v.parameters_schema, v.depends_on, v.conflicts, v.sandbox_profile, v.report_schema, v.manifest_yaml, v.signature_algo, v.signature_data, v.signed_by, v.published_at, v.published_by, v.superseded_by_version, v.created_at, v.conditions_match_mode, i.display_name as publisher_name
FROM policy_module_versions v
LEFT JOIN identities i ON i.id = v.published_by
WHERE v.module_id = ?1
ORDER BY v.created_at DESC
`

type ListVersionsByModuleRow struct {
	ID                  int64          `json:"id"`
	ModuleID            int64          `json:"module_id"`
	Version             string         `json:"version"`
	State               string         `json:"state"`
	TargetOs            string         `json:"target_os"`
	Scope               string         `json:"scope"`
	Satisfies           string         `json:"satisfies"`
	ParametersSchema    sql.NullString `json:"parameters_schema"`
	DependsOn           sql.NullString `json:"depends_on"`
	Conflicts           sql.NullString `json:"conflicts"`
	SandboxProfile      string         `json:"sandbox_profile"`
	ReportSchema        string         `json:"report_schema"`
	ManifestYaml        string         `json:"manifest_yaml"`
	SignatureAlgo       sql.NullString `json:"signature_algo"`
	SignatureData       sql.NullString `json:"signature_data"`
	SignedBy            sql.NullString `json:"signed_by"`
	PublishedAt         sql.NullTime   `json:"published_at"`
	PublishedBy         sql.NullInt64  `json:"published_by"`
	SupersededByVersion sql.NullString `json:"superseded_by_version"`
	CreatedAt           time.Time      `json:"created_at"`
	ConditionsMatchMode string         `json:"conditions_match_mode"`
	PublisherName       sql.NullString `json:"publisher_name"`
}

func (q *Queries) ListVersionsByModule(ctx context.Context, moduleID int64) ([]ListVersionsByModuleRow, error) {
	rows, err := q.db.QueryContext(ctx, ListVersionsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVersionsByModuleRow{}
	for rows.Next() {
		var i ListVersionsByModuleRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.Version,
			&i.State,
			&i.TargetOs,
			&i.Scope,
			&i.Satisfies,
			&i.ParametersSchema,
			&i.DependsOn,
			&i.Conflicts,
			&i.SandboxProfile,
			&i.ReportSchema,
			&i.ManifestYaml,
			&i.SignatureAlgo,
			&i.SignatureData,
			&i.SignedBy,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.SupersededByVersion,
			&i.CreatedAt,
			&i.ConditionsMatchMode,
			&i.PublisherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListVisibleModules = `-- name: ListVisibleModules :many
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin FROM policy_modules
WHERE (tenant_id = ?1 OR is_bundled = TRUE)
  AND deleted_at IS NULL
ORDER BY title
`

// Every module a tenant can see: its own tenant-authored modules plus
// every bundled module. Used by the service's ListModules (read path
// for the Modules Library/Defaults/Sources pages).
func (q *Queries) ListVisibleModules(ctx context.Context, tenantID sql.NullInt64) ([]PolicyModule, error) {
	rows, err := q.db.QueryContext(ctx, ListVisibleModules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModule{}
	for rows.Next() {
		var i PolicyModule
		if err := rows.Scan(
			&i.ID,
			&i.ModuleUrn,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.IsBundled,
			&i.CreatedAt,
			&i.OwnerIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MaxVersionConditionSeq = `-- name: MaxVersionConditionSeq :one
SELECT COALESCE(MAX(seq), -1) FROM module_version_conditions
WHERE version_id = ?1
`

func (q *Queries) MaxVersionConditionSeq(ctx context.Context, versionID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, MaxVersionConditionSeq, versionID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const PublishModuleVersion = `-- name: PublishModuleVersion :execrows
UPDATE policy_module_versions SET
    state = 'published',
    published_at = CURRENT_TIMESTAMP,
    published_by = ?1
WHERE id = ?2 AND state = 'draft'
`

type PublishModuleVersionParams struct {
	PublishedBy sql.NullInt64 `json:"published_by"`
	ID          int64         `json:"id"`
}

// State-guarded: only a draft can transition to published. Returns rows
// affected so the service detects a lost race (two concurrent Publishes
// of the same draft: exactly one sees 1 row). Runs inside Publish's
// transaction together with SupersedeCurrentPublishedVersion.
func (q *Queries) PublishModuleVersion(ctx context.Context, arg PublishModuleVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, PublishModuleVersion, arg.PublishedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const RenameModuleScriptGuarded = `-- name: RenameModuleScriptGuarded :execrows
UPDATE policy_module_scripts
SET name = ?1
WHERE version_id = ?2 AND name = ?3
  AND EXISTS (
    SELECT 1 FROM policy_module_versions
    WHERE id = ?2 AND state = 'draft'
  )
`

type RenameModuleScriptGuardedParams struct {
	NewName   string `json:"new_name"`
	VersionID int64  `json:"version_id"`
	OldName   string `json:"old_name"`
}

func (q *Queries) RenameModuleScriptGuarded(ctx context.Context, arg RenameModuleScriptGuardedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, RenameModuleScriptGuarded, arg.NewName, arg.VersionID, arg.OldName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const RestorePolicyModule = `-- name: RestorePolicyModule :execrows
UPDATE policy_modules
SET deleted_at = NULL, deleted_by = NULL
WHERE id = ?1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestorePolicyModule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, RestorePolicyModule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const RevokeModuleVersion = `-- name: RevokeModuleVersion :execrows
UPDATE policy_module_versions SET
    state = 'revoked'
WHERE id = ?1 AND state IN ('published', 'superseded')
`

// State-guarded: only published/superseded versions can be revoked;
// drafts should be deleted instead (the service returns a typed error
// when 0 rows change).
func (q *Queries) RevokeModuleVersion(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, RevokeModuleVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const SearchPolicyModules = `-- name: SearchPolicyModules :many
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin FROM policy_modules
WHERE (tenant_id = ?1 OR is_bundled = TRUE)
  AND deleted_at IS NULL
  AND (title LIKE '%' || ?2 || '%' OR module_urn LIKE '%' || ?2 || '%')
ORDER BY title
LIMIT ?3
`

type SearchPolicyModulesParams struct {
	TenantID sql.NullInt64  `json:"tenant_id"`
	Search   sql.NullString `json:"search"`
	Limit    int64          `json:"limit"`
}

func (q *Queries) SearchPolicyModules(ctx context.Context, arg SearchPolicyModulesParams) ([]PolicyModule, error) {
	rows, err := q.db.QueryContext(ctx, SearchPolicyModules, arg.TenantID, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModule{}
	for rows.Next() {
		var i PolicyModule
		if err := rows.Scan(
			&i.ID,
			&i.ModuleUrn,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.IsBundled,
			&i.CreatedAt,
			&i.OwnerIdentityID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetModuleOrigin = `-- name: SetModuleOrigin :exec
UPDATE policy_modules SET origin = ?1 WHERE id = ?2
`

type SetModuleOriginParams struct {
	Origin string `json:"origin"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetModuleOrigin(ctx context.Context, arg SetModuleOriginParams) error {
	_, err := q.db.ExecContext(ctx, SetModuleOrigin, arg.Origin, arg.ID)
	return err
}

const SetModuleOwner = `-- name: SetModuleOwner :exec
UPDATE policy_modules SET owner_identity_id = ?1 WHERE id = ?2
`

type SetModuleOwnerParams struct {
	OwnerIdentityID sql.NullInt64 `json:"owner_identity_id"`
	ID              int64         `json:"id"`
}

// Sets (or clears, with a NULL @owner_identity_id) the owning identity of
// a module. A module's owner is the identity whose Pluris permissions it
// inherits (see pkg/authz/modules.go). Bundled modules should never have
// an owner set.
func (q *Queries) SetModuleOwner(ctx context.Context, arg SetModuleOwnerParams) error {
	_, err := q.db.ExecContext(ctx, SetModuleOwner, arg.OwnerIdentityID, arg.ID)
	return err
}

const SoftDeletePolicyModule = `-- name: SoftDeletePolicyModule :execrows
UPDATE policy_modules
SET deleted_at = CURRENT_TIMESTAMP, deleted_by = ?1
WHERE id = ?2 AND deleted_at IS NULL
`

type SoftDeletePolicyModuleParams struct {
	DeletedBy interface{} `json:"deleted_by"`
	ID        int64       `json:"id"`
}

func (q *Queries) SoftDeletePolicyModule(ctx context.Context, arg SoftDeletePolicyModuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, SoftDeletePolicyModule, arg.DeletedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const SupersedeCurrentPublishedVersion = `-- name: SupersedeCurrentPublishedVersion :execrows
UPDATE policy_module_versions SET
    state = 'superseded',
    superseded_by_version = ?1
WHERE module_id = ?2 AND state = 'published' AND id != ?3
`

type SupersedeCurrentPublishedVersionParams struct {
	SupersededByVersion sql.NullString `json:"superseded_by_version"`
	ModuleID            int64          `json:"module_id"`
	ExcludeID           int64          `json:"exclude_id"`
}

// Marks whatever is currently published for @module_id (excluding the
// version being published, @exclude_id) superseded by
// @superseded_by_version. One state-guarded statement instead of a
// read-then-update so the "at most one published version per module"
// invariant can't be broken by a writer racing between the read and the
// write. Runs inside Publish's transaction.
func (q *Queries) SupersedeCurrentPublishedVersion(ctx context.Context, arg SupersedeCurrentPublishedVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, SupersedeCurrentPublishedVersion, arg.SupersededByVersion, arg.ModuleID, arg.ExcludeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdatePolicyModule = `-- name: UpdatePolicyModule :one
UPDATE policy_modules SET
    title = ?1,
    description = ?2
WHERE id = ?3
RETURNING id, module_urn, tenant_id, title, description, is_bundled, created_at, owner_identity_id, deleted_at, deleted_by, origin
`

type UpdatePolicyModuleParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdatePolicyModule(ctx context.Context, arg UpdatePolicyModuleParams) (PolicyModule, error) {
	row := q.db.QueryRowContext(ctx, UpdatePolicyModule, arg.Title, arg.Description, arg.ID)
	var i PolicyModule
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
		&i.OwnerIdentityID,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Origin,
	)
	return i, err
}

const UpdatePolicyModuleVersionDraft = `-- name: UpdatePolicyModuleVersionDraft :one
UPDATE policy_module_versions SET
    version = ?1,
    target_os = ?2,
    scope = ?3,
    satisfies = ?4,
    parameters_schema = ?5,
    depends_on = ?6,
    conflicts = ?7,
    sandbox_profile = ?8,
    report_schema = ?9,
    manifest_yaml = ?10
WHERE id = ?11 AND state = 'draft'
RETURNING id, module_id, version, state, target_os, scope, satisfies, parameters_schema, depends_on, conflicts, sandbox_profile, report_schema, manifest_yaml, signature_algo, signature_data, signed_by, published_at, published_by, superseded_by_version, created_at, conditions_match_mode
`

type UpdatePolicyModuleVersionDraftParams struct {
	Version          string         `json:"version"`
	TargetOs         string         `json:"target_os"`
	Scope            string         `json:"scope"`
	Satisfies        string         `json:"satisfies"`
	ParametersSchema sql.NullString `json:"parameters_schema"`
	DependsOn        sql.NullString `json:"depends_on"`
	Conflicts        sql.NullString `json:"conflicts"`
	SandboxProfile   string         `json:"sandbox_profile"`
	ReportSchema     string         `json:"report_schema"`
	ManifestYaml     string         `json:"manifest_yaml"`
	ID               int64          `json:"id"`
}

// Mutates a version's fields. The WHERE state = 'draft' guard makes the
// immutability rule (ADR-007: published/superseded/revoked versions are
// frozen) hold atomically even if a Publish races between the service's
// pre-read and this UPDATE: a non-draft row matches nothing and sqlite's
// RETURNING yields no row (sql.ErrNoRows), which the service maps to
// ErrVersionNotDraft.
func (q *Queries) UpdatePolicyModuleVersionDraft(ctx context.Context, arg UpdatePolicyModuleVersionDraftParams) (PolicyModuleVersion, error) {
	row := q.db.QueryRowContext(ctx, UpdatePolicyModuleVersionDraft,
		arg.Version,
		arg.TargetOs,
		arg.Scope,
		arg.Satisfies,
		arg.ParametersSchema,
		arg.DependsOn,
		arg.Conflicts,
		arg.SandboxProfile,
		arg.ReportSchema,
		arg.ManifestYaml,
		arg.ID,
	)
	var i PolicyModuleVersion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.State,
		&i.TargetOs,
		&i.Scope,
		&i.Satisfies,
		&i.ParametersSchema,
		&i.DependsOn,
		&i.Conflicts,
		&i.SandboxProfile,
		&i.ReportSchema,
		&i.ManifestYaml,
		&i.SignatureAlgo,
		&i.SignatureData,
		&i.SignedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.SupersededByVersion,
		&i.CreatedAt,
		&i.ConditionsMatchMode,
	)
	return i, err
}

const UpdateVersionConditionGuarded = `-- name: UpdateVersionConditionGuarded :execrows
UPDATE module_version_conditions
SET kind = ?1,
    param_path = ?2,
    operator = ?3,
    value_json = ?4,
    script_source = ?5,
    script_ref = ?6
WHERE module_version_conditions.id = ?7 AND version_id = ?8
  AND EXISTS (
    SELECT 1 FROM policy_module_versions v
    WHERE v.id = ?8 AND v.state = 'draft'
  )
`

type UpdateVersionConditionGuardedParams struct {
	Kind         string `json:"kind"`
	ParamPath    string `json:"param_path"`
	Operator     string `json:"operator"`
	ValueJson    string `json:"value_json"`
	ScriptSource string `json:"script_source"`
	ScriptRef    string `json:"script_ref"`
	ID           int64  `json:"id"`
	VersionID    int64  `json:"version_id"`
}

func (q *Queries) UpdateVersionConditionGuarded(ctx context.Context, arg UpdateVersionConditionGuardedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, UpdateVersionConditionGuarded,
		arg.Kind,
		arg.ParamPath,
		arg.Operator,
		arg.ValueJson,
		arg.ScriptSource,
		arg.ScriptRef,
		arg.ID,
		arg.VersionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateVersionConditionsMatchMode = `-- name: UpdateVersionConditionsMatchMode :execrows
UPDATE policy_module_versions
SET conditions_match_mode = ?1
WHERE id = ?2 AND state = 'draft'
`

type UpdateVersionConditionsMatchModeParams struct {
	ConditionsMatchMode string `json:"conditions_match_mode"`
	ID                  int64  `json:"id"`
}

// Draft-guarded in the statement itself, same pattern as the other
// version mutators.
func (q *Queries) UpdateVersionConditionsMatchMode(ctx context.Context, arg UpdateVersionConditionsMatchModeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, UpdateVersionConditionsMatchMode, arg.ConditionsMatchMode, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpsertModuleActionGuarded = `-- name: UpsertModuleActionGuarded :one
INSERT INTO policy_module_actions (version_id, action_key, label, kind, value, origin, seq)
SELECT ?1, ?2, ?3, ?4, ?5, ?6, ?7
WHERE EXISTS (
    SELECT 1 FROM policy_module_versions
    WHERE id = ?1 AND state = 'draft'
)
ON CONFLICT(version_id, action_key) DO UPDATE SET
    label = excluded.label,
    kind = excluded.kind,
    value = excluded.value,
    origin = excluded.origin
RETURNING id, version_id, action_key, label, kind, value, origin, seq
`

type UpsertModuleActionGuardedParams struct {
	VersionID int64  `json:"version_id"`
	ActionKey string `json:"action_key"`
	Label     string `json:"label"`
	Kind      string `json:"kind"`
	Value     string `json:"value"`
	Origin    string `json:"origin"`
	Seq       int64  `json:"seq"`
}

// Insert-or-replace the action identified by (version_id, action_key),
// draft-guarded the same way UpsertModuleScriptGuarded is.
func (q *Queries) UpsertModuleActionGuarded(ctx context.Context, arg UpsertModuleActionGuardedParams) (PolicyModuleAction, error) {
	row := q.db.QueryRowContext(ctx, UpsertModuleActionGuarded,
		arg.VersionID,
		arg.ActionKey,
		arg.Label,
		arg.Kind,
		arg.Value,
		arg.Origin,
		arg.Seq,
	)
	var i PolicyModuleAction
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.ActionKey,
		&i.Label,
		&i.Kind,
		&i.Value,
		&i.Origin,
		&i.Seq,
	)
	return i, err
}

const UpsertModuleScriptGuarded = `-- name: UpsertModuleScriptGuarded :one
INSERT INTO policy_module_scripts (version_id, name, language, source, origin, seq)
SELECT ?1, ?2, ?3, ?4, ?5, ?6
WHERE EXISTS (
    SELECT 1 FROM policy_module_versions
    WHERE id = ?1 AND state = 'draft'
)
ON CONFLICT(version_id, name) DO UPDATE SET
    language = excluded.language,
    source = excluded.source,
    origin = excluded.origin
RETURNING id, version_id, name, language, source, origin, seq
`

type UpsertModuleScriptGuardedParams struct {
	VersionID int64  `json:"version_id"`
	Name      string `json:"name"`
	Language  string `json:"language"`
	Source    string `json:"source"`
	Origin    string `json:"origin"`
	Seq       int64  `json:"seq"`
}

// Insert-or-replace the script identified by (version_id, name), only
// when the target version's state = 'draft'. The WHERE EXISTS subquery
// is evaluated as part of the same atomic INSERT statement (no separate
// read-then-write), so the guard holds even if a Publish races between
// the service's pre-check and this call. When the version isn't a
// draft, the SELECT yields zero rows, nothing is inserted, and
// RETURNING produces no row -- the :one code path surfaces that as
// sql.ErrNoRows, which the service maps to the typed ErrVersionNotDraft.
func (q *Queries) UpsertModuleScriptGuarded(ctx context.Context, arg UpsertModuleScriptGuardedParams) (PolicyModuleScript, error) {
	row := q.db.QueryRowContext(ctx, UpsertModuleScriptGuarded,
		arg.VersionID,
		arg.Name,
		arg.Language,
		arg.Source,
		arg.Origin,
		arg.Seq,
	)
	var i PolicyModuleScript
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Name,
		&i.Language,
		&i.Source,
		&i.Origin,
		&i.Seq,
	)
	return i, err
}
