// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: policy_modules.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CountPolicyModulesByTenant = `-- name: CountPolicyModulesByTenant :one
SELECT COUNT(*) FROM policy_modules WHERE tenant_id = ?1
`

func (q *Queries) CountPolicyModulesByTenant(ctx context.Context, tenantID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPolicyModulesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountVersionsByModule = `-- name: CountVersionsByModule :one
SELECT COUNT(*) FROM policy_module_versions WHERE module_id = ?1
`

func (q *Queries) CountVersionsByModule(ctx context.Context, moduleID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountVersionsByModule, moduleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreatePolicyModule = `-- name: CreatePolicyModule :one

INSERT INTO policy_modules (
    module_urn,
    tenant_id,
    title,
    description,
    is_bundled
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
) RETURNING id, module_urn, tenant_id, title, description, is_bundled, created_at
`

type CreatePolicyModuleParams struct {
	ModuleUrn   string         `json:"module_urn"`
	TenantID    sql.NullInt64  `json:"tenant_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	IsBundled   bool           `json:"is_bundled"`
}

// Policy module queries
// Policy modules are versioned, signed policy definitions
func (q *Queries) CreatePolicyModule(ctx context.Context, arg CreatePolicyModuleParams) (PolicyModule, error) {
	row := q.db.QueryRowContext(ctx, CreatePolicyModule,
		arg.ModuleUrn,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.IsBundled,
	)
	var i PolicyModule
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
	)
	return i, err
}

const CreatePolicyModuleVersion = `-- name: CreatePolicyModuleVersion :one

INSERT INTO policy_module_versions (
    module_id,
    version,
    state,
    manifest_yaml,
    target_os,
    scope,
    runtime,
    satisfies,
    parameters_schema,
    depends_on,
    conflicts,
    enforce_script,
    validate_script,
    rollback_script
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14
) RETURNING id, module_id, version, state, manifest_yaml, target_os, scope, runtime, satisfies, parameters_schema, depends_on, conflicts, enforce_script, validate_script, rollback_script, signature_algo, signature_data, signed_by, published_at, published_by, superseded_by_version, created_at
`

type CreatePolicyModuleVersionParams struct {
	ModuleID         int64          `json:"module_id"`
	Version          string         `json:"version"`
	State            string         `json:"state"`
	ManifestYaml     string         `json:"manifest_yaml"`
	TargetOs         string         `json:"target_os"`
	Scope            string         `json:"scope"`
	Runtime          string         `json:"runtime"`
	Satisfies        string         `json:"satisfies"`
	ParametersSchema sql.NullString `json:"parameters_schema"`
	DependsOn        sql.NullString `json:"depends_on"`
	Conflicts        sql.NullString `json:"conflicts"`
	EnforceScript    string         `json:"enforce_script"`
	ValidateScript   sql.NullString `json:"validate_script"`
	RollbackScript   sql.NullString `json:"rollback_script"`
}

// ============================================================================
// Policy Module Versions
// ============================================================================
func (q *Queries) CreatePolicyModuleVersion(ctx context.Context, arg CreatePolicyModuleVersionParams) (PolicyModuleVersion, error) {
	row := q.db.QueryRowContext(ctx, CreatePolicyModuleVersion,
		arg.ModuleID,
		arg.Version,
		arg.State,
		arg.ManifestYaml,
		arg.TargetOs,
		arg.Scope,
		arg.Runtime,
		arg.Satisfies,
		arg.ParametersSchema,
		arg.DependsOn,
		arg.Conflicts,
		arg.EnforceScript,
		arg.ValidateScript,
		arg.RollbackScript,
	)
	var i PolicyModuleVersion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.State,
		&i.ManifestYaml,
		&i.TargetOs,
		&i.Scope,
		&i.Runtime,
		&i.Satisfies,
		&i.ParametersSchema,
		&i.DependsOn,
		&i.Conflicts,
		&i.EnforceScript,
		&i.ValidateScript,
		&i.RollbackScript,
		&i.SignatureAlgo,
		&i.SignatureData,
		&i.SignedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.SupersededByVersion,
		&i.CreatedAt,
	)
	return i, err
}

const DeletePolicyModule = `-- name: DeletePolicyModule :exec
DELETE FROM policy_modules WHERE id = ?1
`

func (q *Queries) DeletePolicyModule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeletePolicyModule, id)
	return err
}

const DeletePolicyModuleVersion = `-- name: DeletePolicyModuleVersion :exec
DELETE FROM policy_module_versions WHERE id = ?1
`

func (q *Queries) DeletePolicyModuleVersion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeletePolicyModuleVersion, id)
	return err
}

const GetLatestPublishedVersion = `-- name: GetLatestPublishedVersion :one
SELECT id, module_id, version, state, manifest_yaml, target_os, scope, runtime, satisfies, parameters_schema, depends_on, conflicts, enforce_script, validate_script, rollback_script, signature_algo, signature_data, signed_by, published_at, published_by, superseded_by_version, created_at FROM policy_module_versions 
WHERE module_id = ?1 AND state = 'published'
ORDER BY published_at DESC 
LIMIT 1
`

func (q *Queries) GetLatestPublishedVersion(ctx context.Context, moduleID int64) (PolicyModuleVersion, error) {
	row := q.db.QueryRowContext(ctx, GetLatestPublishedVersion, moduleID)
	var i PolicyModuleVersion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.State,
		&i.ManifestYaml,
		&i.TargetOs,
		&i.Scope,
		&i.Runtime,
		&i.Satisfies,
		&i.ParametersSchema,
		&i.DependsOn,
		&i.Conflicts,
		&i.EnforceScript,
		&i.ValidateScript,
		&i.RollbackScript,
		&i.SignatureAlgo,
		&i.SignatureData,
		&i.SignedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.SupersededByVersion,
		&i.CreatedAt,
	)
	return i, err
}

const GetModuleWithLatestVersion = `-- name: GetModuleWithLatestVersion :one
SELECT 
    m.id, m.module_urn, m.tenant_id, m.title, m.description, m.is_bundled, m.created_at,
    v.id as latest_version_id,
    v.version as latest_version,
    v.published_at as latest_published_at
FROM policy_modules m
LEFT JOIN policy_module_versions v ON v.module_id = m.id AND v.state = 'published'
WHERE m.id = ?1
ORDER BY v.published_at DESC
LIMIT 1
`

type GetModuleWithLatestVersionRow struct {
	ID                int64          `json:"id"`
	ModuleUrn         string         `json:"module_urn"`
	TenantID          sql.NullInt64  `json:"tenant_id"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	IsBundled         bool           `json:"is_bundled"`
	CreatedAt         time.Time      `json:"created_at"`
	LatestVersionID   sql.NullInt64  `json:"latest_version_id"`
	LatestVersion     sql.NullString `json:"latest_version"`
	LatestPublishedAt sql.NullTime   `json:"latest_published_at"`
}

func (q *Queries) GetModuleWithLatestVersion(ctx context.Context, id int64) (GetModuleWithLatestVersionRow, error) {
	row := q.db.QueryRowContext(ctx, GetModuleWithLatestVersion, id)
	var i GetModuleWithLatestVersionRow
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
		&i.LatestVersionID,
		&i.LatestVersion,
		&i.LatestPublishedAt,
	)
	return i, err
}

const GetPolicyModule = `-- name: GetPolicyModule :one
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at FROM policy_modules WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetPolicyModule(ctx context.Context, id int64) (PolicyModule, error) {
	row := q.db.QueryRowContext(ctx, GetPolicyModule, id)
	var i PolicyModule
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
	)
	return i, err
}

const GetPolicyModuleByURN = `-- name: GetPolicyModuleByURN :one
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at FROM policy_modules 
WHERE module_urn = ?1 
LIMIT 1
`

func (q *Queries) GetPolicyModuleByURN(ctx context.Context, moduleUrn string) (PolicyModule, error) {
	row := q.db.QueryRowContext(ctx, GetPolicyModuleByURN, moduleUrn)
	var i PolicyModule
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
	)
	return i, err
}

const GetPolicyModuleVersion = `-- name: GetPolicyModuleVersion :one
SELECT id, module_id, version, state, manifest_yaml, target_os, scope, runtime, satisfies, parameters_schema, depends_on, conflicts, enforce_script, validate_script, rollback_script, signature_algo, signature_data, signed_by, published_at, published_by, superseded_by_version, created_at FROM policy_module_versions WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetPolicyModuleVersion(ctx context.Context, id int64) (PolicyModuleVersion, error) {
	row := q.db.QueryRowContext(ctx, GetPolicyModuleVersion, id)
	var i PolicyModuleVersion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.State,
		&i.ManifestYaml,
		&i.TargetOs,
		&i.Scope,
		&i.Runtime,
		&i.Satisfies,
		&i.ParametersSchema,
		&i.DependsOn,
		&i.Conflicts,
		&i.EnforceScript,
		&i.ValidateScript,
		&i.RollbackScript,
		&i.SignatureAlgo,
		&i.SignatureData,
		&i.SignedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.SupersededByVersion,
		&i.CreatedAt,
	)
	return i, err
}

const GetPolicyModuleVersionByNumber = `-- name: GetPolicyModuleVersionByNumber :one
SELECT id, module_id, version, state, manifest_yaml, target_os, scope, runtime, satisfies, parameters_schema, depends_on, conflicts, enforce_script, validate_script, rollback_script, signature_algo, signature_data, signed_by, published_at, published_by, superseded_by_version, created_at FROM policy_module_versions 
WHERE module_id = ?1 AND version = ?2 
LIMIT 1
`

type GetPolicyModuleVersionByNumberParams struct {
	ModuleID int64  `json:"module_id"`
	Version  string `json:"version"`
}

func (q *Queries) GetPolicyModuleVersionByNumber(ctx context.Context, arg GetPolicyModuleVersionByNumberParams) (PolicyModuleVersion, error) {
	row := q.db.QueryRowContext(ctx, GetPolicyModuleVersionByNumber, arg.ModuleID, arg.Version)
	var i PolicyModuleVersion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.State,
		&i.ManifestYaml,
		&i.TargetOs,
		&i.Scope,
		&i.Runtime,
		&i.Satisfies,
		&i.ParametersSchema,
		&i.DependsOn,
		&i.Conflicts,
		&i.EnforceScript,
		&i.ValidateScript,
		&i.RollbackScript,
		&i.SignatureAlgo,
		&i.SignatureData,
		&i.SignedBy,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.SupersededByVersion,
		&i.CreatedAt,
	)
	return i, err
}

const ListBundledModules = `-- name: ListBundledModules :many
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at FROM policy_modules 
WHERE is_bundled = TRUE
ORDER BY title
`

func (q *Queries) ListBundledModules(ctx context.Context) ([]PolicyModule, error) {
	rows, err := q.db.QueryContext(ctx, ListBundledModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModule{}
	for rows.Next() {
		var i PolicyModule
		if err := rows.Scan(
			&i.ID,
			&i.ModuleUrn,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.IsBundled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPolicyModulesByTenant = `-- name: ListPolicyModulesByTenant :many
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at FROM policy_modules 
WHERE tenant_id = ?1 
ORDER BY title
LIMIT ?3 OFFSET ?2
`

type ListPolicyModulesByTenantParams struct {
	TenantID sql.NullInt64 `json:"tenant_id"`
	Offset   int64         `json:"offset"`
	Limit    int64         `json:"limit"`
}

func (q *Queries) ListPolicyModulesByTenant(ctx context.Context, arg ListPolicyModulesByTenantParams) ([]PolicyModule, error) {
	rows, err := q.db.QueryContext(ctx, ListPolicyModulesByTenant, arg.TenantID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModule{}
	for rows.Next() {
		var i PolicyModule
		if err := rows.Scan(
			&i.ID,
			&i.ModuleUrn,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.IsBundled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListVersionsByModule = `-- name: ListVersionsByModule :many
SELECT v.id, v.module_id, v.version, v.state, v.manifest_yaml, v.target_os, v.scope, v.runtime, v.satisfies, v.parameters_schema, v.depends_on, v.conflicts, v.enforce_script, v.validate_script, v.rollback_script, v.signature_algo, v.signature_data, v.signed_by, v.published_at, v.published_by, v.superseded_by_version, v.created_at, i.display_name as publisher_name
FROM policy_module_versions v
LEFT JOIN identities i ON i.id = v.published_by
WHERE v.module_id = ?1
ORDER BY v.created_at DESC
`

type ListVersionsByModuleRow struct {
	ID                  int64          `json:"id"`
	ModuleID            int64          `json:"module_id"`
	Version             string         `json:"version"`
	State               string         `json:"state"`
	ManifestYaml        string         `json:"manifest_yaml"`
	TargetOs            string         `json:"target_os"`
	Scope               string         `json:"scope"`
	Runtime             string         `json:"runtime"`
	Satisfies           string         `json:"satisfies"`
	ParametersSchema    sql.NullString `json:"parameters_schema"`
	DependsOn           sql.NullString `json:"depends_on"`
	Conflicts           sql.NullString `json:"conflicts"`
	EnforceScript       string         `json:"enforce_script"`
	ValidateScript      sql.NullString `json:"validate_script"`
	RollbackScript      sql.NullString `json:"rollback_script"`
	SignatureAlgo       sql.NullString `json:"signature_algo"`
	SignatureData       sql.NullString `json:"signature_data"`
	SignedBy            sql.NullString `json:"signed_by"`
	PublishedAt         sql.NullTime   `json:"published_at"`
	PublishedBy         sql.NullInt64  `json:"published_by"`
	SupersededByVersion sql.NullString `json:"superseded_by_version"`
	CreatedAt           time.Time      `json:"created_at"`
	PublisherName       sql.NullString `json:"publisher_name"`
}

func (q *Queries) ListVersionsByModule(ctx context.Context, moduleID int64) ([]ListVersionsByModuleRow, error) {
	rows, err := q.db.QueryContext(ctx, ListVersionsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVersionsByModuleRow{}
	for rows.Next() {
		var i ListVersionsByModuleRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.Version,
			&i.State,
			&i.ManifestYaml,
			&i.TargetOs,
			&i.Scope,
			&i.Runtime,
			&i.Satisfies,
			&i.ParametersSchema,
			&i.DependsOn,
			&i.Conflicts,
			&i.EnforceScript,
			&i.ValidateScript,
			&i.RollbackScript,
			&i.SignatureAlgo,
			&i.SignatureData,
			&i.SignedBy,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.SupersededByVersion,
			&i.CreatedAt,
			&i.PublisherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const PublishModuleVersion = `-- name: PublishModuleVersion :exec
UPDATE policy_module_versions SET
    state = 'published',
    published_at = CURRENT_TIMESTAMP,
    published_by = ?1
WHERE id = ?2
`

type PublishModuleVersionParams struct {
	PublishedBy sql.NullInt64 `json:"published_by"`
	ID          int64         `json:"id"`
}

func (q *Queries) PublishModuleVersion(ctx context.Context, arg PublishModuleVersionParams) error {
	_, err := q.db.ExecContext(ctx, PublishModuleVersion, arg.PublishedBy, arg.ID)
	return err
}

const RevokeModuleVersion = `-- name: RevokeModuleVersion :exec
UPDATE policy_module_versions SET
    state = 'revoked'
WHERE id = ?1
`

func (q *Queries) RevokeModuleVersion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, RevokeModuleVersion, id)
	return err
}

const SearchPolicyModules = `-- name: SearchPolicyModules :many
SELECT id, module_urn, tenant_id, title, description, is_bundled, created_at FROM policy_modules
WHERE (tenant_id = ?1 OR is_bundled = TRUE)
  AND (title LIKE '%' || ?2 || '%' OR module_urn LIKE '%' || ?2 || '%')
ORDER BY title
LIMIT ?3
`

type SearchPolicyModulesParams struct {
	TenantID sql.NullInt64  `json:"tenant_id"`
	Search   sql.NullString `json:"search"`
	Limit    int64          `json:"limit"`
}

func (q *Queries) SearchPolicyModules(ctx context.Context, arg SearchPolicyModulesParams) ([]PolicyModule, error) {
	rows, err := q.db.QueryContext(ctx, SearchPolicyModules, arg.TenantID, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyModule{}
	for rows.Next() {
		var i PolicyModule
		if err := rows.Scan(
			&i.ID,
			&i.ModuleUrn,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.IsBundled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdatePolicyModule = `-- name: UpdatePolicyModule :one
UPDATE policy_modules SET
    title = ?1,
    description = ?2
WHERE id = ?3
RETURNING id, module_urn, tenant_id, title, description, is_bundled, created_at
`

type UpdatePolicyModuleParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdatePolicyModule(ctx context.Context, arg UpdatePolicyModuleParams) (PolicyModule, error) {
	row := q.db.QueryRowContext(ctx, UpdatePolicyModule, arg.Title, arg.Description, arg.ID)
	var i PolicyModule
	err := row.Scan(
		&i.ID,
		&i.ModuleUrn,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.IsBundled,
		&i.CreatedAt,
	)
	return i, err
}
