// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// ============================================================================
	// Group membership operations
	// ============================================================================
	AddAssetToGroup(ctx context.Context, arg AddAssetToGroupParams) error
	AddIdentityToGroup(ctx context.Context, arg AddIdentityToGroupParams) error
	AssignRoleToIdentity(ctx context.Context, arg AssignRoleToIdentityParams) error
	ClearAssetOwner(ctx context.Context, id int64) error
	ClearGroupMembers(ctx context.Context, groupID int64) error
	CountAssetsByEnrollmentState(ctx context.Context, arg CountAssetsByEnrollmentStateParams) (int64, error)
	CountAssetsBySubtype(ctx context.Context, arg CountAssetsBySubtypeParams) (int64, error)
	CountAssetsByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountAssetsInGroup(ctx context.Context, groupID int64) (int64, error)
	CountAssignmentsByGroup(ctx context.Context, configurationGroupID int64) (int64, error)
	CountConfigurationGroupsByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountCustomPoliciesByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountGroupsByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountIdentitiesByTenant(ctx context.Context, tenantID int64) (int64, error)
	// Used by the setup-gate middleware: "does any identity exist anywhere?"
	CountIdentitiesGlobal(ctx context.Context) (int64, error)
	CountIdentitiesInGroup(ctx context.Context, groupID int64) (int64, error)
	CountInstallationsByAsset(ctx context.Context, assetID int64) (int64, error)
	CountInstallationsByModule(ctx context.Context, moduleID int64) (int64, error)
	CountInstallationsByState(ctx context.Context, state string) (int64, error)
	CountLinksForAsset(ctx context.Context, assetID int64) (int64, error)
	CountPolicyModulesByTenant(ctx context.Context, tenantID sql.NullInt64) (int64, error)
	CountSitesByTenant(ctx context.Context, tenantID int64) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CountVersionsByModule(ctx context.Context, moduleID int64) (int64, error)
	// Asset CRUD operations
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	// Asset link queries
	// Asset links define relationships between assets (e.g., desk-to-computer, server-to-server)
	CreateAssetLink(ctx context.Context, arg CreateAssetLinkParams) (AssetLink, error)
	// Configuration group queries
	// Configuration groups bundle policy bindings for assignment
	CreateConfigurationGroup(ctx context.Context, arg CreateConfigurationGroupParams) (ConfigurationGroup, error)
	// ============================================================================
	// Configuration Group Assignments (who gets a group)
	// ============================================================================
	CreateConfigurationGroupAssignment(ctx context.Context, arg CreateConfigurationGroupAssignmentParams) (ConfigurationGroupAssignment, error)
	// ============================================================================
	// Configuration Group Bindings (which policies are in a group)
	// ============================================================================
	CreateConfigurationGroupBinding(ctx context.Context, arg CreateConfigurationGroupBindingParams) (ConfigurationGroupBinding, error)
	// Custom policy queries
	// Custom policies are tenant-specific policy definitions (not from bundled catalog)
	CreateCustomPolicy(ctx context.Context, arg CreateCustomPolicyParams) (CustomPolicy, error)
	// ============================================================================
	// Group operations
	// ============================================================================
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	// Identity management queries - matches the schema in
	// db/schema/002_identity_ad_compat.sql. Identities are both the
	// end-user directory (owner of assets) and the accounts that log into
	// the console (role-gated).
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error)
	// Server-side session queries. The raw session token is never stored -
	// only its SHA-256 hash (token_hash). See pkg/auth/session.go (a later task).
	CreateIdentitySession(ctx context.Context, arg CreateIdentitySessionParams) (IdentitySession, error)
	// ============================================================================
	// Module Installation Dependencies
	// ============================================================================
	CreateInstallationDependency(ctx context.Context, arg CreateInstallationDependencyParams) (ModuleInstallationDependency, error)
	// Installed software queries - per asset software inventory backed by
	// the installed_software table in db/schema/003_roles_software_logs.sql.
	CreateInstalledSoftware(ctx context.Context, arg CreateInstalledSoftwareParams) (InstalledSoftware, error)
	// Module installation queries
	// Tracks which policy modules are installed on which assets
	CreateModuleInstallation(ctx context.Context, arg CreateModuleInstallationParams) (ModuleInstallation, error)
	// Policy module queries
	// Policy modules are versioned, signed policy definitions
	CreatePolicyModule(ctx context.Context, arg CreatePolicyModuleParams) (PolicyModule, error)
	// ============================================================================
	// Policy Module Versions
	// ============================================================================
	CreatePolicyModuleVersion(ctx context.Context, arg CreatePolicyModuleVersionParams) (PolicyModuleVersion, error)
	// Role queries - matches the roles and identity_roles tables in
	// db/schema/003_roles_software_logs.sql. Roles are per tenant RBAC
	// definitions beyond the builtin identities.role slugs; identity_roles
	// links them to identities.
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// ============================================================================
	// Site operations
	// ============================================================================
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	// Tenant operations
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteAsset(ctx context.Context, id int64) error
	DeleteAssetLink(ctx context.Context, id int64) error
	DeleteAssignmentsByGroup(ctx context.Context, configurationGroupID int64) error
	DeleteAssignmentsByTarget(ctx context.Context, arg DeleteAssignmentsByTargetParams) error
	DeleteBindingsByGroup(ctx context.Context, configurationGroupID int64) error
	DeleteConfigurationGroup(ctx context.Context, id int64) error
	DeleteConfigurationGroupAssignment(ctx context.Context, id int64) error
	DeleteConfigurationGroupBinding(ctx context.Context, id int64) error
	DeleteCustomPolicy(ctx context.Context, id int64) error
	DeleteDependenciesForInstallation(ctx context.Context, installationID int64) error
	DeleteDependenciesOnInstallation(ctx context.Context, installationID int64) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteGroup(ctx context.Context, id int64) error
	DeleteIdentity(ctx context.Context, id int64) error
	DeleteInstallationDependency(ctx context.Context, id int64) error
	DeleteInstallationsByAsset(ctx context.Context, assetID int64) error
	DeleteInstallationsByModule(ctx context.Context, moduleID int64) error
	DeleteLinksByRelation(ctx context.Context, arg DeleteLinksByRelationParams) error
	DeleteLinksForAsset(ctx context.Context, assetID int64) error
	DeleteModuleInstallation(ctx context.Context, id int64) error
	DeletePolicyModule(ctx context.Context, id int64) error
	DeletePolicyModuleVersion(ctx context.Context, id int64) error
	DeleteSite(ctx context.Context, id int64) error
	DeleteTenant(ctx context.Context, id int64) error
	GetActiveSessionByTokenHash(ctx context.Context, tokenHash string) (IdentitySession, error)
	GetAsset(ctx context.Context, id int64) (Asset, error)
	GetAssetByHumanID(ctx context.Context, humanID sql.NullString) (GetAssetByHumanIDRow, error)
	GetAssetByUUID(ctx context.Context, uuid string) (Asset, error)
	GetAssetLink(ctx context.Context, id int64) (AssetLink, error)
	GetAssetLinkByAssets(ctx context.Context, arg GetAssetLinkByAssetsParams) (AssetLink, error)
	// Summary statistics for dashboard
	GetAssetStatsByTenant(ctx context.Context, tenantID int64) (GetAssetStatsByTenantRow, error)
	GetAssetWithRelations(ctx context.Context, id int64) (GetAssetWithRelationsRow, error)
	GetBindingByGroupAndPolicy(ctx context.Context, arg GetBindingByGroupAndPolicyParams) (ConfigurationGroupBinding, error)
	GetConfigurationGroup(ctx context.Context, id int64) (ConfigurationGroup, error)
	GetConfigurationGroupAssignment(ctx context.Context, id int64) (ConfigurationGroupAssignment, error)
	GetConfigurationGroupBinding(ctx context.Context, id int64) (ConfigurationGroupBinding, error)
	GetConfigurationGroupByName(ctx context.Context, arg GetConfigurationGroupByNameParams) (ConfigurationGroup, error)
	GetCustomPolicy(ctx context.Context, id int64) (CustomPolicy, error)
	GetCustomPolicyByURN(ctx context.Context, arg GetCustomPolicyByURNParams) (CustomPolicy, error)
	GetGroup(ctx context.Context, id int64) (Group, error)
	GetGroupBySlug(ctx context.Context, arg GetGroupBySlugParams) (Group, error)
	GetIdentity(ctx context.Context, id int64) (Identity, error)
	GetIdentityByEmail(ctx context.Context, arg GetIdentityByEmailParams) (Identity, error)
	// Used at login: the user only enters an email, not a tenant, so this
	// resolves across all tenants. Returns 0, 1, or (in the rare case two
	// tenants share an email) more than 1 row - callers MUST check the
	// length and treat >1 as an ambiguous-account error, never just take
	// the first result.
	GetIdentityByEmailGlobal(ctx context.Context, email string) ([]Identity, error)
	GetInstallationByAssetAndModule(ctx context.Context, arg GetInstallationByAssetAndModuleParams) (ModuleInstallation, error)
	GetLatestPublishedVersion(ctx context.Context, moduleID int64) (PolicyModuleVersion, error)
	GetModuleInstallation(ctx context.Context, id int64) (ModuleInstallation, error)
	GetModuleWithLatestVersion(ctx context.Context, id int64) (GetModuleWithLatestVersionRow, error)
	GetPolicyModule(ctx context.Context, id int64) (PolicyModule, error)
	GetPolicyModuleByURN(ctx context.Context, moduleUrn string) (PolicyModule, error)
	GetPolicyModuleVersion(ctx context.Context, id int64) (PolicyModuleVersion, error)
	GetPolicyModuleVersionByNumber(ctx context.Context, arg GetPolicyModuleVersionByNumberParams) (PolicyModuleVersion, error)
	GetRole(ctx context.Context, id int64) (Role, error)
	GetRoleBySlug(ctx context.Context, arg GetRoleBySlugParams) (Role, error)
	GetSite(ctx context.Context, id int64) (Site, error)
	GetSiteBySlug(ctx context.Context, arg GetSiteBySlugParams) (Site, error)
	GetTenant(ctx context.Context, id int64) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	// Activity log queries - generic per entity event feed backed by the
	// activity_log table in db/schema/003_roles_software_logs.sql.
	InsertActivity(ctx context.Context, arg InsertActivityParams) error
	// Audit trail for authentication and identity-management events.
	InsertIdentityAuditLog(ctx context.Context, arg InsertIdentityAuditLogParams) error
	IsAssetInGroup(ctx context.Context, arg IsAssetInGroupParams) (int64, error)
	IsIdentityInGroup(ctx context.Context, arg IsIdentityInGroupParams) (int64, error)
	ListActivityForEntity(ctx context.Context, arg ListActivityForEntityParams) ([]ActivityLog, error)
	ListAllLinksForAsset(ctx context.Context, assetID int64) ([]ListAllLinksForAssetRow, error)
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error)
	// Filter assets by enrollment state
	ListAssetsByEnrollmentState(ctx context.Context, arg ListAssetsByEnrollmentStateParams) ([]Asset, error)
	// Get assets by lifecycle state
	ListAssetsByLifecycleState(ctx context.Context, arg ListAssetsByLifecycleStateParams) ([]Asset, error)
	ListAssetsByOwner(ctx context.Context, arg ListAssetsByOwnerParams) ([]Asset, error)
	ListAssetsBySite(ctx context.Context, arg ListAssetsBySiteParams) ([]Asset, error)
	ListAssetsBySubtype(ctx context.Context, arg ListAssetsBySubtypeParams) ([]ListAssetsBySubtypeRow, error)
	ListAssetsInGroup(ctx context.Context, groupID int64) ([]Asset, error)
	ListAssignmentsByGroup(ctx context.Context, configurationGroupID int64) ([]ConfigurationGroupAssignment, error)
	ListAssignmentsByTarget(ctx context.Context, arg ListAssignmentsByTargetParams) ([]ListAssignmentsByTargetRow, error)
	ListBindingsByGroup(ctx context.Context, configurationGroupID int64) ([]ListBindingsByGroupRow, error)
	ListBindingsByModule(ctx context.Context, moduleID sql.NullInt64) ([]ListBindingsByModuleRow, error)
	ListBundledModules(ctx context.Context) ([]PolicyModule, error)
	ListConfigGroupsForAsset(ctx context.Context, arg ListConfigGroupsForAssetParams) ([]ConfigurationGroup, error)
	ListConfigurationGroupsByTenant(ctx context.Context, arg ListConfigurationGroupsByTenantParams) ([]ConfigurationGroup, error)
	ListCustomPoliciesByCategory(ctx context.Context, arg ListCustomPoliciesByCategoryParams) ([]CustomPolicy, error)
	ListCustomPoliciesByScope(ctx context.Context, arg ListCustomPoliciesByScopeParams) ([]CustomPolicy, error)
	ListCustomPoliciesByTenant(ctx context.Context, arg ListCustomPoliciesByTenantParams) ([]CustomPolicy, error)
	ListDependenciesForInstallation(ctx context.Context, installationID int64) ([]ListDependenciesForInstallationRow, error)
	ListDependentsOfInstallation(ctx context.Context, installationID int64) ([]ListDependentsOfInstallationRow, error)
	ListEnabledConfigurationGroups(ctx context.Context, tenantID int64) ([]ConfigurationGroup, error)
	ListFailingInstallations(ctx context.Context, limit int64) ([]ListFailingInstallationsRow, error)
	ListGroupsBySite(ctx context.Context, arg ListGroupsBySiteParams) ([]Group, error)
	ListGroupsByTenant(ctx context.Context, tenantID int64) ([]Group, error)
	ListGroupsForAsset(ctx context.Context, assetID sql.NullInt64) ([]Group, error)
	// Group rows for the detail page Groups tabs (Task 9). Same joins as
	// ListGroupsForAsset and ListGroupsForIdentity but each row also carries
	// the membership creation time so the UI can show when the entity was
	// added to the group.
	ListGroupsForAssetDetail(ctx context.Context, assetID sql.NullInt64) ([]ListGroupsForAssetDetailRow, error)
	ListGroupsForIdentity(ctx context.Context, identityID sql.NullInt64) ([]Group, error)
	ListGroupsForIdentityDetail(ctx context.Context, identityID sql.NullInt64) ([]ListGroupsForIdentityDetailRow, error)
	ListIdentitiesByTenant(ctx context.Context, arg ListIdentitiesByTenantParams) ([]Identity, error)
	ListIdentitiesInGroup(ctx context.Context, groupID int64) ([]Identity, error)
	ListIdentityAuditLogByTenant(ctx context.Context, arg ListIdentityAuditLogByTenantParams) ([]IdentityAuditLog, error)
	ListInstallationsByAsset(ctx context.Context, assetID int64) ([]ListInstallationsByAssetRow, error)
	ListInstallationsByModule(ctx context.Context, moduleID int64) ([]ListInstallationsByModuleRow, error)
	ListInstallationsByState(ctx context.Context, arg ListInstallationsByStateParams) ([]ListInstallationsByStateRow, error)
	ListLinksByRelation(ctx context.Context, arg ListLinksByRelationParams) ([]ListLinksByRelationRow, error)
	ListLinksFromAsset(ctx context.Context, fromAssetID int64) ([]ListLinksFromAssetRow, error)
	ListLinksToAsset(ctx context.Context, toAssetID int64) ([]ListLinksToAssetRow, error)
	ListPendingInstallations(ctx context.Context, limit int64) ([]ListPendingInstallationsRow, error)
	ListPolicyModulesByTenant(ctx context.Context, arg ListPolicyModulesByTenantParams) ([]PolicyModule, error)
	ListRolesByTenant(ctx context.Context, tenantID int64) ([]Role, error)
	ListRolesForIdentity(ctx context.Context, identityID int64) ([]Role, error)
	// Role rows for the user detail Roles tab (Task 11). Same join as
	// ListRolesForIdentity but carries the assignment time.
	ListRolesForIdentityDetail(ctx context.Context, identityID int64) ([]ListRolesForIdentityDetailRow, error)
	ListSitesByTenant(ctx context.Context, tenantID int64) ([]Site, error)
	ListSoftwareForAsset(ctx context.Context, assetID int64) ([]InstalledSoftware, error)
	// Get assets not seen since a timestamp (stale)
	ListStaleAssets(ctx context.Context, arg ListStaleAssetsParams) ([]Asset, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListVersionsByModule(ctx context.Context, moduleID int64) ([]ListVersionsByModuleRow, error)
	LockIdentityIfThresholdExceeded(ctx context.Context, arg LockIdentityIfThresholdExceededParams) error
	PublishModuleVersion(ctx context.Context, arg PublishModuleVersionParams) error
	RecordLoginFailure(ctx context.Context, id int64) error
	RecordLoginSuccess(ctx context.Context, id int64) error
	RemoveAssetFromGroup(ctx context.Context, arg RemoveAssetFromGroupParams) error
	RemoveIdentityFromGroup(ctx context.Context, arg RemoveIdentityFromGroupParams) error
	RemoveRoleFromIdentity(ctx context.Context, arg RemoveRoleFromIdentityParams) error
	RevokeModuleVersion(ctx context.Context, id int64) error
	RevokeSession(ctx context.Context, tokenHash string) error
	// Search assets across multiple fields
	SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]SearchAssetsRow, error)
	// Search assets by JSON payload fields (hostname)
	SearchAssetsByHostname(ctx context.Context, arg SearchAssetsByHostnameParams) ([]Asset, error)
	SearchConfigurationGroups(ctx context.Context, arg SearchConfigurationGroupsParams) ([]ConfigurationGroup, error)
	SearchCustomPolicies(ctx context.Context, arg SearchCustomPoliciesParams) ([]CustomPolicy, error)
	SearchGroups(ctx context.Context, arg SearchGroupsParams) ([]Group, error)
	SearchIdentities(ctx context.Context, arg SearchIdentitiesParams) ([]Identity, error)
	SearchPolicyModules(ctx context.Context, arg SearchPolicyModulesParams) ([]PolicyModule, error)
	SetAssetDescription(ctx context.Context, arg SetAssetDescriptionParams) error
	SetAssetManagedBy(ctx context.Context, arg SetAssetManagedByParams) error
	// Narrow, single-column update: unlike UpdateAsset (which requires
	// re-supplying site_id/subtype_payload/labels), this only ever touches
	// ownership so callers cannot accidentally clobber unrelated fields.
	SetAssetOwner(ctx context.Context, arg SetAssetOwnerParams) error
	SetIdentityEnabled(ctx context.Context, arg SetIdentityEnabledParams) error
	SetIdentityLocked(ctx context.Context, arg SetIdentityLockedParams) error
	SetIdentityPasswordHash(ctx context.Context, arg SetIdentityPasswordHashParams) error
	SetSessionActiveTenant(ctx context.Context, arg SetSessionActiveTenantParams) error
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error)
	UpdateAssetCMDB(ctx context.Context, arg UpdateAssetCMDBParams) error
	UpdateAssetEnrollmentState(ctx context.Context, arg UpdateAssetEnrollmentStateParams) error
	UpdateAssetLastSeen(ctx context.Context, arg UpdateAssetLastSeenParams) error
	UpdateAssetLink(ctx context.Context, arg UpdateAssetLinkParams) (AssetLink, error)
	// Superseded by SetAssetOwner for new call sites (added in the owner-pairing
	// task); kept as-is here to avoid unrelated churn, not because both are needed.
	UpdateAssetOwner(ctx context.Context, arg UpdateAssetOwnerParams) error
	UpdateAssetPayload(ctx context.Context, arg UpdateAssetPayloadParams) error
	UpdateAssetSite(ctx context.Context, arg UpdateAssetSiteParams) error
	UpdateConfigurationGroup(ctx context.Context, arg UpdateConfigurationGroupParams) (ConfigurationGroup, error)
	UpdateConfigurationGroupBinding(ctx context.Context, arg UpdateConfigurationGroupBindingParams) (ConfigurationGroupBinding, error)
	UpdateCustomPolicy(ctx context.Context, arg UpdateCustomPolicyParams) (CustomPolicy, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateIdentity(ctx context.Context, arg UpdateIdentityParams) (Identity, error)
	UpdateIdentityRole(ctx context.Context, arg UpdateIdentityRoleParams) error
	UpdateInstallationApplied(ctx context.Context, id int64) error
	UpdateInstallationState(ctx context.Context, arg UpdateInstallationStateParams) error
	UpdateModuleInstallation(ctx context.Context, arg UpdateModuleInstallationParams) (ModuleInstallation, error)
	UpdatePolicyModule(ctx context.Context, arg UpdatePolicyModuleParams) (PolicyModule, error)
	UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
