// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention_settings.sql

package db

import (
	"context"
)

const GetRetentionSetting = `-- name: GetRetentionSetting :one
SELECT entity_kind, purge_after_days, mode, updated_at, updated_by FROM retention_settings WHERE entity_kind = ?1
`

func (q *Queries) GetRetentionSetting(ctx context.Context, entityKind string) (RetentionSetting, error) {
	row := q.db.QueryRowContext(ctx, GetRetentionSetting, entityKind)
	var i RetentionSetting
	err := row.Scan(
		&i.EntityKind,
		&i.PurgeAfterDays,
		&i.Mode,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const ListRetentionSettings = `-- name: ListRetentionSettings :many

SELECT entity_kind, purge_after_days, mode, updated_at, updated_by FROM retention_settings ORDER BY entity_kind
`

// Retention setting queries.
func (q *Queries) ListRetentionSettings(ctx context.Context) ([]RetentionSetting, error) {
	rows, err := q.db.QueryContext(ctx, ListRetentionSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetentionSetting{}
	for rows.Next() {
		var i RetentionSetting
		if err := rows.Scan(
			&i.EntityKind,
			&i.PurgeAfterDays,
			&i.Mode,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateRetentionSetting = `-- name: UpdateRetentionSetting :one
UPDATE retention_settings
SET purge_after_days = ?1,
    mode = ?2,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = ?3
WHERE entity_kind = ?4
RETURNING entity_kind, purge_after_days, mode, updated_at, updated_by
`

type UpdateRetentionSettingParams struct {
	PurgeAfterDays interface{} `json:"purge_after_days"`
	Mode           string      `json:"mode"`
	UpdatedBy      interface{} `json:"updated_by"`
	EntityKind     string      `json:"entity_kind"`
}

func (q *Queries) UpdateRetentionSetting(ctx context.Context, arg UpdateRetentionSettingParams) (RetentionSetting, error) {
	row := q.db.QueryRowContext(ctx, UpdateRetentionSetting,
		arg.PurgeAfterDays,
		arg.Mode,
		arg.UpdatedBy,
		arg.EntityKind,
	)
	var i RetentionSetting
	err := row.Scan(
		&i.EntityKind,
		&i.PurgeAfterDays,
		&i.Mode,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
