// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: roles.sql

package db

import (
	"context"
	"database/sql"
)

const AssignRoleToIdentity = `-- name: AssignRoleToIdentity :exec
INSERT OR IGNORE INTO identity_roles (identity_id, role_id, assigned_by)
VALUES (?1, ?2, ?3)
`

type AssignRoleToIdentityParams struct {
	IdentityID int64         `json:"identity_id"`
	RoleID     int64         `json:"role_id"`
	AssignedBy sql.NullInt64 `json:"assigned_by"`
}

func (q *Queries) AssignRoleToIdentity(ctx context.Context, arg AssignRoleToIdentityParams) error {
	_, err := q.db.ExecContext(ctx, AssignRoleToIdentity, arg.IdentityID, arg.RoleID, arg.AssignedBy)
	return err
}

const CreateRole = `-- name: CreateRole :one

INSERT INTO roles (tenant_id, slug, name, description, is_builtin, template_slug)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, tenant_id, slug, name, description, is_builtin, template_slug, permissions, created_at, updated_at
`

type CreateRoleParams struct {
	TenantID     int64          `json:"tenant_id"`
	Slug         string         `json:"slug"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	IsBuiltin    bool           `json:"is_builtin"`
	TemplateSlug sql.NullString `json:"template_slug"`
}

// Role queries - matches the roles and identity_roles tables in
// db/schema/003_roles_software_logs.sql. Roles are per tenant RBAC
// definitions beyond the builtin identities.role slugs; identity_roles
// links them to identities.
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, CreateRole,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.IsBuiltin,
		arg.TemplateSlug,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsBuiltin,
		&i.TemplateSlug,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRole = `-- name: GetRole :one
SELECT id, tenant_id, slug, name, description, is_builtin, template_slug, permissions, created_at, updated_at FROM roles WHERE id = ?1
`

func (q *Queries) GetRole(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRowContext(ctx, GetRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsBuiltin,
		&i.TemplateSlug,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRoleBySlug = `-- name: GetRoleBySlug :one
SELECT id, tenant_id, slug, name, description, is_builtin, template_slug, permissions, created_at, updated_at FROM roles
WHERE tenant_id = ?1 AND slug = ?2
LIMIT 1
`

type GetRoleBySlugParams struct {
	TenantID int64  `json:"tenant_id"`
	Slug     string `json:"slug"`
}

func (q *Queries) GetRoleBySlug(ctx context.Context, arg GetRoleBySlugParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, GetRoleBySlug, arg.TenantID, arg.Slug)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsBuiltin,
		&i.TemplateSlug,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListRolesByTenant = `-- name: ListRolesByTenant :many
SELECT id, tenant_id, slug, name, description, is_builtin, template_slug, permissions, created_at, updated_at FROM roles
WHERE tenant_id = ?1
ORDER BY is_builtin DESC, name
`

func (q *Queries) ListRolesByTenant(ctx context.Context, tenantID int64) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, ListRolesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsBuiltin,
			&i.TemplateSlug,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRolesForIdentity = `-- name: ListRolesForIdentity :many
SELECT r.id, r.tenant_id, r.slug, r.name, r.description, r.is_builtin, r.template_slug, r.permissions, r.created_at, r.updated_at FROM roles r
JOIN identity_roles ir ON ir.role_id = r.id
WHERE ir.identity_id = ?1
ORDER BY r.name
`

func (q *Queries) ListRolesForIdentity(ctx context.Context, identityID int64) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, ListRolesForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsBuiltin,
			&i.TemplateSlug,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveRoleFromIdentity = `-- name: RemoveRoleFromIdentity :exec
DELETE FROM identity_roles
WHERE identity_id = ?1 AND role_id = ?2
`

type RemoveRoleFromIdentityParams struct {
	IdentityID int64 `json:"identity_id"`
	RoleID     int64 `json:"role_id"`
}

func (q *Queries) RemoveRoleFromIdentity(ctx context.Context, arg RemoveRoleFromIdentityParams) error {
	_, err := q.db.ExecContext(ctx, RemoveRoleFromIdentity, arg.IdentityID, arg.RoleID)
	return err
}
