// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CreateIdentitySession = `-- name: CreateIdentitySession :one

INSERT INTO identity_sessions (
    identity_id, token_hash, ip_address, user_agent, expires_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5
) RETURNING id, identity_id, token_hash, active_tenant_id, ip_address, user_agent, created_at, expires_at, revoked_at
`

type CreateIdentitySessionParams struct {
	IdentityID int64          `json:"identity_id"`
	TokenHash  string         `json:"token_hash"`
	IpAddress  sql.NullString `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	ExpiresAt  time.Time      `json:"expires_at"`
}

// Server-side session queries. The raw session token is never stored -
// only its SHA-256 hash (token_hash). See pkg/auth/session.go (a later task).
func (q *Queries) CreateIdentitySession(ctx context.Context, arg CreateIdentitySessionParams) (IdentitySession, error) {
	row := q.db.QueryRowContext(ctx, CreateIdentitySession,
		arg.IdentityID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.TokenHash,
		&i.ActiveTenantID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const DeleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM identity_sessions WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteExpiredSessions)
	return err
}

const GetActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, identity_id, token_hash, active_tenant_id, ip_address, user_agent, created_at, expires_at, revoked_at FROM identity_sessions
WHERE token_hash = ?1
  AND revoked_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash string) (IdentitySession, error) {
	row := q.db.QueryRowContext(ctx, GetActiveSessionByTokenHash, tokenHash)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.TokenHash,
		&i.ActiveTenantID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const RevokeSession = `-- name: RevokeSession :exec
UPDATE identity_sessions SET revoked_at = CURRENT_TIMESTAMP WHERE token_hash = ?1
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, RevokeSession, tokenHash)
	return err
}

const SetSessionActiveTenant = `-- name: SetSessionActiveTenant :exec
UPDATE identity_sessions SET active_tenant_id = ?1 WHERE id = ?2
`

type SetSessionActiveTenantParams struct {
	ActiveTenantID sql.NullInt64 `json:"active_tenant_id"`
	ID             int64         `json:"id"`
}

func (q *Queries) SetSessionActiveTenant(ctx context.Context, arg SetSessionActiveTenantParams) error {
	_, err := q.db.ExecContext(ctx, SetSessionActiveTenant, arg.ActiveTenantID, arg.ID)
	return err
}
