// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tenants.sql

package db

import (
	"context"
	"database/sql"
)

const AddAssetToGroup = `-- name: AddAssetToGroup :exec

INSERT INTO group_memberships (group_id, asset_id)
VALUES (?1, ?2)
ON CONFLICT DO NOTHING
`

type AddAssetToGroupParams struct {
	GroupID int64         `json:"group_id"`
	AssetID sql.NullInt64 `json:"asset_id"`
}

// ============================================================================
// Group membership operations
// ============================================================================
func (q *Queries) AddAssetToGroup(ctx context.Context, arg AddAssetToGroupParams) error {
	_, err := q.db.ExecContext(ctx, AddAssetToGroup, arg.GroupID, arg.AssetID)
	return err
}

const AddIdentityToGroup = `-- name: AddIdentityToGroup :exec
INSERT INTO group_memberships (group_id, identity_id)
VALUES (?1, ?2)
ON CONFLICT DO NOTHING
`

type AddIdentityToGroupParams struct {
	GroupID    int64         `json:"group_id"`
	IdentityID sql.NullInt64 `json:"identity_id"`
}

func (q *Queries) AddIdentityToGroup(ctx context.Context, arg AddIdentityToGroupParams) error {
	_, err := q.db.ExecContext(ctx, AddIdentityToGroup, arg.GroupID, arg.IdentityID)
	return err
}

const ClearGroupMembers = `-- name: ClearGroupMembers :exec
DELETE FROM group_memberships WHERE group_id = ?1
`

func (q *Queries) ClearGroupMembers(ctx context.Context, groupID int64) error {
	_, err := q.db.ExecContext(ctx, ClearGroupMembers, groupID)
	return err
}

const CountAssetsInGroup = `-- name: CountAssetsInGroup :one
SELECT COUNT(*) FROM group_memberships
WHERE group_id = ?1 AND asset_id IS NOT NULL
`

func (q *Queries) CountAssetsInGroup(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountAssetsInGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountGroupsByTenant = `-- name: CountGroupsByTenant :one
SELECT COUNT(*) FROM groups WHERE tenant_id = ?1
`

func (q *Queries) CountGroupsByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountGroupsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountIdentitiesInGroup = `-- name: CountIdentitiesInGroup :one
SELECT COUNT(*) FROM group_memberships
WHERE group_id = ?1 AND identity_id IS NOT NULL
`

func (q *Queries) CountIdentitiesInGroup(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountIdentitiesInGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountSitesByTenant = `-- name: CountSitesByTenant :one
SELECT COUNT(*) FROM sites WHERE tenant_id = ?1
`

func (q *Queries) CountSitesByTenant(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSitesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountTenants = `-- name: CountTenants :one
SELECT COUNT(*) FROM tenants
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateGroup = `-- name: CreateGroup :one

INSERT INTO groups (tenant_id, site_id, name, slug)
VALUES (?1, ?2, ?3, ?4) RETURNING id, tenant_id, site_id, name, slug, created_at, group_category, group_scope
`

type CreateGroupParams struct {
	TenantID int64         `json:"tenant_id"`
	SiteID   sql.NullInt64 `json:"site_id"`
	Name     string        `json:"name"`
	Slug     string        `json:"slug"`
}

// ============================================================================
// Group operations
// ============================================================================
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, CreateGroup,
		arg.TenantID,
		arg.SiteID,
		arg.Name,
		arg.Slug,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.GroupCategory,
		&i.GroupScope,
	)
	return i, err
}

const CreateSite = `-- name: CreateSite :one

INSERT INTO sites (tenant_id, name, slug)
VALUES (?1, ?2, ?3) RETURNING id, tenant_id, name, slug, created_at
`

type CreateSiteParams struct {
	TenantID int64  `json:"tenant_id"`
	Name     string `json:"name"`
	Slug     string `json:"slug"`
}

// ============================================================================
// Site operations
// ============================================================================
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, CreateSite, arg.TenantID, arg.Name, arg.Slug)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const CreateTenant = `-- name: CreateTenant :one

INSERT INTO tenants (name, slug)
VALUES (?1, ?2) RETURNING id, name, slug, created_at
`

type CreateTenantParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// Tenant operations
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, CreateTenant, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ?1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteGroup, id)
	return err
}

const DeleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = ?1
`

func (q *Queries) DeleteSite(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteSite, id)
	return err
}

const DeleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = ?1
`

func (q *Queries) DeleteTenant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteTenant, id)
	return err
}

const GetGroup = `-- name: GetGroup :one
SELECT id, tenant_id, site_id, name, slug, created_at, group_category, group_scope FROM groups WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, GetGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.GroupCategory,
		&i.GroupScope,
	)
	return i, err
}

const GetGroupBySlug = `-- name: GetGroupBySlug :one
SELECT id, tenant_id, site_id, name, slug, created_at, group_category, group_scope FROM groups 
WHERE tenant_id = ?1 AND slug = ?2 
LIMIT 1
`

type GetGroupBySlugParams struct {
	TenantID int64  `json:"tenant_id"`
	Slug     string `json:"slug"`
}

func (q *Queries) GetGroupBySlug(ctx context.Context, arg GetGroupBySlugParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, GetGroupBySlug, arg.TenantID, arg.Slug)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.GroupCategory,
		&i.GroupScope,
	)
	return i, err
}

const GetSite = `-- name: GetSite :one
SELECT id, tenant_id, name, slug, created_at FROM sites WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetSite(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRowContext(ctx, GetSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const GetSiteBySlug = `-- name: GetSiteBySlug :one
SELECT id, tenant_id, name, slug, created_at FROM sites 
WHERE tenant_id = ?1 AND slug = ?2 
LIMIT 1
`

type GetSiteBySlugParams struct {
	TenantID int64  `json:"tenant_id"`
	Slug     string `json:"slug"`
}

func (q *Queries) GetSiteBySlug(ctx context.Context, arg GetSiteBySlugParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, GetSiteBySlug, arg.TenantID, arg.Slug)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const GetTenant = `-- name: GetTenant :one
SELECT id, name, slug, created_at FROM tenants WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetTenant(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, GetTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const GetTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, created_at FROM tenants WHERE slug = ?1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, GetTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const IsAssetInGroup = `-- name: IsAssetInGroup :one
SELECT EXISTS(
    SELECT 1 FROM group_memberships 
    WHERE group_id = ?1 AND asset_id = ?2
) as is_member
`

type IsAssetInGroupParams struct {
	GroupID int64         `json:"group_id"`
	AssetID sql.NullInt64 `json:"asset_id"`
}

func (q *Queries) IsAssetInGroup(ctx context.Context, arg IsAssetInGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, IsAssetInGroup, arg.GroupID, arg.AssetID)
	var is_member int64
	err := row.Scan(&is_member)
	return is_member, err
}

const IsIdentityInGroup = `-- name: IsIdentityInGroup :one
SELECT EXISTS(
    SELECT 1 FROM group_memberships 
    WHERE group_id = ?1 AND identity_id = ?2
) as is_member
`

type IsIdentityInGroupParams struct {
	GroupID    int64         `json:"group_id"`
	IdentityID sql.NullInt64 `json:"identity_id"`
}

func (q *Queries) IsIdentityInGroup(ctx context.Context, arg IsIdentityInGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, IsIdentityInGroup, arg.GroupID, arg.IdentityID)
	var is_member int64
	err := row.Scan(&is_member)
	return is_member, err
}

const ListAssetsInGroup = `-- name: ListAssetsInGroup :many
SELECT a.id, a.uuid, a.tenant_id, a.site_id, a.subtype, a.subtype_payload, a.enrollment_state, a.enrolled_at, a.last_seen_at, a.agent_version, a.labels, a.lifecycle_state, a.location, a.owner_identity_id, a.vendor, a.purchase_date, a.purchase_price, a.warranty_expires_at, a.human_id, a.created_at, a.updated_at, a.description, a.managed_by_identity_id FROM assets a
INNER JOIN group_memberships gm ON a.id = gm.asset_id
WHERE gm.group_id = ?1
ORDER BY a.human_id
`

func (q *Queries) ListAssetsInGroup(ctx context.Context, groupID int64) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, ListAssetsInGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TenantID,
			&i.SiteID,
			&i.Subtype,
			&i.SubtypePayload,
			&i.EnrollmentState,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.AgentVersion,
			&i.Labels,
			&i.LifecycleState,
			&i.Location,
			&i.OwnerIdentityID,
			&i.Vendor,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.WarrantyExpiresAt,
			&i.HumanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.ManagedByIdentityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListGroupsBySite = `-- name: ListGroupsBySite :many
SELECT id, tenant_id, site_id, name, slug, created_at, group_category, group_scope FROM groups
WHERE tenant_id = ?1 AND site_id = ?2
ORDER BY name
`

type ListGroupsBySiteParams struct {
	TenantID int64         `json:"tenant_id"`
	SiteID   sql.NullInt64 `json:"site_id"`
}

func (q *Queries) ListGroupsBySite(ctx context.Context, arg ListGroupsBySiteParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, ListGroupsBySite, arg.TenantID, arg.SiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.GroupCategory,
			&i.GroupScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListGroupsByTenant = `-- name: ListGroupsByTenant :many
SELECT id, tenant_id, site_id, name, slug, created_at, group_category, group_scope FROM groups
WHERE tenant_id = ?1
ORDER BY name
`

func (q *Queries) ListGroupsByTenant(ctx context.Context, tenantID int64) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, ListGroupsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.GroupCategory,
			&i.GroupScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListGroupsForAsset = `-- name: ListGroupsForAsset :many
SELECT g.id, g.tenant_id, g.site_id, g.name, g.slug, g.created_at, g.group_category, g.group_scope FROM groups g
INNER JOIN group_memberships gm ON g.id = gm.group_id
WHERE gm.asset_id = ?1
ORDER BY g.name
`

func (q *Queries) ListGroupsForAsset(ctx context.Context, assetID sql.NullInt64) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, ListGroupsForAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.GroupCategory,
			&i.GroupScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListGroupsForIdentity = `-- name: ListGroupsForIdentity :many
SELECT g.id, g.tenant_id, g.site_id, g.name, g.slug, g.created_at, g.group_category, g.group_scope FROM groups g
INNER JOIN group_memberships gm ON g.id = gm.group_id
WHERE gm.identity_id = ?1
ORDER BY g.name
`

func (q *Queries) ListGroupsForIdentity(ctx context.Context, identityID sql.NullInt64) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, ListGroupsForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.GroupCategory,
			&i.GroupScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListIdentitiesInGroup = `-- name: ListIdentitiesInGroup :many
SELECT i.id, i.tenant_id, i.site_id, i.username, i.user_principal_name, i.email, i.display_name, i.given_name, i.surname, i.initials, i.title, i.department, i.company, i.employee_id, i.employee_type, i.manager_id, i.phone_office, i.phone_mobile, i.phone_home, i.fax, i.office, i.street_address, i.city, i.state, i.postal_code, i.country, i.country_code, i.home_directory, i.home_drive, i.profile_path, i.logon_script, i.account_enabled, i.account_locked, i.account_expires_at, i.password_hash, i.password_last_set_at, i.password_never_expires, i.must_change_password, i.last_logon_at, i.logon_count, i.bad_password_count, i.last_bad_password_at, i.role, i.avatar_url, i.locale, i.timezone, i.description, i.notes, i.created_at, i.updated_at FROM identities i
INNER JOIN group_memberships gm ON i.id = gm.identity_id
WHERE gm.group_id = ?1
ORDER BY i.display_name
`

func (q *Queries) ListIdentitiesInGroup(ctx context.Context, groupID int64) ([]Identity, error) {
	rows, err := q.db.QueryContext(ctx, ListIdentitiesInGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Username,
			&i.UserPrincipalName,
			&i.Email,
			&i.DisplayName,
			&i.GivenName,
			&i.Surname,
			&i.Initials,
			&i.Title,
			&i.Department,
			&i.Company,
			&i.EmployeeID,
			&i.EmployeeType,
			&i.ManagerID,
			&i.PhoneOffice,
			&i.PhoneMobile,
			&i.PhoneHome,
			&i.Fax,
			&i.Office,
			&i.StreetAddress,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.CountryCode,
			&i.HomeDirectory,
			&i.HomeDrive,
			&i.ProfilePath,
			&i.LogonScript,
			&i.AccountEnabled,
			&i.AccountLocked,
			&i.AccountExpiresAt,
			&i.PasswordHash,
			&i.PasswordLastSetAt,
			&i.PasswordNeverExpires,
			&i.MustChangePassword,
			&i.LastLogonAt,
			&i.LogonCount,
			&i.BadPasswordCount,
			&i.LastBadPasswordAt,
			&i.Role,
			&i.AvatarUrl,
			&i.Locale,
			&i.Timezone,
			&i.Description,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSitesByTenant = `-- name: ListSitesByTenant :many
SELECT id, tenant_id, name, slug, created_at FROM sites
WHERE tenant_id = ?1
ORDER BY name
`

func (q *Queries) ListSitesByTenant(ctx context.Context, tenantID int64) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, ListSitesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTenants = `-- name: ListTenants :many
SELECT id, name, slug, created_at FROM tenants ORDER BY name
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, ListTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveAssetFromGroup = `-- name: RemoveAssetFromGroup :exec
DELETE FROM group_memberships
WHERE group_id = ?1 AND asset_id = ?2
`

type RemoveAssetFromGroupParams struct {
	GroupID int64         `json:"group_id"`
	AssetID sql.NullInt64 `json:"asset_id"`
}

func (q *Queries) RemoveAssetFromGroup(ctx context.Context, arg RemoveAssetFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, RemoveAssetFromGroup, arg.GroupID, arg.AssetID)
	return err
}

const RemoveIdentityFromGroup = `-- name: RemoveIdentityFromGroup :exec
DELETE FROM group_memberships
WHERE group_id = ?1 AND identity_id = ?2
`

type RemoveIdentityFromGroupParams struct {
	GroupID    int64         `json:"group_id"`
	IdentityID sql.NullInt64 `json:"identity_id"`
}

func (q *Queries) RemoveIdentityFromGroup(ctx context.Context, arg RemoveIdentityFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, RemoveIdentityFromGroup, arg.GroupID, arg.IdentityID)
	return err
}

const SearchGroups = `-- name: SearchGroups :many
SELECT id, tenant_id, site_id, name, slug, created_at, group_category, group_scope FROM groups
WHERE tenant_id = ?1
  AND name LIKE '%' || ?2 || '%'
ORDER BY name
LIMIT ?3
`

type SearchGroupsParams struct {
	TenantID int64          `json:"tenant_id"`
	Search   sql.NullString `json:"search"`
	Limit    int64          `json:"limit"`
}

func (q *Queries) SearchGroups(ctx context.Context, arg SearchGroupsParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, SearchGroups, arg.TenantID, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.GroupCategory,
			&i.GroupScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateGroup = `-- name: UpdateGroup :one
UPDATE groups SET 
    name = ?1, 
    site_id = ?2
WHERE id = ?3
RETURNING id, tenant_id, site_id, name, slug, created_at, group_category, group_scope
`

type UpdateGroupParams struct {
	Name   string        `json:"name"`
	SiteID sql.NullInt64 `json:"site_id"`
	ID     int64         `json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, UpdateGroup, arg.Name, arg.SiteID, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.GroupCategory,
		&i.GroupScope,
	)
	return i, err
}

const UpdateSite = `-- name: UpdateSite :one
UPDATE sites SET 
    name = ?1
WHERE id = ?2
RETURNING id, tenant_id, name, slug, created_at
`

type UpdateSiteParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, UpdateSite, arg.Name, arg.ID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const UpdateTenant = `-- name: UpdateTenant :one
UPDATE tenants SET 
    name = ?1
WHERE id = ?2
RETURNING id, name, slug, created_at
`

type UpdateTenantParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, UpdateTenant, arg.Name, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
